### PR TITLE
22183 multiple series(one being scatter) may cause wrong yAxis in boost

### LINKED ISSUE #22183: yAxis max value is calculated incorrectly for scatterplot with multiple series when using boost module
#### Background

- We found this bug after upgrading Highcharts from v10 to v11. In v10 this is working correctly, so this is a regression in v11.
- After the v11 upgrade the yAxis has the correct range without the boost module, but when the boost module is added the yAxis range is incorrect.

#### Expected behaviour

For scatterplots with multiple series and many data points the max value of the yAxis should be calculated based on the series with the largest range, as in the image below (where the boost module is not enabled):

without_boost_mode

#### Actual behaviour

The yAxis max is calculated based on the series with the most data-points, but with a smallest range, as in the image below (with boost module enabled):

with_boost_mode

#### Live demo with steps to reproduce

1. Open this jsFiddle to see the chart with the boost module enabled, and observer the yAxis only goes up to 1400: https://jsfiddle.net/vdjsep39/2/
2. Compare to this jsFiddle where the yAxis is scaled correctly to 5000: https://jsfiddle.net/djcx10Lh/1/

#### Product version

Highcharts Core 11.4.8
With Highcharts boost module (also on 11.4.8)

#### Affected browser(s)

All

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #22183, wrong y-axis extremes when using multiple boosted series

### CODE REVIEW

**Review by bre1470 — APPROVED** [review]
Looks good! 👍

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks!

Can you add a test too? Probably we can reuse one of the existing tests. Also, instead af adding thousands of points to trigger boost mode, test with merely a few points and `boostThreshold: 1`.

Also, provide a more recognizable description for the changelog. Instead of describing the fix (for other team members), describe the problem it fixes in a way that the users recognize. The description in the bug report is a good starting point.

**Comment by MarkusBarstad** [comment]
> Thanks!
> 
> Can you add a test too? Probably we can reuse one of the existing tests. Also, instead af adding thousands of points to trigger boost mode, test with merely a few points and `boostThreshold: 1`.

Unfortunately, @TorsteinHonsi , I cannot recreate the issue with a low amount of points 🤔 

Testing reveals that we need at least around 200-300 points for the scatter series for the issue to trigger.

How should we proceed 🤔 ?

**Comment by TorsteinHonsi** [comment]
No problem, 2-300 points is also "a few" points in this context.

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
