### PR TITLE
bugfix/16675-custom-annotations-button

### LINKED ISSUE #16675: NavigationBindings: Cannot create a custom button
#### Expected behaviour
When creating the button as SVG shape it should work normally. 

#### Actual behaviour
There is an error, which is called by `bindings.button.className.indexOf('highcharts-disabled-btn') === -1`

#### Live demo with steps to reproduce

https://jsfiddle.net/BlackLabel/by126xor/
Click on the button next to the exporting button

#### Product version
v9.3.1

#### Affected browser(s)
all

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #16675, adding annotation from a custom button was not possible, if the button had a custom SVG symbol.

### CODE REVIEW

**Comment by OldBuddy** [comment]
@kamil-musialowski maybe better to reuse [classList](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) instead?

**Comment by kamil-musialowski** [comment]
@OldBuddy, thank you for your suggestion and contribution. It's a great idea! I've added the requested changes.

**Comment by OldBuddy** [comment]
@kamil-musialowski thanks! what about reusing [existing utility method](https://github.com/highcharts/highcharts/blob/master/ts/Accessibility/Utils/HTMLUtilities.ts#L59)?

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
