### PR TITLE
Fixed gantts connection lines not clearing/redrawing properly

### LINKED ISSUE #17833: Gantt chart: Connecting lines will not be fully deleted/redrawn on Drag'nDrop
#### Expected behaviour
All connecting lines will be redrawn after drag n' drop

#### Actual behaviour
If more than one connecting lines are defined, only the last defined line will be redrawn/removed on d&d. All other lines are still visible.
grafik

#### Live demo with steps to reproduce
https://jsfiddle.net/dmt3fypL/9/

#### Product version
Highcharts Gantt JS v10.2.1 (2022-08-29)

#### Affected browser(s)
FF 102.3.0esr (64-Bit)
Chrome 102.0.5200.0
Edge 106.0.1370.34

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #17833, all connectors weren't redrawn/deleted when updating them

The reason for this issue is the code in `Pathfinder.ts`, from line [744 to 770](https://github.com/highcharts/highcharts/blob/master/ts/Gantt/Pathfinder.ts#L744), during the update-function where it stores what connections are still present, and destroys old ones.

Specifically this conditional at line [752](https://github.com/highcharts/highcharts/blob/master/ts/Gantt/Pathfinder.ts#L752) is the culprit:
```
if (
    oldConnections[j].fromPoint ===
        pathfinder.connections[k].fromPoint &&
    oldConnections[j].toPoint ===
        pathfinder.connections[k].toPoint
)
```

It makes no distinction between lines to and from the same datapoint since they by necessity have the same `toPoint` and `fromPoint` values. This causes the code to store more than one reference to the same connection, and not storing others, on `redraw`.

Question:
- Should I implement a unique id for each connection, maybe in `Connection.ts` we can then use to distinguish between connecting lines? 
- Another option is to also check for the types of the connections, which will make the [demo](https://jsfiddle.net/dmt3fypL/9/) in the issue function, but will cause the same issue if you have multiple connections with same type, source, and destination.

TODO:
- [x] Create a fix for connecting lines which are not being cleared/redrawn properly

### CODE REVIEW

**Comment by oysteinmoseng** [comment]
The Pathfinder module was never made with the intention of having multiple connections for the same points, so this could break in several places if we are unlucky...

Adding a UID is probably tricky here, since what we are doing is looking at the chart options and trying to match those against the graphics that have been drawn. We also need to be able to update a connection by changing its options, which means what we are really trying to do is look at the options and see if the resulting connection from those options has already been drawn.

I don't see a way to accomplish that other than to compare the options property by property (or store a hash to compare or similar). That will be overkill for 99.8% of cases, so I suggest just comparing on `type` in addition to the existing checks.

Disclaimer: I have not touched this code in years and may be totally wrong 😬

**Comment by oysteinmoseng** [comment]
Nice! You could probably just do `oldCon.options && newCon.options && oldCon.options.type === newCon.options.type` in this case.

**Comment by oysteinmoseng** [comment]
Actually scratch that - the connections are also the same if the types are both undefined... So maybe `(oldCon.options && oldCon.options.type) === (newCon.options && newCon.options.type)`. Alternatively `oldCon.options?.type === newCon.options?.type` would be neat, but I think that still transpiles pretty verbosely and is to be avoided.

**Comment by MarkusBarstad** [comment]
This functions on my end now!

**Comment by TorsteinHonsi** [comment]
Looks good to me! Asking a review from @oysteinmoseng too, to be on the safe side.

**Review by oysteinmoseng — APPROVED** [review]
Nice!

**Pull request merged**
