### PR TITLE
bugfix/20166-ticks-visibility-outside-axis

### LINKED ISSUE #20166: Plot-background and x/y axis groups are misaligned for column series
#### Expected behaviour
`plotBorder` should encapsulate all `gridLines` by default.

#### Actual behaviour
For column series, when one creates a `plotBorder`, a `gridLine` outside of plot space can be seen. This does, however, only appear in utils, not in jsfiddle (there it does not appear in the DOM either)

For the `yAxis` it appears by default, 
for the `xAxis` it only appears when `pointPlacement` is set.

From looking at the values in the DOM it seems like `minPointOffset` or `minPixelPadding` should apply somewhere,
and it seems like x and y axis `groups` are not positioned correctly compared to `plotBackground.`

#### Live demo with steps to reproduce
https://jsfiddle.net/mkb93/qm1v4nxu/

#### Product version
Highcharts 11.2

#### Affected browser(s)
Chromium-based, Firefox, maybe more

### PR DESCRIPTION
**Pull request by hubertkozik**
Fixed #20166, ticks and gridlines shouldn't be visible outside the axis.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206008636612601

### CODE REVIEW

**Review by MarkusBarstad — APPROVED** [review]
Awesome work! 

Do you know why this does not break animation? Is it because we here check for whether the tick is new, or is that check there so that we only have to check for this once?

**Comment by hubertkozik** [comment]
Yes, 

> check for whether the tick is new

 is the key, because if the tick already exists then it probably should be re-rendered to new position, new style etc.

**Review by bre1470 — APPROVED** [review]
Nice fix! Looks good. 👍

**Review by TorsteinHonsi — APPROVED** [review]
Thanks, looks good! I managed to squeeze a few more bytes out, after CI checks I'll merge.

**Review by KacperMadej — APPROVED** [review]

**Pull request merged**
