### PR TITLE
dash/dg-min-visible-rows

### PR DESCRIPTION
**Pull request by ddragula**
An attempt to introduce a minimum height for the DataGrid tbody - `minVisibleRows` option.

Ultimately, this should only work when the container height is not set, so that the `tbody` height can be reduced when the user wants it. Unfortunately, even when container height is not set, `getStyle(container, 'height')` return always a value.

### CODE REVIEW

**Review by stitot — COMMENTED** [review]
If I increase padding: 

```
:root {
  --padding: 20px;
}
```
then `minVisibleRows` breaks apart.

**Comment by stitot** [comment]
> Unfortunately, even when container height is not set, `getStyle(container, 'height')` return always a value.

I guess this could be checked using `element.style.height` if set inline on the element, or a monster loop running through the actual CSS.

Pseudo:
```
for (const sheet of document.styleSheets)
     for (const rule of sheet.cssRules) 
```
But that is perhaps overkill for this particular need.

**Comment by stitot** [comment]
I'm also wondering why the `caption` is within the table borders here. If you look at https://jsfiddle.net/stitot/r1vpqtbo/ that is not the case, and CSS/markup seems the same?

**Comment by stitot** [comment]
> In this demo, these red borders are set to `container`

Is no caption to check here. Look at e.g. http://localhost:3030/samples/#view/data-grid/basic/overview

**Comment by ddragula** [comment]
Oh, I confused `caption` with `credits`. You are right, I see that setting `display: flex` on the table caused `caption` to be included inside the table border. The only solution that comes to my mind now is to drag the caption outside the table - the question is whether it won't affect a11y, but from what I remember, table caption is not read by screen readers anyway.

**Comment by stitot** [comment]
But, do we really need to introduce `flex` on `<table>`, ref. https://highsoft.slack.com/archives/CNBT45U3U/p1733228543012089? The issue with `<caption>` just highlights that default table rendering is destroyed, and we kind of loose control here.

**Comment by ddragula** [comment]
We will try to cover it in the discussion tomorrow, but generally, the default table rendering is not exactly what we want when we have scroll available in tbody.

We need to somehow size the tbody so that it fills all the available space in the container, while still making room for `thead`, `caption` and `credits`. The approach before flex was as follows:

A resize observer was attached to the table, and when its size changed, the `reflow` method was called. The `reflow` method contained, among other things, logic that set the height of the `tbody`, based on the height of the container, minus the height of the elements outside the `tbody`. If the recalculated height was slightly different from the height that was being set, and this repeated, the process would loop. The problem did not occur when the `container` had a fixed height, but when the height was set to `auto`, we had an infinity loop.

Using flex allows us to get rid of this logic and take advantage of the benefits of CSS. When using a non-virtualized, non-scrollable table, `display: flex` is not necessary.

**Comment by stitot** [comment]
Yes, I absolutely see the upsides here, and as long as we can guarantee excellent a11y support and hopefully no "dirty" hacks for e.g. positioning of caption I'm fine with it. Let's discuss tomorrow.

**Pull request closed without merging**
