### PR TITLE
Allow logarithmic axis for negative values

### LINKED ISSUE #4276: Highstock: Logarithmic + series.compare "percent"
Hello

How might i do a logarithmic line chart with rebasing (ie series.compare as "percent")?
My jsfiddle works when you comment out the plotOptions.series.compare: "percent"

http://jsfiddle.net/axelnormand/mw8w8ea8/

Many thanks

### PR DESCRIPTION
**Pull request by JannesMeyer**
Fix #4276

### CODE REVIEW

**Comment by JannesMeyer** [comment]
Hello highcharts!

This is my first pull request here.

I have created a pull request for @TorsteinHonsi  and @pawelfus 's patches from #4276. Is there any reason why this should not be merged into the main distribution of highcharts?

**Comment by TorsteinHonsi** [comment]
> Is there any reason why this should not be merged into the main distribution of highcharts?

Yes, as noted in #4276, this is not a logarithmic axis anymore. See my explanation there. 

This is however a frequent question, so maybe we should consider allowing this broken log axis as an option.

**Comment by JannesMeyer** [comment]
@TorsteinHonsi you are right. Actually the chart looks terrible with this hack when Y values are close to 0 (which happens a lot when `compare: 'percent'` is turned on).

However, I have figured out what the real solution to this problem (compare: percent + logarithmic axis) should be. I need to add 100 to every Y value (after being processed by the compare function). So every line in the graph would start at 100% instead of 0%.

That way you never get negative percentages if the original data is always >=0 (e.g. stock prices).

**Comment by JannesMeyer** [comment]
The line that calculates the percent comparison seems to be line 548 in StockChart.js: https://github.com/highcharts/highcharts/blob/67f1bfaba30466ca29aaf55ae139e3822bdbd7c5/js/parts/StockChart.js#L548

And it doesn't look like there is a configuration value to change the offset.

**Comment by TorsteinHonsi** [comment]
It would be fairly simple to add an option that sets whether the percent comparison should start at 0 or 100. With your knowlegde of stock charting @pawelfus, do you think this is something we should do? I remember a support case a couple of months back, I think the client was requesting the same.

**Comment by pawelfus** [comment]
Yes, I think this should be configurable.

**Comment by sebastianbochan** [comment]
I agree with @pawelfus  especially that some users sent us a request to change start point.

**Pull request closed without merging**
