### PR TITLE
Db/demos-resize-flag

### PR DESCRIPTION
**Pull request by sebastianbochan**

### CODE REVIEW

**Review by karolkolodziej — CHANGES_REQUESTED** [review]
Waiting for the main branch to be fixed and for CI.

In the meantime could you please explain why removing it?

**Comment by sebastianbochan** [comment]
The `isResizable` param is only in options and does not cover the real functionality in the code ;) 

Instead of adding this option, Pawel decided to remove it from demos.

**Comment by karolkolodziej** [comment]
If so, please remove it from each file including `.test.js`, `.mjs` and `.md`

**Review by pawellysy — APPROVED** [review]
LGTM!

**Review by karolkolodziej — APPROVED** [review]

**Pull request merged**
