### PR TITLE
bugfix/20456-boosted-heatmap-not-rendering

### LINKED ISSUE #20456: Boosted heatmap series not rendered in 11.3.0
#### Expected behaviour
Boosted heatmap series should be rendered

#### Actual behaviour
Boosted heatmap series is not rendering

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/umh54k23/

#### Product version
Highcharts v11.3.0

#### Last working version
Highcharts v11.2.0

#### Affected browser(s)
All

_Internal note:_
Bisected to: https://github.com/highcharts/highcharts/commit/a67ba29717127638d1e1c742b16bcb6f50e25986

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #20456, boosted heatmaps were not rendering.

Note: Not sure if this fix truly addresses the root issue here. Also I am excited for visual compare 😬 

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206372287259153

### CODE REVIEW

**Review by KacperMadej — COMMENTED** [review]
- About the `turboThreshold`: color axis fails to find extremes based on a heatmap running in turbo mode - [demo](https://jsfiddle.net/BlackLabel/9mkg5bso/1/)

- A note for the future branches: this branch name doesn't follow [the convention](https://github.com/highcharts/highcharts/blob/master/CONTRIBUTING.md#pull-requests).

**Comment by MarkusBarstad** [comment]
> * About the `turboThreshold`: color axis fails to find extremes based on a heatmap running in turbo mode - [demo](https://jsfiddle.net/BlackLabel/9mkg5bso/1/)
Seems to happen [regardless of turbo or boost thresholds](https://jsfiddle.net/eyqk3fb5/15/) in current highcharts 🤔 
Should it still be part of this fix?

**Comment by MarkusBarstad** [comment]
> You should also remove the line, which Torstein suggested here: [#20456 (comment)](https://github.com/highcharts/highcharts/issues/20456#issuecomment-1965960766)

@hubertkozik 
The problem with removing this line is that the demo will not render, and we receive [error #12](https://assets.highcharts.com/errors/12/) :thinking:

FYI, you as well @KacperMadej , there was an issue with the `highcharts/boost/heatmap` demo still not rendering, i [fixed it](https://jsfiddle.net/oj2p0trk/1/) but the fix has therefore changed a bit.

**Comment by hubertkozik** [comment]
@MarkusBarstad From what I can see in one of the OP demos from the GH thread the issue is not fixed: https://jsfiddle.net/BlackLabel/eqk17uh6/

Also, we definitely need a unit-test for this issue to prevent regression in the future.

Regarding the `turboThreshold: Number.MAX_VALUE` also needs to be removed, because it disables boost in this demo.
To prevent error #12 you can change the data from CSV or change the data in `complete` callback (but then the performance is worse, because of additional calculations in browser), like here: https://jsfiddle.net/BlackLabel/xh0wy8gb/

It should work similar to v10.3.3: https://jsfiddle.net/BlackLabel/6zgjhbx1/

**Comment by MarkusBarstad** [comment]
Thanks for input @hubertkozik !
I have a fix for [this one case](https://jsfiddle.net/mkb93/72r9cbez/16/) but somehow this breaks [this other demo](https://jsfiddle.net/mkb93/a5bsrxkv/2/) :grimacing: Will keep debugging it

**Comment by KacperMadej** [comment]
The second demo lacks data module - with it added it throws an error. https://jsfiddle.net/BlackLabel/zvgupw68/

**Comment by MarkusBarstad** [comment]
Alright, @KacperMadej thank you!

Both demos should run now, however I am having issues with the `Large Heatmap` in jsfiddle, regardless of whether I retreive `highcharts.js` locally or from `https://code.highcharts.com/ `. 

It does however function locally in utils.

Here is the [other demo](https://jsfiddle.net/ynq531am/9/), using the latest commit.

I am kind of unsure if the fix is alright though. I basically avoid the problematic code you highlighted [by checking if extremes are set on a heatmap](https://github.com/highcharts/highcharts/pull/20873/commits/030d5cb49dfdc6a392b78ee78033a6f64da4e5fb#diff-957079c8eb035023bfe220cb4ee38302f616bbb618bc75014576a62d7cbec3a9). 

Should dig harder for some way to resolve this at an earlier stage in the code? What do you think?

**Comment by MarkusBarstad** [comment]
@KacperMadej @hubertkozik 

Alright, so I think I have at least arrived at a better diagnosis here:

`scatterProcessData` did not work correctly for the heatmap, [thus we avoid it for the heatmap](https://github.com/highcharts/highcharts/blob/20456-boosted-heatmap-series-not-rendered-in-1130/ts/Extensions/Boost/BoostSeries.ts#L1457). 

But whithout running it, heatmap needs to propegate its `processedXData` and `processedYData` arrays in another way.

My fix is to do it in the heatmap's `translate`-function (for the vanilla Series ancestor class this also occurs in its translate function).

Finally to make the heatmap work, `hasData` now looks for `xData` and not for `processedXData` as it still is not propegated when heatmap's `hasData` is called.

**Review by hubertkozik — APPROVED** [review]

**Comment by MarkusBarstad** [comment]
> The whole idea of removing `turboThreshold` and replacing it with a more complex and custom `complete` callback seems strange to me. What am I missing?

My apologies I had forgotten about this part of the fix, @TorsteinHonsi 

I must admit I do not quite understand the problem of `turboThreshold` but unless I am misinterpreting it was [stated here](https://github.com/highcharts/highcharts/issues/20456#issuecomment-1965960766) that it should be removed.

Once `turboThreshold` is gone, Highcharts will not accept the csv data as-is, thus the need for the `complete`-function changing the csv data into nested array data.

We could of course hard-code the data as nested array data, but then I am not sure where we ought to call the `new Date` constructor on the `start` [variable which is used](https://github.com/highcharts/highcharts/blob/e171198b26cb338d872dedb43748bc6b1d741418/samples/highcharts/boost/heatmap/demo.js#L8) for benchmarking the demo.

How should we proceed 🤔 ?

**Comment by TorsteinHonsi** [comment]
> I must admit I do not quite understand the problem of `turboThreshold` but unless I am misinterpreting it was [stated here](https://github.com/highcharts/highcharts/issues/20456#issuecomment-1965960766) that it should be removed.

I think my comment was a bit premature. We can't simply remove `turboThreshold`, because the data is actually in object format. And removing it just to replace it with an even uglier workaround is of course not what we want either. Also, the non-boosted heatmap behaves the same when it comes to `turboThreshold`. So we do nothing with that.

As far as I understand it, the issue now is the error message from `hasData`: https://jsfiddle.net/highcharts/pym68ou5/ . So let's focus on that part.

**Comment by MarkusBarstad** [comment]
> As far as I understand it, the issue now is the error message from `hasData`: https://jsfiddle.net/highcharts/pym68ou5/ . So let's focus on that part.

Alright, @TorsteinHonsi
- `hasData` [does not throw anymore](https://jsfiddle.net/t6rany2c/4/), 
- demo back in its original state (no `complete`-function parsing data, and re-added `turboThreshold`),
- all boosted heatmaps now render

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
