### PR TITLE
Added rangeSelector.buttons.description option for AT. Closes #14437.

### LINKED ISSUE #14437: Custom aria labels for range selector buttons
Looking at [this demo](http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/stock/accessibility/accessible-stock/), the range selector buttons are accessible to screen reader users, but the labels mirror the button text.

It should be possible to configure a custom label text, so that the time abbreviations can be explained.

### PR DESCRIPTION
**Pull request by oysteinmoseng**
Added `rangeSelector.buttons.title` option for assistive technology and general accessability, see #14437.
___
It is now possible to define custom accessible labels for each individual range selector button. This is done through the optional `rangeSelector.buttons.description` option. The default buttons have these descriptions added out of the box. Where a description is not supplied, the button text is used, as before.

It is recommended to add the descriptions since many screen readers will announce confusing information when presented with these abbreviations. `1m` can for example be announced as `One minute`.

We might want to consider if these buttons should have a tooltip so that non-AT users can benefit from the abbreviation explanations on hover.

```js
buttons: [{
  type: 'month',
  count: 1,
  text: '1m',
  description: '1 month'
}, {
  // ...
}, {
  type: 'ytd',
  text: 'YTD',
  description: 'Year to Date'
}, {
  type: 'all',
  text: 'All'
 }]
```

### CODE REVIEW

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks!

Now that we put this in the API, perhaps we should also supply it as a `title` to the buttons? It would be a simple addition, and also make the buttons more accessible regardless of screen readers.

And if so, we should probably call it `title` in accordance with for example `contextButton.titleKey`.

PS: How about internationalization?

**Comment by oysteinmoseng** [comment]
Yes, even better if we can add this as a `<title>` element (in which case we might also be able to ditch the `aria-label`).

As for internationalization, I assume that would be the same as for the `1m`, `6m`, `YTD`, `All` strings etc. I am not sure it is necessary to add them to the `lang` options when they can be configured elsewhere?

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
> Added now in a11y module, could consider adding the title element in the core instead.

Yes, I think we should do it in the core. And we don't need a new function to set the title, we have it built in to the `SVGElement`: https://jsfiddle.net/highcharts/zecLkhqn/

**Review by TorsteinHonsi — APPROVED** [review]
Looking great! Pending CI tests.

**Pull request merged**
