### PR TITLE
15468-lastPrice-label-docs

### LINKED ISSUE #15468: lastPrice label should be customizable: docs
#### Expected behaviour
Test that compatibility and add documentation under `lastPrice.label`.

#### Actual behaviour
It looks like [options](https://api.highcharts.com/highstock/yAxis.crosshair.label) for the `crosshair` label can be also applied to the `lastPrice` indicator label.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/xy5ar81h/

#### Product version
Highstock JS v9.0.1 (2021-02-15)

Similar issue regarding `lastVisiblePrice`: #15199

### PR DESCRIPTION
**Pull request by pawellysy**
Fixed #15468, added `lastPrice.label` docs.

### CODE REVIEW

**Review by raf18seb — APPROVED** [review]
Looks fine, thanks!

Can you edit the description and put the API name into the "\`" quote?
`Like this`

Also, is label `Changelog: Bugfix` correct?

**Comment by pawellysy** [comment]
> Looks fine, thanks!
> 
> Can you edit the description and put the API name into the "`" quote?
> `Like this`
> 
> Also, is label `Changelog: Bugfix` correct?

@raf18seb Done, thanks! Probably `Changelog: Docs` is more accurate 👍

**Review by TorsteinHonsi — APPROVED** [review]
Thanks! Approved from my end, pending the other reviewers before merge.

**Review by bre1470 — APPROVED** [review]
Doclets look fine! 👍

**Review by karolkolodziej — APPROVED** [review]

**Review by pawelfus — APPROVED** [review]

**Pull request merged**
