### PR TITLE
Highstock: Fixed #7219, crosshair label was incorrect when using mult…

### LINKED ISSUE #7219: Crosshair label not showing correctly on multiple series
#### Expected behaviour
Crosshair label should show differently on different series.
On series 1:
image
On series 2:
image

#### Actual behaviour
But when moving the cursor from series 1 to series 2 and then back to series 1, it shows incorrectly:
image

#### Live demo with steps to reproduce
http://jsfiddle.net/Ladgk4yp/4/

#### Affected browser(s)
Google Chrome 60.0

### PR DESCRIPTION
**Pull request by pawelfus**
…iple panes.

### CODE REVIEW

**Comment by pawelfus** [comment]
Additionally implemented 80chars rule in the responsible method for a bug.

**Comment by Karthikeyan1993** [comment]
@pawelfus  is there any way to change the crosshair label shape like blow image

http://i.imgur.com/5fBPnFs.jpg

**Comment by pawelfus** [comment]
Hi @Karthikeyan1993 - it should be possible, but this shape is not in our build-in list. Please contact with out support: https://www.highcharts.com/support

**Comment by Karthikeyan1993** [comment]
@pawelfus you're always life saver..Thanks much

**Pull request merged**
