### PR TITLE
bugfix/21255-tooltip-with-outside-expanding-documentElement-width

### LINKED ISSUE #21255: Tooltip with `outside: true` renders outside the viewport
#### Expected behaviour
Tooltip should not overflow the viewport

#### Actual behaviour
tooltip sometimes renders outside the viewport (causes scrollbar to appear)

this started in version 11.0.0
most likely related to one of  these:
https://github.com/highcharts/highcharts/pull/18681
https://github.com/highcharts/highcharts/pull/18692

#### Product version
11.0.0-11.4.3

CleanShot 2024-05-30 at 12 19 18

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #21255, tooltip with `outside` rendered outside viewport, making `document.documentElement` expand

Not entirely sure if its okay to remove `document.documentElement.scrollWidth` as a max-value used in positioning the tooltip, but it seemed the simplest solution to make the tooltip respect the viewport. `outside` still works

### CODE REVIEW

**Comment by bre1470** [comment]
This is not fixing it for me. See https://jsfiddle.net/bre1470/wu6nbm3g/2/

To solve this issue the animation direction needs to be flipped (coming from left, than from right side), when on the right edge (positioned left size from the point), so that the tooltip keeps inside the container even when animated.

Simple fix could be to disable animation, when toolbar is not rendered in default position.

**Review by bre1470 — COMMENTED** [review]
This is not fixing it for me. See https://jsfiddle.net/bre1470/wu6nbm3g/2/

To solve this issue the animation direction needs to be flipped (coming from left, than from right side), when on the right edge (positioned left size from the point), so that the tooltip keeps inside the container even when animated.

Simple fix could be to disable animation, when toolbar is not rendered in default position.

**Comment by MarkusBarstad** [comment]
> This is not fixing it for me. See https://jsfiddle.net/bre1470/wu6nbm3g/2/
> 
> To solve this issue the animation direction needs to be flipped (coming from left, than from right side), when on the right edge (positioned left size from the point), so that the tooltip keeps inside the container even when animated.
> 
> Simple fix could be to disable animation, when toolbar is not rendered in default position.

Thanks for feedback!

So you are saying that during animation the tooltip can extend outside the chart bounds right? Will try flipping the animation as you suggest!

**Comment by bre1470** [comment]
I still have the effect for some milliseconds, but it recovers from it, so it seems to be fixed.

https://github.com/user-attachments/assets/aa422efe-4a23-4256-a759-0e65f57da9a8

**Review by bre1470 — APPROVED** [review]

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks!

The issue ultimately comes down to the width of the label increasing, so it overflows briefly before animating to the new, adjusted position.

I found that it is probably cheaper, both in terms of performance and weight, to do this adjustment immediately after setting the longer text:

```diff
diff --git a/ts/Core/Tooltip.ts b/ts/Core/Tooltip.ts
index 64f35735f8..b02e0d0a83 100644
--- a/ts/Core/Tooltip.ts
+++ b/ts/Core/Tooltip.ts
@@ -1079,6 +1079,20 @@ class Tooltip {
                             text
                     });
 
+                    // When the length of the label has increased, immediately
+                    // update the x position to prevent tooltip from flowing
+                    // outside the viewport during animation (#21371)
+                    if (this.outside) {
+                        label.attr({
+                            x: clamp(
+                                label.x || 0,
+                                0,
+                                this.getPlayingField().width -
+                                    (label.width || 0)
+                            )
+                        });
+                    }
+
                     if (!styledMode) {
                         label.attr({
                             stroke: (
```

This also gets rid of the very short glimpse of the scrollbar that Sophie mentions. There's however a small glitch with the chevron, but we're now in edge case land so it's probably not worthwhile looking into.

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
