### PR TITLE
tools/dashboards-lint

### PR DESCRIPTION
**Pull request by goransle**
Alternate solution could be to remove Dashboards from `ts/.eslintignore`, and just have a single linting run.

### CODE REVIEW

**Review by bre1470 — APPROVED** [review]
Surprising fix. Looks good. 👍
Has the `dashboards/test-lint` task become redundant?

**Comment by goransle** [comment]
> Surprising fix. Looks good. 👍 Has the `dashboards/test-lint` task become redundant?

It's still used as part of the `dashboards/test` gulp script, which is what runs in the GH action.

**Comment by bre1470** [comment]
Wait, maybe it is then better to run dashboards/test-lint in the lint-dashboards as well, so that the tests are identical with future changes.

**Comment by goransle** [comment]
> Wait, maybe it is then better to run `dashboards/test-lint` in the lint-dashboards as well, so that the tests are identical with future changes.

`gulp` and `lint-staged' doesn't play along too nicely out of the box unfortunately.

**Review by sebastianbochan — APPROVED** [review]
Looks promising! :)

**Comment by TorsteinHonsi** [comment]
Pending review from @oysteinmoseng

**Review by oysteinmoseng — APPROVED** [review]

**Comment by sebastianbochan** [comment]
Can we merge it, @TorsteinHonsi @goransle ?

**Pull request merged**
