### PR TITLE
bugfix/17186-csv-empty-cells

### LINKED ISSUE #17186: chart.getCSV() doesn't add empty cells at the end of the row
`chart.getCSV()`  doesn't add empty cells at the end of the row. Although according to the CSV specification `"Within the header and each record, there may be one or more fields, separated by commas.  Each line should contain the same number of fields throughout the file."` Taken from [rfc4180](https://datatracker.ietf.org/doc/html/rfc4180#section-2). So there should be the same number of delimiters in every row. 

Most CSV parsers do still open the CSV like this. But this thing causes some trouble for the simple solutions, e.g. when you do not want to explicitly ask the user about the delimiter used, but to detect it automatically. If you cannot expect that a CSV has the same number of columns within every row, this adds more errors.

Imagine we have 2 series of points:

    A = [ [1, 0.1], [2, 0.2], [3,0.3] ]
    B = [ [2, 0.5], [4, 1.0] ]  

#### Expected behavior (expected CSV output)
- all rows have equal number of cells  
    
      x,A,B
      1,0.1,
      2,0.2,0.5
      3,0.3,
      4,,1.0

#### Actual behavior

- rows with `x=1` and `x=3` have 2 cells, other rows have 3 cells  

      x,A,B
      1,0.1
      2,0.2,0.5
      3,0.3
      4,,1.0

#### Live demo with steps to reproduce
- [https://jsfiddle.net/odjute63/1/](https://jsfiddle.net/odjute63/1/)

#### Product version
Highcharts 10.0.0 (latest)

#### Affected browser(s)
- all, but it is not a browser-dependent issue

### PR DESCRIPTION
**Pull request by raf18seb**
Fixed #17186, CSV rows were missing delimiters when data was missing at the end of a row.

This is a continuation of: https://github.com/highcharts/highcharts/pull/17195

I checked the above solution and I think it's the best when it comes to performance.
If we'd like to add this logic to the `getDataRows` method, we would have to loop rows one more time. In this case, we could add this code here: https://github.com/highcharts/highcharts/blob/96fb71da571456bd45724df75767e92bfdb014e3/ts/Extensions/ExportData.ts#L793

What do you think @TorsteinHonsi? Should it be even fixed in the first place? As a workaround, the `null` points could be added to data. But, the CSV should have the same number of cells in all rows by definition.

Demo: http://jsfiddle.net/BlackLabel/pxLgb2d6/

### CODE REVIEW

**Comment by TorsteinHonsi** [comment]
@raf18seb 

I think this fix makes sense. And it seems like HTML table is already handling this correctly: https://jsfiddle.net/highcharts/yg9em5dv/1/ .

**Comment by TorsteinHonsi** [comment]
@raf18seb In the latest commit I tried just setting the length of the row, which seems to have the same effect as pushing undefined. It fixes the problem with the missing delimiters. Please have a look if you can see any problems with that.

**Comment by raf18seb** [comment]
Looks good! I only improved a comment because it didn't fit after a variable was removed.

**Comment by raf18seb** [comment]
@TorsteinHonsi

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
