### PR TITLE
ts/logarithmicaxis

### PR DESCRIPTION
**Pull request by bre1470**
Migrated LogarithmicAxis to ES6 pattern.
Related to #12738.

### CODE REVIEW

**Comment by bre1470** [comment]
@TorsteinHonsi Both tests wrap (now) non-existence log/lin functions on the Axis prototype. How do we address that? Do we modify the demos to point to the composition property, or do we duplicate functions to be backward compatible with both demos?

**Comment by pawelfus** [comment]
It's not only demos, users are actually using these solutions - we will break compatibility when changing methods.. Just saying, deprecation process could help here ;) Perhaps for now, modify demos to use new solution and keep backward compatibility?

**Comment by bre1470** [comment]
@pawelfus The problem with the deprecate process works only for documented functions. That is the problem with all these half-official stuff floating around. ;)

**Comment by bre1470** [comment]
That said, I will restore the compatibility. It will hinder the migration though.

**Pull request closed without merging**
