### PR TITLE
bugfix/14143-14434-stickOnContact-useHTML-outside

### LINKED ISSUE #13310: Tooltip`s stickOnContact param is not working when useHTML is enabled
#### Expected behaviour
Tooltip should be shown while cursor is over tooltip.

#### Actual behaviour
Default tooltip`s behavior.

#### Product version
Highcharts 8.0.4

#### Affected browser(s)
All

### LINKED ISSUE #14143: Tooltip's stickOnContact is not working when useHTML and split are enabled
#### Expected behaviour
Tooltip should not change while mouse pointer is on it.

#### Actual behaviour
Tooltip jumps to next point when mouse is moved (default behaviour).

#### Live demo with steps to reproduce
https://jsfiddle.net/6hmz3k17/

Steps: Move mouse over a tooltip to observe tooltip jumping to next point.

#### Product version
Highcharts JS v8.2.0 (2020-08-20)

#### Affected browser(s)
All I tried with: chromium, firefox.

### LINKED ISSUE #14434: Tooltip `stickOnContact` has confilct with `outside`
#### Expected behaviour

Tooltip should not change while mouse pointer is on it.

#### Actual behaviour

Tooltip is closed

#### Live demo with steps to reproduce
https://jsfiddle.net/fv5qkr4c/

#### Product version
v8.2.2

#### Affected browser(s)
Tested on Chrome 86.0.4240.111

### PR DESCRIPTION
**Pull request by khlieng**
Fixed #14143, #14434, #13310, tooltip with `stickOnContact` and `useHTML` or `outside` enabled did not work properly.

Replaces #14473.
Closes #14434.
Closes #13310.

### CODE REVIEW

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Comment by galangel** [comment]
I'm sorry, but it still an issue:
```
    useHTML: true,
    stickOnContact: true,
    outside: true,
```

are not working together as expected

for example, here: https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/accessible-line

adding `outside: true`, brakes `stickOnContact`

**Comment by doganalper** [comment]
This is still ongoing issue, can't use stickOnContact with outside configuration.

**Comment by doganalper** [comment]
Any chance to fix anytime soon? Should me and my coworkers search alternative way to do what we want to achieve?

**Comment by TorsteinHonsi** [comment]
@doganalper I'll have a look at this ASAP

**Comment by TorsteinHonsi** [comment]
@doganalper , I found a fix, created a PR.

Here's a drop-in workaround that you can use while waiting for the next release:

```js
Highcharts.Pointer.prototype.onContainerMouseLeave = function(e) {

	const { charts, pick, Pointer } = Highcharts;
    const chart = charts[pick(Pointer.hoverChartIndex, -1)];

    e = this.normalize(e);

    // #4886, MS Touch end fires mouseleave but with no related target
    if (
        chart &&
        e.relatedTarget &&
        !this.inClass(e.relatedTarget, 'highcharts-tooltip')
    ) {
        chart.pointer.reset();
        // Also reset the chart position, used in #149 fix
        chart.pointer.chartPosition = void 0;
    }
}
```
[View it live on jsFiddle](https://jsfiddle.net/highcharts/vk9xzdpr/).

**Comment by doganalper** [comment]
@TorsteinHonsi Workaround works perfectly, thank you so much for helping!

**Pull request merged**
