### PR TITLE
enhancement/7318-minLinkHeight-sankey

### LINKED ISSUE #7318: Sankey / minPointLength not working
If I use links with big differences in weight, it happens, that the lower ones are shown with a linkHeight lower than 1px and so they become invisible. Unfortunately the parameter **minPointLength** isn't working, respectively it is not implemented.

As a workaround I've added following code to the source:

`linkHeight = (point.weight != null && linkHeight < 1) ? 1 : linkHeight;	`

With this hack, all valid links will be shown with a minimal linkHeight of 1px.

It would be nice, if I could use the parameter **minPointLength** for that instead of the hack!

### PR DESCRIPTION
**Pull request by sebastianbochan**
Fixed #7318, added new minLinkWidth option to sankey series.

### CODE REVIEW

**Comment by pawelfus** [comment]
There's also another request for `minPointLength` which would set.. min node height (width in inverted), see #9036.

I guess one should be `minPointLength` and the other `minLinkLength`/`minNodeLength`. Since `series.data` creates links, then maybe `minPointLength` should define height/width for links and `minNodeLength` for nodes?

**Comment by oysteinmoseng** [comment]
Ah, I see. Your suggestion makes sense to me. There is a `nodeWidth` option, so maybe `minNodeWidth` for nodes and reuse `minPointLength` for links?

That being said, `minPointLength` is probably not a very intuitive name for the user (the length of the link to me would be the length between the nodes - not the width/height), so it might be better in the long run to actually add `minLinkWidth` and remove `minPointLength` from the API. Thoughts?

**Comment by sebastianbochan** [comment]
Make sense for me, will change that today.

**Comment by sebastianbochan** [comment]
@oysteinmoseng I replaced parameter with the suggested name. 

Let me know if you have any additional questions.

**Comment by oysteinmoseng** [comment]
Mention @TorsteinHonsi in case he has additional comments since we are adding API option (`minLinkWidth`)

**Pull request merged**
