### PR TITLE
docs/9829-data-labels-interface

### PR DESCRIPTION
**Pull request by bre1470**
- Added interfaces for data labels
- Will break existing structure of data labels, but reduces number of declaration lines by 25%

### CODE REVIEW

**Comment by TorsteinHonsi** [comment]
There are conflicts directly related to the doclets - can you fix those?

**Comment by bre1470** [comment]
Yes, I will look into it...

**Comment by bre1470** [comment]
Please review again.

**Comment by TorsteinHonsi** [comment]
Thanks!

**Pull request merged**
