### PR TITLE
ts/networkgraph-series

### PR DESCRIPTION
**Pull request by bre1470**
Migrated networkgraph series to class pattern.

### CODE REVIEW

**Comment by bre1470** [comment]
I will not go further. Types, implementations and inheritence do not fit.

**Comment by bre1470** [comment]
Actually the layout concept makes no sense to me, because there is only one implementation everywhere and the draggable mixin is only used for that layout. So there are many unnecessary splits and naming of basically the same thing over and over again.

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Comment by TorsteinHonsi** [comment]
@pawelfus @Izothep any comments about @bre1470 's layout refactor suggestion?

**Pull request merged**
