### PR TITLE
bugfix/21268-standalone-navigator-height

### LINKED ISSUE #21268: Highcharts Standalone Navigator height property is not working properly
#### Expected behaviour
Standalone navigator height property to change the size of navigator.

#### Actual behaviour
When setting the standalone navigator height for a value higher then 70px, the navigator partially hidden.

#### Live demo with steps to reproduce

https://codepen.io/ducolares/pen/zYQwNdW 

#### Product version

 Highcharts JS v11.4.3 (2024-05-22)
 Standalone navigator module

#### Affected browser(s)
Chrome

### PR DESCRIPTION
**Pull request by bm64**
Fixed #21268, standalone navigator container height did not adjust correctly when a custom height was set.

### CODE REVIEW

**Review by pawellysy — APPROVED** [review]
👍

**Review by kamil-musialowski — APPROVED** [review]

**Review by pawelfus — APPROVED** [review]
Looks good, thanks!

**Review by DJTechnoo — APPROVED** [review]
Great stuff!

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
