### PR TITLE
[Highcharts-3D] Add all 6 faces to the 3D Frame

### PR DESCRIPTION
**Pull request by paulo-raca**
Highchart's support for 3D is really awesome, but it gets really buggy when you try to perform a "full rotation" on the chart.

That is, if beta<-90 or beta>+90, the axis elements are moved to weird places, you start seeing the wrong side of the frame, etc.

### 3D Frame
The "frame" now has all 6 sides, not 3 as previously.

You can configure which faces are visible with `options3d.frame.{bottom/top/left/right/front/back}.visible`:
- `true`/`false`: What you expect
- `'auto'`: Automatically shows only the faces "behind the data" -- This is what I'll use for everything!
- `'default'`: Current behavior 
  - Back is always visible
  - front is never visible
  - left is visible if there is a non-opposite Y axis
  - right is visible if there is a opposite Y axis
  - bottom is visible if there is a non-opposite X or Z axis
  - top is visible if there is a opposite X or Z axis

Also, Instead of using cuboids, the frame is drawn using a custom polyhedron, which hopefully looks a bit better on thick frames :)

Obviously, each Axis lines, plot line and plot band is extended to up-to 4 sides of the cube.

### Axis Labels

Currently, the labels for the X, Y and Z axes are always shown on the same edge, independent of the projection chosen. This looks bad on some angles.

You can now configure `options3d.axisLabelPosition == 'auto'` to automatically move the labels to the best edge:
- The Y axis labels/title/ticks are positioned next to the left-most vertical edge (right-most if opposite=true)
- The X/Z axis labels/titles/ticks are positioned next to the lower-most X/Z horizontal edges (top-most if opposite=true)
- The labels are hidden if they would clutter the chart on the current projection (e.g., the Y axis labels are hidden when seeing the chart from above).

### Demo

http://jsfiddle.net/qryg1jLr/

### CODE REVIEW

**Comment by paulo-raca** [comment]
A demo:
http://jsfiddle.net/gmk00y0o/

**Comment by TorsteinHonsi** [comment]
Looks really impressive Paulo!

> The "frame" has 6 sides, not 3 as previously. Each side is automatically hidden or shown depending on the projection angle.

Any opinions on how that affects performance?

@pawelfus What do you think?

**Comment by paulo-raca** [comment]
> Any opinions on how that affects performance?

Overall, I think the impact will be pretty low.

The code: It has plenty of room for optimizations -- particularly the constant recalculations of `get3dFrame`, `sin` and `cos` -- but once those are addressed the performance impact should be almost none.

The drawing complexity: The number of SVG nodes elements for axis lines (and plotLines and plotBands) isn't changed, but the SVG path might be a bit more complicated if many faces are visible at once (It's not implemented yet, but for alpha=0, beta=0 and perspective enabled, you should be able to see 5 faces of the cube: Left, Right, Up, Down and Back), so it can have some impact depending on the view angle.

Likewise, half of the 6 sides of the 3D frame (currently commented out on my code) will be hidden most of the time, although it will require adding more SVG elements.

**Comment by pawelfus** [comment]
It's a great idea. I think it should be customizable, so user can decide between results. For columns, it makes sense to keep bottom frame in some cases: http://jsfiddle.net/gmk00y0o/5/ . I don't review the code as it's a work in progress, but our linter won't allow some of the changes.

**Comment by paulo-raca** [comment]
@pawelfus, I've updated it to allows manually enabling/disabling each side of the box, and updated your example: http://jsfiddle.net/w6zzqcfc/

IMHO, while it might makes sense to manually disable undesired sides of the box, "forcing" them to be visible is probably a bad idea -- E.g., in your example, the bottom frame looks yuck for alpha < 0.

**Comment by pawelfus** [comment]
Sorry! By "bottom frame" I mean bottom of the bars, so in my demo, it's a left frame. Well, it's an inverted chart so it's also a bottom at the same time.. Does this fix remove an option to set options for frames? For example: http://jsfiddle.net/rf06h999/1/ (color is missing).

**Comment by paulo-raca** [comment]
@pawelfus: Sorry, I've brought back the colour frames now
They look prettier than before, and are now correctly z-ordered in case the orientation puts the frame in front of the actual chart

Also, there are now 3 ways to decide which faces are visible:
- **Standard**, Keeps the current behavior by default: left/bottom/back faces are always visible (Or right/top/back if the axes have `opposite:true`)
- **Auto**, (Enabled by `frameOptions.auto: true`) considers the projection to only enables the faces "behind the data"
- **Manual**, You can toggle each face setting `frameOptions.<face>.enabled`

Updated demo: http://jsfiddle.net/jmr5ctxj/

**Comment by paulo-raca** [comment]
I'm happy with the code now.
Can you please review it?

@pawelfus, how do I run the linter?
I've been using gulp, and AFAICT, it doesn't produce any message.

**Comment by pawelfus** [comment]
We will, thank you!

It's `gulp lint`. `gulp` task builds source files.

**Comment by paulo-raca** [comment]
I've fixed the lint errors

**Comment by paulo-raca** [comment]
Thank you!

**Comment by pawelfus** [comment]
@paulo-raca I tried to play around with these options to make some demos, but it looks "auto" doesn't work: http://jsfiddle.net/garnguaq/3/ 

Do I miss something in config?

**Comment by paulo-raca** [comment]
Hello, @pawelfus.
You were using one of the 'old versions' of the sample. Sorry, but it looks like I pasted too many links on this thread. The "current" one is on the summary now.

The main change is that instead of `auto: true`, I settled on `visible: true / false / 'auto' / null` (null is the backwards-compatible behavior)

Also, there is now `options3d.axisLabelPosition == 'auto'` to move the axis labels

**Comment by pawelfus** [comment]
Right, thank you!

**Pull request merged**
