### PR TITLE
add health check for GET /status that is need for AWS EC2 load banlance

### PR DESCRIPTION
**Pull request by ghostuz**
I found the phantomjs server side export chart is no way to work with AWS EC2 load banlance.
To check the phantaomjs server status EC2 can only send GET request or POST without body request.
So I add add this to make the export server can work with it.

### CODE REVIEW

**Comment by ghostuz** [comment]
test with AWS EC2 load banlancer
not sure which branch I should push to. but push to master must be a bad idea. ;)

**Comment by gvaartjes** [comment]
Hi! Thanks for PR. 

Isn't it more convenient to implement a healthcheck url in Java? You're not running phantomjs directly exposed to internet,  or are you?

**Comment by ghostuz** [comment]
Java is another solution for just export chart image. but I used make the client send 2 request for this work in phantomjs. 
1. send ajax request to command phantomjs to build chart image and saved it into shared folder and returned image url.
2. use the returned url to get the chart image from nginx or other web host.

As we know the phantomjs have some limit. but it is really fast. for a real production env. the load balance really important. you can use as many as you want EC2 t2.micro linux instance for phantomjs behind load balance. and 1 shared folder nignx for the image web host.

**Comment by ghostuz** [comment]
btw. my anohter idea is use AWS S3 for the image host. will better for this work.

**Pull request closed without merging**
