### PR TITLE
docs/16246-error-10-correct-urls

### LINKED ISSUE #16246: Error 10 wrong demo URL
Change the demo URLs in the [error 10](https://assets.highcharts.com/errors/10/)
The URLs are missing the `/master/` folder in the path.

#### Product version
9.2.1

### PR DESCRIPTION
**Pull request by raf18seb**
Fixed #16246, corrected demo URLs for the error 10.

https://assets.highcharts.com/errors/10/

### CODE REVIEW

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Pending checks...

**Comment by raf18seb** [comment]
@TorsteinHonsi, do you know why the checks are not passing?

**Comment by raf18seb** [comment]
Ok, so the problem was that all 4 files should be changed.

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
