### PR TITLE
bugfix/14397-networkgraph-update

### LINKED ISSUE #14397: Updating networkgraph series causes simulation to start from the beginning
#### Expected behaviour
`series.update({ dataLabels })` should keep existing positions instead of starting the simulation from the scratch.

#### Actual behaviour
`series.update({ dataLabels })` starts simulation like when creating a chart.

#### Live demo with steps to reproduce
https://jsfiddle.net/highcharts/18vrf9su/2/

*Internal note:*
Might be connected to the way Series is updated: by removing old one and initialising new one. Perhaps `points` (links) are preserved, but `nodes` are not.

### PR DESCRIPTION
**Pull request by khlieng**
Fixed #14397, `networkgraph` simulation restarted on `series.update()`.

### CODE REVIEW

**Review by pawelfus — APPROVED** [review]
Looks good to me, thanks!
Changes in `Dynamic.ts` up to @TorsteinHonsi - probably it could be a nice idea to let series specific type provide props that should be stored. No strong opinion here, though.

**Comment by pawelfus** [comment]
Just realized - karma + chrome headless do not have `requestAnimationFrame`, so is this test actually testing anything?

**Comment by khlieng** [comment]
The test is just testing if nodes and layout are preserved on update, so that should be fine?

**Comment by pawelfus** [comment]
Good point 👍  Then `enableSimulation` can be disabled (default in karma tests).

**Review by TorsteinHonsi — APPROVED** [review]
Looks good!

**Comment by TorsteinHonsi** [comment]
> probably it could be a nice idea to let series, of a specific type, provide props that should be stored. No strong opinion here, though.

Yes, absolutely. But we can come back to that if we find the list hard to maintain.

**Pull request merged**
