### PR TITLE
feature/searchpoint-perf

### PR DESCRIPTION
**Pull request by pawellysy**
Improved implementation of `attractToPoint` to make use of KD-tree.

### CODE REVIEW

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by bm64 — APPROVED** [review]

**Review by kamil-musialowski — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Nice move!

**Review by DJTechnoo — APPROVED** [review]

**Comment by pawelfus** [comment]
Requesting to merge, @TorsteinHonsi

**Comment by bre1470** [comment]
This breaks the cypress test `annotations/time-cycles/time-cycles`.

**Pull request merged**
