### PR TITLE
support commonjs canvg Fixes #5638

### LINKED ISSUE #5638: Support browserify/webpack/commonjs canvg
#### Expected behaviour

``` js
import highchartsMore from 'highcharts/highcharts-more.src';
import modSolidGuage from 'highcharts/modules/solid-gauge.src';
import modHeatmap from 'highcharts/modules/heatmap.src';
import modExport from 'highcharts/modules/exporting.src';
import modOfflineExport from 'highcharts/modules/offline-exporting.src';
import canvgRenderer from 'highcharts/modules/canvgrenderer-extended.src';
import canvg from 'canvg-origin';
import applyTheme from './applyTheme';

export default function customiseHighcharts(Highcharts) {
  canvgRenderer(Highcharts, canvg);
  highchartsMore(Highcharts);
  modSolidGuage(Highcharts);
  modHeatmap(Highcharts);
  modExport(Highcharts);
  modOfflineExport(Highcharts);
  applyTheme(Highcharts);
}
```

Should allow client-side exporting to work.
#### Actual behaviour

Does not work, canvgrenderer-extended.src is missing from the bundle and assumes Highcharts and canvg are on window.

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard See my comment on https://github.com/highcharts/highcharts/issues/5638#issuecomment-243993294. The canvg-extended file is a lazy-loaded polyfill for Android 2.x, so I'm not sure we want it in our modules directory.

**Comment by graingert** [comment]
Ah that's not clear, is there any documentation for that?

**Comment by TorsteinHonsi** [comment]
Yes, it's in http://www.highcharts.com/documentation/compatibility, all the way at the bottom.

**Comment by graingert** [comment]
Ah I see, yeah, I'd like to be able to bundle this directly with webpack. I
want to use module splitting to control how all my assets load.

I think most of the PR makes sense, I'll update it.

**Comment by graingert** [comment]
@TorsteinHonsi why did you close this?

**Pull request closed without merging**
