### PR TITLE
MACD chart naming is wrong if parameters are changed

### PR DESCRIPTION
**Pull request by HNygard**

### CODE REVIEW

**Comment by pawelfus** [comment]
Hi @HNygard 

Thank you for sharing. You can change MACD name like any other series: https://api.highcharts.com/highstock/series.macd.name . Default name for MACD (and every other technical indicator) includes default params in a series name.

**Comment by HNygard** [comment]
@pawelfus : Well. That is a quite stupid default and I suggest changing it. 

Nice if you use the default params, but not nice at all when you change them. Quite fast you are looking at a graph with other params than the name suggest.

**Comment by pawelfus** [comment]
It's a common way to provide details of a technical indicator which params are used in the algorithm. If you change for example [`params.longPeriod`](https://api.highcharts.com/highstock/plotOptions.macd.params.longPeriod) then series name should be changed too. If you don't want to set name on every change, then you can simply set series name to always be `MACD`:

```
series: [{
  data: [ .. ],
  id: 'main',
}, {
  linkedTo: 'main',
  name: 'MACD',
  params: { ... }
}]
```

**Comment by HNygard** [comment]
@pawelfus : 

The default should be 'MACD' or a dynamic version based on parameters. I agree that showing the parameters like 'MACD (26, 10, 9)' is the best solution, but it is way to easy to get this wrong and spend useless time debugging. This is not developer friendly.

**Comment by pawelfus** [comment]
I agree, the best solution would be use dynamic name, based on parameters.

**Comment by TorsteinHonsi** [comment]
@pawelfus Maybe we should resolve this by making the name `null` as default, which means Highstock dynamically generates the name? Like we currently do with the base series, which are given names like `Series 1`, `Series 2` etc by default.

**Comment by pawelfus** [comment]
Yes, it crossed my mind: if it's confusing, then maybe we shouldn't try to set names at all. I am worried that users will report this change as a bug (unexpeced change on a chart "SMA (14)" -> "Series N") anyway and we will be forced to revert this. 

> Also, does this apply to any other indicators as well?

Yes, every technical indicator has default name including default parameters. Just in case, it's in our docs: 
https://api.highcharts.com/highstock/plotOptions.macd.name

**Comment by TorsteinHonsi** [comment]
Yes, I didn't mean we should fall back to `Series 1`, `Series 2` etc. We should set the default name to `null` which means the indicator series will build its default name based on the actual parameters. I agree with @HNygard it is counter intuitive with the wrong parameters listed in the name.

The name for normal series is dynamically set in Chart.orderSeries:

https://github.com/highcharts/highcharts/blob/v6.0.4/js/parts/Chart.js#L299-L300

I suggest we move this line to a new function, `Series.getName`, and override that in the indicators.

**Comment by pawelfus** [comment]
Created separate topic for it: #7642

**Pull request closed without merging**
