### PR TITLE
20584 errors in visual test screendumps for mobiles

### PR DESCRIPTION
**Pull request by jomar-honsi**
Wait times after viewport changes significantly increased based on observed time usage per test case.

### CODE REVIEW

**Comment by jomar-honsi** [comment]
> Increasing the wait time 10x seems a lot but it is what it is...

Not a good solution but we may have to live with it. I am browsing the Cypress documentation to investigate if there is a more elegant solution. Cypress [boasts of automatic waiting](https://docs.cypress.io/guides/overview/why-cypress) so perhaps there is a solution. @goransle any idea?

**Review by Vazonik — APPROVED** [review]
Does it have to be 5 seconds? When we add more demos to array, this will be quite problematic.

Anyway, I approve, I tried to do it in a better way myself, but to no avail.

**Comment by jomar-honsi** [comment]
> Does it have to be 5 seconds? When we add more demos to array, this will be quite problematic.
> 
> Anyway, I approve, I tried to do it in a better way myself, but to no avail.

It is a very unsatisfactory solution as the execution times could vary wildly depending on the machine and load at the time of text execution. There is nothing in the documentation either and searches on the internet were fruitless. Note that cy.get() has a default timeout of 4 seconds. Also I don't understand why changing viewport should take that long (when we do the same in the UI the reaction is instant). Still, I think we will have to live with this for now.

**Review by goransle — APPROVED** [review]
This should do the trick, but with the discussed drawbacks.

A more complicated solution would be to add a custom command similar to the [`boardRendered` command](https://github.com/highcharts/highcharts/blob/master/test/cypress/support/index.js#L30-L65), that waits for all components to have "settled". Possibly something could be done using a ResizeObserver?

**Pull request merged**
