### PR TITLE
Samples: Patched details files Gantt

### PR DESCRIPTION
**Pull request by goransle**
Patched `demo.details` files for Gantt demos and samples

### CODE REVIEW

**Comment by oysteinmoseng** [comment]
Agree. It should currently be easy to parse this from the HTML source, unless I am missing something. I think this would be a better option than forcing duplication, since alternative 2 would require us to parse the HTML anyway.

**Comment by goransle** [comment]
Should have been clearer in the original message. The new additions are all parsed via the demo-manager, so keeping the details file as it is should not be problem in that regard.

**Comment by jon-a-nygaard** [comment]
I am wondering what is the purpose or benefit of having the name of these files in the demo.details? Is it to be able to filter on the modules used in the demo?

Another possible option could be to remove the scripts from `demo.html` and add them as `resources` to JSFiddle and Codepen, and have the demo manager add all resources as link/script tags in the output.

**Comment by TorsteinHonsi** [comment]
> The new additions are all parsed via the demo-manager, so keeping the details file as it is should not be problem in that regard.

My concern is about keeping it consistent in the future. We constantly add and update samples.

> Another possible option could be to remove the scripts from demo.html and add them as resources to JSFiddle and Codepen, and have the demo manager add all resources as link/script tags in the output.
> downside is that the script tags are not visible in the html

Yes, we tried this in the beginning. The main downside is that is very cumbersome to add/modify/remove scripts when testing in jsFiddle.

**Comment by jon-a-nygaard** [comment]
> Having it in demo.html is more visible and much more handy

I agree, so if it is not very beneficial that the modules are mentioned in the `demo.details`, then I believe alternative 1 is a good choice.

**Comment by goransle** [comment]
Changed to only patch names, tags and categories. Currently names are set using the `demo/index.htm` file in all cases, but perhaps it should prefer the name in `demo.details` (if it is not 'Highcharts Demo' etc)?

**Pull request merged**
