### PR TITLE
Fixed TreemapSeries not working with Boost

### LINKED ISSUE #21863: Boost does not work with Treemap since 11.3.0
#### Expected behaviour
Boost should work with Treemap as in 11.2.0 and other previous versions: https://jsfiddle.net/vn3m6L7f/

#### Actual behaviour
In our docs (https://www.highcharts.com/docs/advanced-chart-features/boost-module), at the bottom of the page there is a link to a sample with Treemap: https://www.highcharts.com/samples/highcharts/boost/treemap which does not work since 11.3.0.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/078gv2zj/

#### Product version
Since Highcharts 11.3.0

***Internal note***: Bisected to https://github.com/highcharts/highcharts/commit/a67ba29717127638d1e1c742b16bcb6f50e25986 FYI @bre1470

### PR DESCRIPTION
**Pull request by Eskils**
Fixed #21863, a regression causing the Boost module to fail with treemap series

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208339061077327

### CODE REVIEW

**Comment by Eskils** [comment]
While already here, I noticed that the console shows a warning that it expects point configuration to be numbers or arrays in turbo mode. (12) Does this make sense to show for TreemapSeries, or can it be silenced?

Screenshot 2024-10-17 at 21 35 27

Example fix:

```ts
if (
    !isNumber(firstPoint) && 
    !isArray(firstPoint) &&
    !series.is('treemap')
) {
    error(12, false, series.chart);
}
```

**Comment by bre1470** [comment]
Nice catch! Yes, that should be adjusted.

**Review by bre1470 — APPROVED** [review]
Looks good! 👍

**Review by MarkusBarstad — APPROVED** [review]
Looks good! 🚀

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
