### PR TITLE
bugfix/19861-search-point-undefined

### LINKED ISSUE #19861: `series.searchPoint` returning undefined + Discussion on editing existing line annotation so that end-points attach to nearest series point
#### Expected behaviour

`Series.searchPoint` should always work.

#### Actual behaviour

`Series.searchPoint` is randomly returning `undefined` sometimes.

#### Live demo with steps to reproduce

**Live - https://jsfiddle.net/5x7g6vwf/4/**

My use-case is to add line annotation such that the end points of line attach to the nearest series point. I am using custom bindings to solve this. It is working correctly when annotation is first added, but in second step, when user clicks again to finalize the second end-point, I want the second point also to attach to the nearest series point - which does not seem to happen because `series.searchPoint` is returning `undefined` for all series.

searchpoint-bug

#### Product version
Latest Highcharts

#### Affected browser(s)
Chrome

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #19861, `kdTree` was deleted on annotation redraw.

Demo for testing: https://jsfiddle.net/BlackLabel/jetn459p/

_Internal note:_
The problem was in the annotation update (from the OP demo), not in the search point itself. KD Tree was deleted every time annotation was updated (which called `chart.redraw()`). https://github.com/highcharts/highcharts/blob/acaa13a09f1bd7e463b30af984a07ce396bdc1d6/ts/Core/Series/Series.ts#L3451-L3460

Connected to #17582.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205657626316268

### CODE REVIEW

**Review by bm64 — APPROVED** [review]

**Review by pawelfus — CHANGES_REQUESTED** [review]
Nice catch! Missing test though 🤔 

___
I'm fine with this solution, however I was curious why `redraw()` destroys the kdTree? It seems like something we could improve in Core. 

Just made a simple demo: https://jsfiddle.net/BlackLabel/Lozm98kd/ - two charts, just bit different datasets (one point less in the second chart), and we get different behaviour of `chart.redraw()`. 

Debugged a little:
- charts look similar, however xAxis labels have different tickInterval. With interval=1, logic to animate labels (move them like categorized) jumps in
- this sorting? animating? implementation sets [axis.isDirty](https://github.com/highcharts/highcharts/blob/dd6879c0826b89d96617e0c117e6f45b6a96f8e5/ts/Core/Axis/Tick.ts#L1093-L1120) flag to true
- dirty axis = dirty series => let's destroy the kdTree 🤷 

I'm not sure if this is something that we should improve right now. tickInterval=1 is unlikely to happen in Stock charts, and with the workaround/fix by Kamil, we can completely ignore the issue.

FYI @TorsteinHonsi

**Comment by kamil-musialowski** [comment]
@pawelfus Thank you! I've added a test, however it was not possible to simply call `annotation.update()`, I had to go with `annotation.update( { shapes: [{}] } )`. Are we cool with it, or it should be reported as a bug?

**Comment by pawelfus** [comment]
Yes, we are cool with that

**Review by DJTechnoo — APPROVED** [review]

**Review by bm64 — APPROVED** [review]

**Comment by pawelfus** [comment]
The remaining thing is a green light from Torstein: are we okay with breaking a non-written rule that `redraw=boolean` parameter means `chart.redraw()`? 

As of now, it is [an undescribed param](https://api.highcharts.com/class-reference/Highcharts.Chart#addAnnotation).

**Comment by TorsteinHonsi** [comment]
@pawelfus 

> The remaining thing is a green light from Torstein: are we okay with breaking a non-written rule that redraw=boolean parameter means chart.redraw()?

Yes, I think that's fine. Since we don't have to redraw the whole chart in order to render this annotation. The question is - if we call `addAnnotation` with redraw = false, then run `chart.redraw()` - will that work as expected?

**Comment by pawelfus** [comment]
> Yes, I think that's fine. Since we don't have to redraw the whole chart in order to render this annotation. The question is - if we call `addAnnotation` with redraw = false, then run `chart.redraw()` - will that work as expected?

Yes, it will work fine. The redraw of all annotations is attached to `chart.redraw` event, so changes made by `addAnnotation()` will be picked up.

I just realized I mentioned the wrong method. I wanted to discuss [`annotation.update()`](https://api.highcharts.com/class-reference/Highcharts.Annotation#update), not `addAnnotation()` 🤦. Anyway, the answer remains the same: the `chart.redraw()` method will apply changes made in `annotation.update(options, redraw=false)`.

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
