### PR TITLE
bugfix/13831-restart-simulation-after-click

### LINKED ISSUE #13831: Ball does not return to the problem
When the ball is rendered, click the ball, the ball does not move, does not return to its parent

https://jshare.com.cn/temp/rFG0q8
圆堆积图

### PR DESCRIPTION
**Pull request by madepiet**
Fixed #13831, network graph simulation didn't restart after clicking a node.

~~Fixed #13831, restart simulation after a click.~~

### CODE REVIEW

**Comment by madepiet** [comment]
> I think we don't need to wrap `onMouseUp` method in networkgraph module. We should fix this directly in the draggable-nodes module, so all series that use that mixin will get fixed, right?
> 
> See solution idea posted by @Izothep : [#13831 (comment)](https://github.com/highcharts/highcharts/issues/13831#issuecomment-654838113)

Sure, thanks! Here I just tested these solutions.
I'm not sure how to write tests for this, any hint?

**Comment by pawelfus** [comment]
Ah, sorry!

For a test, use TestController: https://github.com/highcharts/highcharts/tree/master/samples#useful-tips-for-setting-up-tests

**Comment by madepiet** [comment]
Unable to write test - headless chrome has no rAF()

**Comment by TorsteinHonsi** [comment]
Pending @pawelfus' approval

**Comment by TorsteinHonsi** [comment]
Should this be marked "Ready for review"? Also, pending @pawelfus' approval.

**Review by pawelfus — APPROVED** [review]
Good, thanks! 👍

**Comment by madepiet** [comment]
@TorsteinHonsi Yes, it is ready 👍

**Pull request merged**
