### PR TITLE
bugfix/8365 macd periods

### PR DESCRIPTION
**Pull request by sebastianbochan**

### CODE REVIEW

**Comment by TorsteinHonsi** [comment]
It looks like this PR is polluted with changes from another branch. The columnpyramid series shouldn't be added to this bugfix?

**Comment by sebastianbochan** [comment]
Oh, sorry @TorsteinHonsi, it looks like something went wrong with columnpyramid. Its strange becase has separate own branch and MACD fix also separate branch.

Well, what we can do at this moment with this? Revert columnpyramid commit or prepare a new PR ?

**Comment by TorsteinHonsi** [comment]
No worries! It's probably best just to scrap this branch and create a new PR.

**Comment by sebastianbochan** [comment]
Ok, will do that.

**Comment by sebastianbochan** [comment]
Correct PR -> https://github.com/highcharts/highcharts/pull/8488

**Pull request closed without merging**
