### PR TITLE
 Jervis Bay is not a state or territory.

### PR DESCRIPTION
**Pull request by nickspiel**
Adjusted data to match other minor cities.
Changed the ID of NT to 8 instead of 9 (Jervis bay was 8).

### CODE REVIEW

**Comment by tomascassidy** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/Jervis_Bay_Territory) and the [Australian Government](http://regional.gov.au/territories/jervis_bay/), "The Jervis Bay Territory is a non-self governing territory of the Commonwealth of Australia, occupying the Bherwerre Peninsula, and forming the southern boundary of Jervis Bay."

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng @nickspiel Note that merging this PR is not enough to fix the issue. Our geojson files are generated from Natural Earth shapefiles so we need to make the change in the source data or in a middle layer.

**Comment by tomascassidy** [comment]
I would think that qualifies it to be listed as Territory? Therefore no changes need to be made?

**Comment by nickspiel** [comment]
@tomascassidy I live in Australia, Jervis bay is definitely not a territory and will only confuse people. @TorsteinHonsi I am not sure how to go about updating the geojson data, sounds like it could get pretty involved.

I posted this PR over a year and a half ago, the project I required the fix on has moved on from the highcharts map implementation and I simply don't have the time to look into this any further. I am happy to raise this as an issue as opposed to a PR.

**Comment by TorsteinHonsi** [comment]
@nickspiel We should fix it on our end. Our map guy, @oysteinmoseng, is on vacation, but will look at it when he's back.

**Comment by oysteinmoseng** [comment]
This will need to be fixed in our source data. I will have a look at it.

**Pull request closed without merging**
