### PR TITLE
Fixed #14182, points disappeared after zooming on variwide series

### LINKED ISSUE #3136: cropThreshold doesn't work
Example: http://jsfiddle.net/n6EhL/3/

Try to zoom-in by dragging one of navigator's handles. First column is missing even when we set `cropThreshold`.

Maybe be connected to #2437.

Workaround is to set `cropShoulder` directly in series prototype.

### LINKED ISSUE #14182: Variwide within range - zoom not working properly
#### Expected behaviour
After zooming between 21.25 and 22.00  should render properly.
https://jsfiddle.net/raghava_2121/rq3mfc4L/9/

7138A6F8-569E-4B19-8AC1-DEF6C8903E6F_1_105_c

#### Actual behaviour
After zoomin graph doesn't display the selected range with colour.
 
#### Live demo with steps to reproduce
https://jsfiddle.net/raghava_2121/rq3mfc4L/13/

#### Product version
Highstock 

#### Affected browser(s)
google chrome

### PR DESCRIPTION
**Pull request by TorsteinHonsi**
Fixed #14182, points disappeared after zooming on variwide series

___
Removed the existing `cropThreshold` series property, since it seems that there is no case when we want it to be 0 rather than 1. Issues #14182 and #3136 shows that column-like series also should have one graphic generated outside the zoomed area.

Closes #3136.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205293302215875

### CODE REVIEW

**Comment by TorsteinHonsi** [comment]
Most of the visual diff is caused by karma now picking the shoulder point for tooltip comparison. Will probably be fixed by #19600.

**Comment by TorsteinHonsi** [comment]
@pawelfus As of now there are 15 diffing visual tests. As far as I can see, all of those come from the fact that the data grouping algorithm uses only data that is within the visible range. Except now it also includes one point outside. If I apply `groupAll` to those samples, it is not different from before. So it is no more incorrect now than it used to be, so to speak. 

Any thoughts?

**Comment by pawelfus** [comment]
There is not much to add, I don't know any specific case where shoulder=1 would cause more trouble than shoulder=0 for column series. If we get such a bug report, we can revert it and set it only for variwide series.

**Review by pawelfus — APPROVED** [review]

**Comment by pawelfus** [comment]
Worth checking if those are also fixed with the commit above: #13985

Note: Just realized there was a case when someone didn't want extra points outside the visible chart: #14248

**Pull request merged**
