### PR TITLE
bugfix/12133-stacklabels-misalignment

### LINKED ISSUE #12133: stackLabel misaligned when having a scrollable plot area in bar chart
#### Expected behaviour
Labels should be aligned to each column

#### Actual behaviour
Labels are misaligned.

#### Live demo with steps to reproduce
https://jsfiddle.net/xhsrm9db/

#### Product version
7.1.2
7.2.0

#### Affected browser(s)
Google Chrome  77.0.3865.90 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Fixed #12133, stack labels alignment was wrong when `scrollablePlotArea` was enabled.

DEMO: https://jsfiddle.net/BlackLabel/a7gzLpdc/

### CODE REVIEW

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! Please add a unit test too.

**Comment by kamil-musialowski** [comment]
Current fix breaks down the `bar` charts. Need to:

- [ ] Rewrite the current solution, so that it won't break down the bar charts
- [ ] Create unit tests for both column and bar charts

**Comment by TorsteinHonsi** [comment]
I see this deals with negative stack labels. Is there any conflict of interest with https://github.com/highcharts/highcharts/pull/17289?

**Comment by kamil-musialowski** [comment]
> I see this deals with negative stack labels. Is there any conflict of interest with #17289?

The commited fix only deals with `inverted: true`, so there shouldn't be any conflict with negative axes.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks!

The code change is fine, but please write a proper changelog description: https://github.com/highcharts/highcharts/tree/master/changelog#writing-content-for-the-changelog

**Review by TorsteinHonsi — APPROVED** [review]

**Comment by TorsteinHonsi** [comment]
Sorry I had to revert this, I didn't notice the failing test in Safari.

**Comment by kamil-musialowski** [comment]
Sure thing. Since @pawellysy is going to work on rewriting that module, maybe we can pause this one for now, and wait until the new PR?

**Comment by pawellysy** [comment]
@kamil-musialowski probably my refactor of `StackItem.setOffset` method will fix this issue as well :)

**Pull request merged**
