### PR TITLE
bugfix/17331-type-type

### LINKED ISSUE #17331: TS: definition for OptionsTypeValue is wrong
#### Behaviour
`OptionsTypeValue` is a merge of `chart.panning.type` and `series.map.data.geometry.type`. Those should not be of the same type. The property name collision (and following unwanted merge) is logged upon running `npx gulp jsdoc-dts`.

#### Live demo with steps to reproduce
Run `npx gulp jsdoc-dts` in the repo.
`OptionsTypeValue` (could be checked [here](https://raw.githubusercontent.com/highcharts/highcharts-dist/05dcbf8e2dbc924c37eb6e8c719fed3e9f953bbd/highcharts.src.d.ts)) shows as:
`export type OptionsTypeValue = ("x"|"xy"|"y"|"LineString"|"MultiLineString"|"MultiPolygon"|"Polygon");`

#### Product version
Highcharts 10.1.0 (probably since v9.3.0)

### PR DESCRIPTION
**Pull request by KacperMadej**
Fixed #17331, resolved TS type collision.

### CODE REVIEW

**Comment by KacperMadej** [comment]
Not sure if this should go into the changelog - I am not adding the label that would make it do so.

**Comment by KacperMadej** [comment]
I have tried changing the added definition location based on other similar definitions but I am still getting this error message. I do not see how the error is related to the introduced change. Any ideas @bre1470 ?

**Comment by KacperMadej** [comment]
If https://github.com/highcharts/highcharts/pull/17354 works this PR can be closed. However, it would be nice to know why it failed.

**Comment by bre1470** [comment]
@KacperMadej `@typedef` is a tag for class reference and `@apioption` is a tag for API reference. Not every file is processed for class reference, so this file might be ignored by the gulp task. I commented in the other PR about the solution to solve conflicts with aliases in a simple way. In general your approach is correct, but this can be automated with a custom tag.

**Comment by raf18seb** [comment]
@TorsteinHonsi Kacper is on vacation for 3 weeks until 11 of July. Can this PR wait that long?

**Comment by TorsteinHonsi** [comment]
@raf18seb Sure, no problem!

**Comment by TorsteinHonsi** [comment]
Pending reply from @KacperMadej

**Comment by KacperMadej** [comment]
Let's continue with the other PR.

**Pull request closed without merging**
