### PR TITLE
bugfix/hollowcandlestick-line-color

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed how the color is applied for bullish hollow candlestick line.

### CODE REVIEW

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by raf18seb — CHANGES_REQUESTED** [review]
Seems ok, thanks!
Shouldn't we add some tests for the point's colors? Or the visuals are enough?

**Comment by karolkolodziej** [comment]
At the beginning of creating the new series, we agreed that the visual test is enough and I think we shouldn't add more tests.

**Comment by TorsteinHonsi** [comment]
I agree that the visuals are enough for the general color handling. Merging now. Thanks for the fix!

**Pull request merged**
