### PR TITLE
demo/stock-technical-analysis

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Added a technical analysis demo with annotations.

_Asana:_ https://app.asana.com/0/1203542399740129/1204260211115403/f

### CODE REVIEW

**Comment by kamil-musialowski** [comment]
@TorsteinHonsi Since we have to use a static dataset for this one, do you have any recommendations for that instead of clogging the HTML with 1000 lines? (moved to HTML to make the JS more readable) Or should I leave it as it is?

**Review by pawelfus — CHANGES_REQUESTED** [review]
Nice! A couple of minor things:

- Could you add also `id` to series? It seems without it we can't add indicators from GUI
- Could you add names or `langKey` to added annotations? Otherwise, the name is missing in the popup
- ~It's not possible to scroll in the Indicators Popup~ Edit, reported:    https://github.com/highcharts/highcharts/issues/19736

**Comment by kamil-musialowski** [comment]
Merged master to fix visuals & Chrome.

**Comment by kamil-musialowski** [comment]
@TorsteinHonsi Could you please suggest what could we do in such situation, where a static dataset is needed? 
The approach with HTML does not pass the Visuals check, so should I simply move it to JS, or maybe there is anything better that could be done here? Thanks :)

**Comment by TorsteinHonsi** [comment]
I think you should put it in `/samples/data`. See [the description](https://github.com/highcharts/highcharts/tree/master/samples#:~:text=Using%20data%20from%20/samples/data).

**Review by pawelfus — APPROVED** [review]
Thanks!

@goransle - any thoughts about the height of the container? Will the thumbnail look good?

**Comment by goransle** [comment]
Thumbnail looks good to me:

thumbnail

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
