### PR TITLE
ts/new-line-series

### PR DESCRIPTION
**Pull request by bre1470**
Created a new line series and replaced references of core series (previous line series).

### CODE REVIEW

**Review by Onixmiha — APPROVED** [review]

**Review by Onixmiha — APPROVED** [review]

**Comment by TorsteinHonsi** [comment]
> Created a new empty line series with the temporary key `_line`.

How temporary is that? Looks like a hack that doesn't belong in the master, but if it is just a required quick step on the way to the permanent solution then we can merge it.

**Comment by bre1470** [comment]
When all line-specific code is moved to the new `LineSeries`, we can replace the `line` registry and remove `_line` again. Though I have no idea how much work it is. In many places like axis, label, legend, pointer, stock are references, that only directly work with `Series` class and rely on the inheritance of the old `line` series by all other series (so in future the reduced core series). All these code lines have make use of `SeriesRegistry.series` instead of `SeriesRegistry.seriesTypes.line` before we can even think about moving line-specific code to the new `LineSeries` and removing `_line`.

**Comment by bre1470** [comment]
@TorsteinHonsi Please review ones more.

**Review by TorsteinHonsi — APPROVED** [review]
Thanks, looks good!

Now there are other functions that can probably be moved over too, like `getSymbol`, `getGraphPath`, 'getZonesGraphs`, though it is not very important.

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
