### PR TITLE
bugfix/18768-missing-legend-page

### LINKED ISSUE #18768: Legend is missing the last page when legend.maxHeight is smaller than 43
#### Expected behaviour

Legend has the 3rd page containing series 9 for small legend.maxHeight. (in the attached JSFiddle case)

#### Actual behaviour

Legend does not have the 3rd page when legend.maxHeight is less than 43.

#### Live demo with steps to reproduce
https://jsfiddle.net/386czx9f/1/

#### Product version

Highcharts v10.3.3 (to at least v8.1.1)

#### Affected browser(s)
Chrome, Safari, Firefox, Edge

### PR DESCRIPTION
**Pull request by Vazonik**
Fixed #18768, missing the last item in a legend when it was alone on a page.

### CODE REVIEW

**Review by TorsteinHonsi — APPROVED** [review]

**Comment by TorsteinHonsi** [comment]
@Vazonik Since merging this, `npm test` fails on the master. Can you check it out?

**Comment by Vazonik** [comment]
I ran tests on Windows (node v18.12.1) and two Macs, with reinstalled modules and in all cases they pass. Does the problem still occur? @TorsteinHonsi

**Comment by TorsteinHonsi** [comment]
You're probably running your tests in ChromeHeadless. The test issue can be reproduced by opening http://localhost:3030/samples/#test/unit-tests/legend/navigation in Firefox on the Mac. With a disclaimer that it may depend on how the system handles fonts.

**Comment by Vazonik** [comment]
@TorsteinHonsi That's right, thanks! Fixed it here: #18820.

**Pull request merged**
