### PR TITLE
Migration: AccessibilityComponent

### PR DESCRIPTION
**Pull request by bre1470**
Migrated AccessibilityComponent to class pattern.

### CODE REVIEW

**Comment by bre1470** [comment]
@oysteinmoseng I wonder in this case, if the dummy functions should actually become abstract class members with the class itself also abstract.

**Comment by oysteinmoseng** [comment]
@bre1470 Good thinking, but they are not quite dummy functions, but more like default functions that can be overridden. So better keep it as is I think.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! Please resolve conflicts.

**Review by TorsteinHonsi — APPROVED** [review]
Thanks! Pending approval by @oysteinmoseng

**Review by oysteinmoseng — APPROVED** [review]
Looks great!

**Pull request merged**
