### PR TITLE
demo/neon-stockchart

### PR DESCRIPTION
**Pull request by DJTechnoo**
Added line chart demo with neon glow.

### CODE REVIEW

**Review by kamil-musialowski — CHANGES_REQUESTED** [review]
I like how you used the subtitle as a price label 👍 

Two comments from me:
- If we export the chart, then the AAPL and price change their place
- The tooltip content is quite small compared to the rest of the demo, maybe the font size should be increased?

**Review by bm64 — APPROVED** [review]
LGTM!

**Review by kamil-musialowski — APPROVED** [review]
All good now!

**Review by pawelfus — CHANGES_REQUESTED** [review]
Amazing work!

One thing though: RangeSelector buttons have lost their `cursor: pointer` (or in general, hover state), could you add it?

**Review by pawelfus — APPROVED** [review]
Nice!

**Review by TorsteinHonsi — APPROVED** [review]
Very nice! Despite my best efforts, I couldn't find anything to nitpick on 👍

**Review by marvin19 — APPROVED** [review]
Really cool demo! 👏🏻

**Comment by DJTechnoo** [comment]
@TorsteinHonsi  we are go for merge!

**Pull request merged**
