### PR TITLE
demo/non-geo-map-fix

### PR DESCRIPTION
**Pull request by KacperMadej**
Moved data into the JS to fix visual compare.

Sadly, [the demo](https://github.com/highcharts/highcharts/pull/20639) is causing visual tests failure like [here](https://github.com/highcharts/highcharts/actions/runs/8049777012/job/21984072825?pr=20447).

### CODE REVIEW

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
That's strange. Do you know why it leaks to other samples?

Also, we now have a demo that starts with 300+ lines of path data, which will not look good on the demo pages and in jsFiddle. We have some options:

* Define an `options` constant first, holding the chart configuration, which is usually the most important part of any demo.
* Or, create a JSON file for the seat plan.
* Or, define the seat plan in a hidden `<pre>` tag in `demo.html` and read it using `pre.innerText`.

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
It now fails in the CI visual test. I wonder why, it's not the first time we're using this pattern...

**Comment by hubertkozik** [comment]
Wouldn't the issue in Visual tests resolved after merging changes from this PR? The visual test breaks because of the not defined `seatPlan` variable, which should work now?

**Comment by TorsteinHonsi** [comment]
@hubertkozik I think you're right. It fails because it is not set in the master. Let's merge.

**Review by TorsteinHonsi — APPROVED** [review]

**Comment by hubertkozik** [comment]
Tested here: https://github.com/highcharts/highcharts/pull/20447 merge master resolved visual tests issue.

**Pull request merged**
