### PR TITLE
db/sidebar-hide

### PR DESCRIPTION
**Pull request by karolkolodziej**
The sidebar was not hidden on the init.

### CODE REVIEW

**Review by bre1470 — APPROVED** [review]
Looks good! 👍

**Review by sebastianbochan — APPROVED** [review]

**Comment by sebastianbochan** [comment]
It's fine for me too 👍

**Review by pawellysy — APPROVED** [review]
One question to think about, otherwise looks good.

**Comment by karolkolodziej** [comment]
@sebastianbochan the issue you are referring to `Add component option breaks detecting context, after drag` is still visible.

It needs to be investigated in a separate PR.

**Pull request merged**
