### PR TITLE
bugfix/18251-range-selector-multiple-series

### LINKED ISSUE #18251: Gantt Chart Range selector not consistent
Hi Team,
I'm trying to check Gantt chart meet our requirements. Range selector didn't allow me to select valid date from date picker. it is going to first row date range.

2023-01-05_15h11_01

When i select Jan 22nd. it is going to Jan 19 (first row date range). Please check on live demo
Live Demo : [Project Management - JSFiddle - Code Playground](https://jsfiddle.net/shihabkaniyarath/y0r496ct/2/)

#2 When I try to export with collapsed, collapsed items are not showing the result. And navigator showing the result

### PR DESCRIPTION
**Pull request by jakubjanuchta**
Fixed #18251, range selector should consider all series extremes.

### CODE REVIEW

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Review by TorsteinHonsi — COMMENTED** [review]
I can't break this, but still I am wondering about the fix. First, the comment "Validate the extremes. If it goes beyound the data min or max, use the actual data extreme (#2438)." doesn't seem to match the new logic. Yet, it still apparently works for the #2438 case.

Next, I am wondering why `dataAxis.dataMin` and `dataMax` do not work with multiple series. They should, because the `Axis.getSeriesExtremes` function should consider all the axis' series. So maybe that's where the real bug is?

**Comment by pawelfus** [comment]
I can explain the problem a  little deeper:
In the demo, we have the main x-axis with two series and a navigator x-axis with just one series. `dataMax` in the navigator reflects data extremes taken from the shorter series (which is correct). `max` is taken from all series in the chart (from all x-axes) using `modifyNavigatorAxisExtremes` method (which is well... correct too). 

There is another solution, instead of getting `scroller.max`: use `getUnioneExtremes()` (like all other methods in RS do). Aaaan when writing a comment, I realized how to break it: `max` < `dataMax`:  [current fiddle](https://jsfiddle.net/BlackLabel/zL843r7x/) vs [PR fiddle](https://jsfiddle.net/BlackLabel/zL843r7x/4/). Select in max-input 30-09-2006 date, nothing happens in PR fiddle.

**Comment by jakubjanuchta** [comment]
Thanks for following up @TorsteinHonsi and @pawelfus.

Regarding to what @pawelfus pointed out about breaking the fix when `max` < `dataMax`, should I first apply the logic to check which of them is bigger in Range Selector, or do you guys think there is a better solution for that?

**Comment by TorsteinHonsi** [comment]
> should I first apply the logic to check which of them is bigger in Range Selector, or do you think that there is a better solution for that?

@pawelfus What do you advice?

**Comment by jakubjanuchta** [comment]
> I would start with using `getUnionExtremes` - it already has this logic implemented (max for `dataMax` and `max`)

Okey, thanks for the tip @pawelfus , I'll do that!

**Review by TorsteinHonsi — APPROVED** [review]
Thanks! Pending final approval by Pawel.

**Review by pawelfus — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
