### PR TITLE
bugfix/17957-dataLabels-hover

### LINKED ISSUE #17957: Data label disappears on hover
#### Expected behaviour
Data label persist on hover

#### Actual behaviour
Data label disappears on hover

#### Live demo with steps to reproduce
https://jsfiddle.net/qhwz90nL/

Removing off the `marker.enabled: false` bit, the issue is resolved.
https://jsfiddle.net/qhwz90nL/1/

#### Product version
Presumably originating in the Accessibility module.
Introduced in 10.3.0 and seen in later versions

#### Affected browser(s)
FF, Chrome

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #17957, data labels disappeared on point hover.

### CODE REVIEW

**Comment by TorsteinHonsi** [comment]
@karolkolodziej Is it still in progress or did you mean to set Ready for review?

**Comment by karolkolodziej** [comment]
@TorsteinHonsi  yes you can take a look at the code however the visual differences are disturbing- I will take a look at that.

**Comment by TorsteinHonsi** [comment]
> the visual differences are disturbing

They are expected, it was the other way around when I did these changes.

**Review by TorsteinHonsi — COMMENTED** [review]
Thanks!

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
