### PR TITLE
dash/layout-esm

### PR DESCRIPTION
**Pull request by karolkolodziej**
Added documentation on how to use the Layout module with ESM.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206708615911742

### CODE REVIEW

**Review by sebastianbochan — APPROVED** [review]

**Review by bre1470 — CHANGES_REQUESTED** [review]
The example lacks the necessary file ending `.js`, that is required for ESM imports.

Besides I failed to create a working test project with the example. The type of the `Dashboards.board` factory does not exist.

**Comment by karolkolodziej** [comment]
I've created a fresh Angular 17 project with 
`"@highcharts/dashboards": "github:highcharts/dashboards-dist#v2.0.0-rc1"` 

and everything seems to be working fine:
image

Can you please tell me how to recreate this issue?

**Comment by bre1470** [comment]
Here is my test setup: https://github.com/bre1470/dashboards-v2-test/

**Comment by bre1470** [comment]
I played around a bit, and it looks like there is something off with the declaration's default export as the following is working:
```
import Dashboards from '@highcharts/dashboards/es-modules/masters/dashboards.src.js';
import '@highcharts/dashboards/es-modules/masters/modules/layout.src.js';

Dashboards.default.board('container', {
```
So there seems to be a double default export somewhere.

**Review by bre1470 — APPROVED** [review]
Okay, looks good. Limitations to module settings should be documented (later).

**Review by Vazonik — APPROVED** [review]

**Pull request merged**
