### PR TITLE
db/click-selected-city

### PR DESCRIPTION
**Pull request by karolkolodziej**
Added return when clicking on the selected city.

### CODE REVIEW

**Comment by sebastianbochan** [comment]
What is the reason for it? Any side effect?

**Comment by karolkolodziej** [comment]
@sebastianbochan without that, if you click on the already selected city, the series in the navigator disappear.

**Comment by sebastianbochan** [comment]
Does `e.preventDefault` or `stopPropagation` not solve the problem?

**Comment by karolkolodziej** [comment]
No, in this case, `cityScope === city`, we don't want to run the callback at all.

**Review by sebastianbochan — APPROVED** [review]

**Review by pawellysy — APPROVED** [review]

**Pull request merged**
