### PR TITLE
Removed references to _modules

### PR DESCRIPTION
**Pull request by jomar-honsi**
Resolves https://app.asana.com/0/1203234853779882/1208879875572159/f

### CODE REVIEW

**Review by ddragula — COMMENTED** [review]
Nice! Could you also register the rest of converters, for consistency?

**Review by sebastianbochan — APPROVED** [review]

**Review by ddragula — APPROVED** [review]
Great, thank you! 🎉

**Review by TorsteinHonsi — APPROVED** [review]
Thanks, looks good 👍

**Comment by TorsteinHonsi** [comment]
... except the failing CI check...

**Comment by jomar-honsi** [comment]
> ... except the failing CI check...

Should soon be sorted out: https://github.com/highcharts/highcharts/tree/dash/datagrid-missing-dts

**Comment by sebastianbochan** [comment]
We just already fixed it here: https://github.com/highcharts/highcharts/pull/22366

**Pull request merged**
