### PR TITLE
Fixed `TreemapSeries` to drill up if needed when setting new data.

### PR DESCRIPTION
**Pull request by hon2a**
If you drill into a `TreemapSeries` and then update its data, you might end up with an inconsistent state, drilled to a point that either
1. no longer has children, or
2. doesn't exist at all.

The former you can at least get back from by clicking on the drill up button. The latter causes clicks on the drill up button to throw, leaving the chart broken.

---

This patch fixes `TreemapSeries` to drill up as far as necessary when the data is updated so as to end up drilled to a point that exists and has children in the new data.

### CODE REVIEW

**Comment by znevrly** [comment]
Hi,
please would you like to review and merge this PR, we have pending bug on this.

Thank you a lot!

**Comment by jon-a-nygaard** [comment]
@znevrly Yes, certainly! Will review it right away.

**Comment by jon-a-nygaard** [comment]
@hon2a Thanks for the PR, your suggested code changes was of very good quality, but I decided on a slightly different solution to the issue. Your commit pointed out many improvements which I have included in the final fix.

The fix is tracked in issue #6180 which is planned to be included in the next version 5.0.7.

**Comment by hon2a** [comment]
Ok, thanks for the info.

**Pull request closed without merging**
