### PR TITLE
docs/navigator-update

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Improved navigator docs page.

_Before merging, replace demo links with stable ones from #21602._

### CODE REVIEW

**Review by DJTechnoo — APPROVED** [review]
Looks Great!

**Review by bm64 — APPROVED** [review]

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by pawellysy — APPROVED** [review]

**Comment by TorsteinHonsi** [comment]
@kamil-musialowski #21602 is now merged

**Comment by kamil-musialowski** [comment]
Thanks @TorsteinHonsi ! I have updated the links so now it's ready to merge.

**Pull request merged**
