### PR TITLE
Blog demo about accessibility tags

### PR DESCRIPTION
**Pull request by mekhatria**
Add a blog demo about accessibility tags

### CODE REVIEW

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! I have no complaints about the coding, but I think the chart itself looks a bit boring:

Skjermbilde 2023-02-21 kl  18 47 58

* Maybe use separate colors for the columns? Either through `colorByPoint` or by assigning individual point colors.
* We word Penguin is repeated in the title, the subtitle, the y axis title , the x axis title and the legend. Especially the legend can be removed, since we only have one series. Y axis title perhaps can be "Count"? X axis title can also be removed, since the chart title already describes that we are dealing with penguin species. Unless of course the X axis title serves a point for demonstrating the accessibility tags

**Comment by TorsteinHonsi** [comment]
Asking @oysteinmoseng for a review of the coding.

**Review by oysteinmoseng — APPROVED** [review]
Coding is all good 👍

**Comment by mekhatria** [comment]
I kept only the X axis title to demonstrate the accessibility tags

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
