### PR TITLE
bugfix/20318-navigator-series-datasorting-empty-data

### LINKED ISSUE #20318: `Navigator` series not rendered on initial load with `dataSorting` enabled
#### Expected behaviour
Navigator series is displayed on initial load with `dataSorting` enabled.

#### Actual behaviour
Navigator series is not displayed on initial load with `dataSorting` enabled.

#### Live demo with steps to reproduce
[https://jsfiddle.net/BlackLabel/p03895tu/](https://jsfiddle.net/BlackLabel/p03895tu/)

#### Product version
Highcharts Stock since v8 (since adding the data sorting)

### PR DESCRIPTION
**Pull request by jedrzejruta**
Fixed #20318, `Navigator` series data wasn't set with `dataSorting` enabled on initial run.

### CODE REVIEW

**Review by pawelfus — COMMENTED** [review]
Q: Why can't we reuse `setSortedData()` method? Or to put it in different words, why that method does not set data for series with 'sorted' option in Navigator?

**Comment by jedrzejruta** [comment]
> Q: Why can't we reuse `setSortedData()` method? Or to put it in different words, why that method does not set data for series with 'sorted' option in Navigator?

When you mentioned using `setSortedData()`, it seems that it's better to reuse this method in this case.

**Review by pawelfus — APPROVED** [review]
Looks good. I think it shouldn't affect the performance - the navigator needs this, and other series should already have `points` defined

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
