### PR TITLE
Feature/stock annotation icons

### PR DESCRIPTION
**Pull request by nasin**
These are icons for the following new stock annotation/series:

- Heikin Ashi, touch #15348
- Hollow candlestick, touch #15347
- HLC, touch #15346
- Time cycles, touch #15826
- Fibonacci Timezones touch #15825
- Freeform drawing, touch #15827

### CODE REVIEW

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! I added a change to make the existing icons render regardless of sizing.

In addition, it seems that there are some  sample file changes in this PR that are out of scope. They hasn't got do do with the annotation icons.

**Review by TorsteinHonsi — COMMENTED** [review]
Regarding the icons themselves, it seems like at least some of the new ones have a thinner line style than the existing ones. Is that a problem?

Skjermbilde 2021-06-09 kl  12 38 28

**Comment by pawelfus** [comment]
> Thanks! I added a change to make the existing icons render regardless of sizing.

Icons are a little too big right now 😅  (and separators too small) Compare:
- [current](https://jsfiddle.net/BlackLabel/sgbukwmj/4/)
- [candidate](https://jsfiddle.net/BlackLabel/sgbukwmj/5/) (you can observe new icons "in action")

|Zrzut ekranu 2021-06-9 o 14 27 23| Zrzut ekranu 2021-06-9 o 14 27 32 |

**Review by pawelfus — CHANGES_REQUESTED** [review]
Could you add `series-` prefix to all series-related icons, so we match the current format? For example `series-hlc` instead of `hlc-series`

Thanks!

**Comment by TorsteinHonsi** [comment]
> Icons are a little too big right now

Oh. Since I removed the width and height attributes, the background is now stretched to the size of the button. But I'm inclined to think that this is better behaviour (more responsive). Is there a way to make them render like they did, but using CSS? 

In addition, the new icons in this PR do not have width and height attributes, so in order to make it consistent, we need to either add attributes to those or remove them from the old ones.

**Comment by pawelfus** [comment]
> Oh. Since I removed the width and height attributes, the background is now stretched to the size of the button. But I'm inclined to think that this is better behaviour (more responsive). Is there a way to make them render like they did, but using CSS?

@sebastianbochan - I need your assist, what do you think? Can we get the old behaviour in CSS?

**Comment by nasin** [comment]
I created new icons for the follow: 

- Ellipse, touch #15008 
- Disable Zoom (panning.svg), no ticket yet, 
- linear.svg and logarithmic.svg for axes switching, #15695 
- Clear chart -- I suggest using the trash can icon (destroy.svg), no ticket yet. 

I also renamed series icons. And I updated the width of the lines on some of the icons (drawing, time-cycles, fibonacci timezones.)

**Comment by TorsteinHonsi** [comment]
> @sebastianbochan - I need your assist, what do you think? Can we get the old behaviour in CSS?

@pawelfus, @sebastianbochan We can use [background-size](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size). I added a commit with it. In my opinion it is better to do this in CSS than in the SVG file itself, as it then possible for designers to override it (for example in responsive designs) without modifying the icons. Feel free to revert if you disagree.

**Comment by pawelfus** [comment]
Added all icons to the demo: https://jsfiddle.net/BlackLabel/sgbukwmj/7/ (the first group) - looks great! 

> In my opinion it is better to do this in CSS than in the SVG file itself, as it allows designers to override it (for example in responsive designs) without modifying the icons

Convinced 👍 


@nasin - could we decrease the number of vertical lines in Fibonacci timezones? Or decrease the line-width of the first one (I guess this is the one Torstein was referring to in one of his previous comments):
Zrzut ekranu 2021-06-10 o 11 54 54

**Comment by nasin** [comment]
Hi, I made the lines on the fibonacci icon all the same width.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
@nasin Can you remove the `samples/highcharts/website/*` stuff from this PR? They are out of scope for this PR, I assume they belong in another branch?

**Review by TorsteinHonsi — APPROVED** [review]

**Comment by TorsteinHonsi** [comment]
Pending approval by @pawelfus

**Comment by TorsteinHonsi** [comment]
Merging, as Pawel's change request seems to be fixed.

**Pull request merged**
