### PR TITLE
bugfix/ast-allow-description-list-tags

### PR DESCRIPTION
**Pull request by ryanbonial**
Fixed the removal of description list ( `<dl>`, `<dt>`, and `<dd>`) tags by adding them as allowed tags in the AST.

### CODE REVIEW

**Comment by KacperMadej** [comment]
Hi @ryanbonial 

Thank you for submitting the PR.

**Comment by KacperMadej** [comment]
@ryanbonial 
Could you create an issue for the problem that this PR solves? With a live demo and maybe a longer description so we could add a test for the issue and reference the fix later in the changelog., if possible, please.

**Comment by TorsteinHonsi** [comment]
Thanks again! It's okay without an issue, we will add the list tags to the allow list. I'll be adding them in a separate PR so this one will be closed. Leaving it open until then. No further action required.

**Comment by ryanbonial** [comment]
Thank you!

**Pull request closed without merging**
