### PR TITLE
bugfix/21274-plotbands-on-navigator

### PR DESCRIPTION
**Pull request by pawellysy**
Fixed https://github.com/highcharts/highcharts/issues/21274,  `plotBands` were assigned to the wrong `yAxis` when there was no series in navigator.

### CODE REVIEW

**Review by kamil-musialowski — APPROVED** [review]
Nice!

**Review by bm64 — APPROVED** [review]

**Review by DJTechnoo — CHANGES_REQUESTED** [review]
Looking good! There is still another part of the issue that needs to be resolved form this comment https://github.com/highcharts/highcharts/issues/21274#issuecomment-2222239530

**Review by DJTechnoo — APPROVED** [review]
Looks great!

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
