### PR TITLE
Tools: Added virtual package.json in code folder for local testing.

### PR DESCRIPTION
**Pull request by bre1470**
Makes it possible to use `npm i ../highcharts/code` for local testing of the repository in npm-based projects.

### CODE REVIEW

**Review by karolkolodziej — APPROVED** [review]
Tested in fresh Angular project, works fine!

**Comment by bre1470** [comment]
Great! 👍 Let me just add the `--dts` flag to the watch task, so the typing is always available.

**Comment by karolkolodziej** [comment]
@bre1470 Could you also please add a `.md` file with quick guidelines that we can refer to in the future?

**Comment by bre1470** [comment]
Sure, though I can not decide where to put it. Makes it sense to add it to the `ts/README.md`?

**Comment by karolkolodziej** [comment]
Yes, `ts/README.md` looks good for me ;)

**Review by TorsteinHonsi — APPROVED** [review]
Looks good!

**Comment by TorsteinHonsi** [comment]
Pending approval by @karolkolodziej

**Review by karolkolodziej — APPROVED** [review]

**Pull request merged**
