### PR TITLE
enhancement/8912-stacked-labels-crop-overflow

### PR DESCRIPTION
**Pull request by Basts**
Added `overflow` and `crop` options to stack labels. See #8912.

### CODE REVIEW

**Comment by Basts** [comment]
@TorsteinHonsi 

I considered using **justifyDataLabel**, but **dataLabels** are rendered in a different way than **stackLabels** 
- main differences: **dataLabels** has additional features, which has an impact for the position, like rotation and **padding**, **stackLabels** "finds" their positions via **getStackBox** function, while **dataLabels** does it via **alignTo** property. 

Using a justifyDataLabel function for both cases requires:
1. adding padding feature into **stackLabels**,
2. **justifyDataLabel** function is justified dataLabel via: 
`    if (justified) {
        dataLabel.placed = !isNew;
        dataLabel.align(options, null, alignTo);
    }
 `
I haven't tested how it will be aligining for **getStackBox** rather than **alignTo**, but as I did investigation their **alignAttr.x** is totally different, so I assumed that some additional refactor will be needed.

**Comment by TorsteinHonsi** [comment]
Hmm.. I think it's unfortunate that we have two different code paths for so similar features. I imagine that the positioning logic should be identical for a _stack_ and a _column_ in a column series. The `getStackBox` would be equivalent to the column. Can you do some more research and see if we can piggy-back the column datalabel positioning logic more?

**Comment by Basts** [comment]
@TorsteinHonsi 
Ok, then I will try to refactor `stackLabels` to match them to `justifyDataLabel` function.

What about padding feature? Should it be implemented into stackLabels or set to 0 by default? This value is needed to find a proper position via `justifyDataLabel` function.

**Comment by TorsteinHonsi** [comment]
> What about padding feature? 

As a minimum viable solution, it is probably ok to set it to 0 for now.

**Comment by bre1470** [comment]
@basts You have to resolve the conflict by applying the changes to the `ts/parts/Stacking.ts` file.

**Comment by TorsteinHonsi** [comment]
Fixed in another PR.

**Pull request closed without merging**
