### PR TITLE
dash/datagrid-highlight-sync-scroll

### PR DESCRIPTION
**Pull request by vazonik**
Added `autoScroll` option to the Datagrid's highlight sync.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206739220855159

### CODE REVIEW

**Review by jomar-honsi — APPROVED** [review]
Great enhancement!

**Review by sebastianbochan — APPROVED** [review]
Simple and clever, great improvement!

ps. Tested with different CSS styles, flex order and mobile. All cases worked like a charm!

**Review by karolkolodziej — APPROVED** [review]

**Review by stitot — COMMENTED** [review]
This is sweet!! Nice work!

Would it be more intuitive for the user what is happening if it's not the top row that is highlighted? Either the middle row in the viewable area or at least one from the top? IMO it would be easier to orient oneself if you see that it's content above the highlighted row as well. If not toooooooo much work to fix.

**Review by jomar-honsi — APPROVED** [review]

**Review by stitot — COMMENTED** [review]
Nice! IMO this is more intuitive and easier to see what's happening. To be picky: 

1. Possible to avoid that small flicker in the datagrid when autscrolling?
2. If you hover the mouse on one row in the datagrid and then scroll with mouse the chart is not updating.

**Comment by vazonik** [comment]
> 1. Possible to avoid that small flicker in the datagrid when autscrolling?

I tried to reduce it with a timeout, I managed to improve it slightly, but I would leave it for when we have a better virtual scroll.


> 2. If you hover the mouse on one row in the datagrid and then scroll with mouse the chart is not updating.

I moved it to a separate issue: #21051.

**Review by jomar-honsi — APPROVED** [review]

**Review by stitot — APPROVED** [review]

**Pull request merged**
