### PR TITLE
bugfix/11738-treemap-update

### LINKED ISSUE #11738: Treemap - update issue when same amount of points
Update feature doesn't work in the case of updating the same amount of points as the number of points for initial series.

Last working version is 7.0.3 - [demo](https://jsfiddle.net/BlackLabel/pxdjk4yo/)

#### Live demo with steps to reproduce

[Demo](https://jsfiddle.net/BlackLabel/8ux9j7d4/)

#### Product version
versions > 7.0.3

### PR DESCRIPTION
**Pull request by pawelfus**
Fixed #11738, updating treemap series with the same amount of points caused cells to disappear.

### CODE REVIEW

**Comment by pawelfus** [comment]
Hmm.. strange, in the first visual test I see no difference (maybe because of the gif's quality), while the second one has different `Zoom` text rendering - not related to the commit

**Comment by lezan** [comment]
I do not know if I am missing something, but I am trying to use master branch to fix the problem mentioned here #11829 but still It can not update correctly in my case.
[Here](https://www.highcharts.com/forum/viewtopic.php?f=9&t=42574&p=149765#p149765) there is conversation with me and Bastss.
You can find a jsfiddle here: https://jsfiddle.net/e8uda9gw/.

Thank you.

**Comment by pawelfus** [comment]
Thanks! I will check this

**Comment by pawelfus** [comment]
Created separate ticket for this issue with ID's: https://github.com/highcharts/highcharts/issues/12333

**Pull request merged**
