### PR TITLE
ts/roc-indicator

### PR DESCRIPTION
**Pull request by wchmiel**
Migrated roc indicator to the class pattern.

### CODE REVIEW

**Review by bre1470 — APPROVED** [review]
Thank you! Looks good. 👍

**Comment by bre1470** [comment]
Please merge master to solve conflicts.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
As she said ☝️

**Comment by bre1470** [comment]
@TorsteinHonsi Merge is done.

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
