### PR TITLE
demo/stock-png-thumbnail-demos

### PR DESCRIPTION
**Pull request by bm64**
Added use_png_thumbnail flag in stock demos.

### CODE REVIEW

**Review by pawelfus — CHANGES_REQUESTED** [review]
2/3 - missing the third CSS demo (by Pueblo)

**Review by kamil-musialowski — APPROVED** [review]
All good, just add Pueblo's demo

**Review by pawelfus — APPROVED** [review]
Missed that, thanks!

**Review by TorsteinHonsi — COMMENTED** [review]
Thanks! May I ask why we need a PNG thumbnail for the neon line chart demo? It looks pretty straight forward and the SVG would probably be smaller?

**Comment by pawelfus** [comment]
Because it uses styled mode. Not sure about the details, @goransle could you help?

**Comment by goransle** [comment]
The thumbnail builder does not handle styled mode too well: 
image

Likely something that could be investigated

**Review by TorsteinHonsi — APPROVED** [review]
Okay @goransle . We could include `highcharts.css`, but would probably not get the results we wanted anyway. Possibly inject the contents of `highcharts.css` directly into the SVG, and append contents of `demo.css` after that to respect overrides.

Anyway I'm merging this, because the styled mode problem is probably a bigger issue that applies to other samples too.

**Pull request merged**
