### PR TITLE
dash/rangemodifier-crossfilter

### PR DESCRIPTION
**Pull request by bre1470**
RangeModifier will now intersect the results of multiple ranges by default. Use the `additive` option to concatenate results of multiple ranges.

Based on #19441 - merge first!

### CODE REVIEW

**Comment by sebastianbochan** [comment]
Running the [demo](http://utils.highcharts.local/samples/#view/highcharts/data-tools/rangemodifier-crossfilter), I am not able to filter the table. Am I doing something wrong?

filtering

**Comment by bre1470** [comment]
I do not know. Maybe recompile?

**Comment by sebastianbochan** [comment]
The problem was caused by the missing rebuild of HC.

**Review by pawelfus — APPROVED** [review]
Nice!!

**Review by pawellysy — APPROVED** [review]
LGTM!

**Review by karolkolodziej — APPROVED** [review]

**Pull request merged**
