### PR TITLE
db/kpi-navigator-series-type

### PR DESCRIPTION
**Pull request by sebastianbochan**
When changing KPI (clicking on KPI component), the chart and navigator should change/set it's type:
- temperature and avg temp => line/spline chart (see both, whichever looks/animates better is fine)
- Fog/Ice/Rain days => column chart

### TODO:
- [x] - navigator
- [x] - main chart
- [x] - styles

### CODE REVIEW

**Review by karolkolodziej — APPROVED** [review]

**Review by bre1470 — CHANGES_REQUESTED** [review]
It looks strange that the initial series is rendered as column and then animates to spline. That should be fixed.

**Review by pawellysy — APPROVED** [review]
LGTM!

**Comment by sebastianbochan** [comment]
@bre1470 I am not able to reproduce it, running the demo. in the navigator, there is a spline by default.

**Review by bre1470 — APPROVED** [review]
@sebastian Me neither. Looks good now.

**Pull request merged**
