### PR TITLE
Migration: LegendSymbol

### PR DESCRIPTION
**Pull request by bre1470**
- Migrated LegendSymbolMixin into a namespace.

### CODE REVIEW

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Comment by transdoc** [comment]
Hi, I was using `H.LegendSymbolMixin.drawLineMarker` outside Highcharts, how can I update my code after this change so that I can still get `drawLineMarker`? Thanks.

**Comment by bre1470** [comment]
Hello! I suggest to use `Series.prototype.drawLegendSymbol`.

**Comment by transdoc** [comment]
OK, thanks a lot.

**Pull request merged**
