### PR TITLE
bugfix/18658-sunburst-labels-blinking

### LINKED ISSUE #18658: Sunburst: data labels re-animate when points are programmatically updated
#### Expected behaviour
When updating a point programmatically using `point.update(...)` (e.g., to make it sliced), I expect minimal animation.

#### Actual behaviour
The data labels disappear and fade back in when I perform that update.

#### Live demo with steps to reproduce
https://jsfiddle.net/cedricbaptk/f0xhqpuk/

Click the "toggle sliced" button. This causes one of the point to toggle its `sliced` option. The slice correctly animates, but all data labels also disappear and fade back in when the button is clicked.

This can also be triggered simply by calling `series.redraw()`.

Presumably, this is caused by the `hackDataLabelAnimation` flag being `true` here (v10.3.3):
https://github.com/highcharts/highcharts/blob/2bc6062f482bd649a52aa625bc53116c0bc81a4b/ts/Series/Sunburst/SunburstSeries.ts#L839-L844

Indeed, I can work around the issue by temporarily setting `series.idPreviousRoot` to `series.rootNode`. Example workaround to apply to the jsfiddle above:
```diff
+      const s = p.series;
+      const tmp = s.idPreviousRoot;
+      s.idPreviousRoot = s.rootNode;
       p.update({sliced: !p.sliced});
+      s.idPreviousRoot = tmp;
```

#### Product version
Highcharts v10.3.3

#### Affected browser(s)
Latest Chrome

### PR DESCRIPTION
**Pull request by Vazonik**
Fixed #18658, all sunburst's data labels were disappearing and showing back after one point update.

### CODE REVIEW

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
@Vazonik When removing code, it is important to consider closely what is lost. One thing I can see is that the data labels now suddenly appear initially, instead of easing/fading in. This is what should be controlled by the [dataLabels.defer](https://api.highcharts.com/highcharts/series.line.dataLabels.defer) option, and in the current state of this PR, it behaves like `defer` is always false.

I recommend taking a closer look at what is going on in that code block, hopefully we can do it in a more consistent way. Maybe we can implement the `defer` option in another place, more consistent with other series types. If things were done correctly, it shouldn't be necessary with series-specific overrides like this.

**Comment by Vazonik** [comment]
@TorsteinHonsi Thanks! Ignoring the defer option was caused by some other commit that had already been merged into the master, but I haven't identified which one of it yet. This regression applies to data labels regardless of series type. Should I fix it in this pull request or should I make a separate issue for it?

My change causes, for example, removing the fadein-fadeout animation of data labels during drill down, but with @pawellysy we found that it could also be unnecessary.

**Comment by TorsteinHonsi** [comment]
> Ignoring the defer option was caused by some other commit that had already been merged into the master

In that case it is important that we find it and fix it before the next release. Do you have a demo of this? It seems to work well here (on the master): https://jsfiddle.net/highcharts/rz82ywtp/

**Comment by Vazonik** [comment]
> Do you have a demo of this?

@TorsteinHonsi Yes:
- master: https://jsfiddle.net/BlackLabel/t23qonpy/
- v10.3.3.: https://jsfiddle.net/BlackLabel/2b6jzk3g/

**Comment by TorsteinHonsi** [comment]
Okay, it's caused by this regression: https://github.com/highcharts/highcharts/issues/18478 . If we set a container height in the CSS, we fix the redraw issue and the data labels behave like they should.

**Comment by Vazonik** [comment]
Ok, so now it works like this: https://jsfiddle.net/BlackLabel/Lg5c0nwu/

**Review by TorsteinHonsi — APPROVED** [review]
Yes, seems good now!

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
I now remembered what the `hackDataLabelAnimation` is about. It is for traversing the sunburst. See http://localhost:3030/samples/#view/highcharts/demo/sunburst and click Europe. Without the hack, the data labels animate in a chaotic way. That's why we decided to just temporary hide them and fade back in instead of trying to animate between different rotations and text paths. I think what you need to do is to keep the logic is it was, but rather inspect when the `hackDataLabelAnimation` is activated. So that it does not get activated when just doing a simple point update. In fact, looking at the previous line 851, I would expect it to only happen when the root changed, which is does not do in this case.

**Comment by TorsteinHonsi** [comment]
Thank you! While we're in this part of the code, I want to ask you to to check out something I have been noticing for a while. See https://jsfiddle.net/highcharts/6eka4tmn/. If you click the middle element, "Oceanic", you also get the blinking of the data labels. I would expect that in this case the root id was identical to the previous root id, since we're not allowed to traverse further up, and subsequently the labels shouldn't blink. Can you have a look at that?

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
