### PR TITLE
Split DTS

### LINKED ISSUE #18980: highcharts.d.ts is 603000 lines long and freezes editors
#### Expected behaviour

I expect type file to be split in smaller files and more manageable. It is over 603000 lines long and took me all night to index in IntelliJ and still afterwards my machine is basically down.

#### Actual behaviour

Split to smaller type files

#### Product version
11.0.1

### PR DESCRIPTION
**Pull request by bre1470**
Closed #18980, #20136; Moved majority of series options into separate definition files (`.d.ts`).

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206611758472806

### CODE REVIEW

**Review by MarkusBarstad — APPROVED** [review]
LGTM!

Only thing i do not understand is: wasnt decleration files already split? 

In my `highcharts/code/es-modules/`-folder I can find many split declerations files corresponding to source-code files like `Utilities` etc 🤔

**Comment by bre1470** [comment]
This adresses the distributed bundled declarations in the root of `code/`. The native declarations in `code/es-module/` are just for internal tests and do not go into the NPM package.

**Review by Xillez — APPROVED** [review]
lgtm 👍

**Review by goransle — APPROVED** [review]
Looks good!

**Review by KacperMadej — COMMENTED** [review]
- [ ] why some series like have the main options interface defined like `PlotBellcurveOptions` in `highcharts.src.d.ts` and not in `options/bellcurve` while the map series does?
- [ ] JSDoc comments have `@product` field that is used for API docs to filter some options. In map series, that is for Highcharts Maps only, there is no `jitter` option as that option is inherited from `scatter` but defined only for `highcharts, highstock` and is not visible for the map series. A not needed interface was created (`PlotMapJitterOptions`). I tried excluding `jitter` in JSDoc comment at `plotOptions.map` level and that seems to be working (no wrong interface nor jitter in map series).
- [ ] there are a lot of long interfaces like `PlotMapSonificationContextTracksMappingHighpassFrequencyOptions` that are the same. Can these be reduced to save some bytes?
- [ ] why `PlotMapDataLabelsAnimationOptions` is in `highcharts.d.ts` while only one `PlotZigzagDataLabelsAnimationOptions` is in `options/zigzag`? And maybe more importantly, why every series have own interface for this even though all seem to have only the `defer` option in it? (the only difference I see is the product limitation in the description related to the series)

**Comment by KacperMadej** [comment]
- [ ] another "trashy" prop is `onPoint` that is added on SeriesOptions and makes all series create `Plot${series.type}OnPointOptions` interfaces - even though the `onPoint` feature works only for `pie` and `sunburst`.

**Comment by KacperMadej** [comment]
- I am not sure if this is related to the changes here but I am also getting a log that looks like a warning:

```console
Finished 'jsdoc-options' after 4.58 min
Start creating TypeScript declarations...
Creating declarations...
Unknown kind:  code/modules/tiledwebmap {
  doclet: { name: 'Highcharts.MapView' },
  children: [ { doclet: [Object] }, { doclet: [Object] } ]
}
Saving declarations...
Finished creating TypeScript declarations.
```

**Review by marvin19 — APPROVED** [review]

**Review by MarkusBarstad — APPROVED** [review]
🚀

**Comment by bre1470** [comment]
@KacperMadej Please create asana tickets for unresolved findings.

**Review by hubertkozik — COMMENTED** [review]
I am not sure if this is related to current changes, but I cannot generate declarations now: 
image

Update:
My bad, after bisecting `tree.json` was broken - don't know why. Works good after generating everything from scratch!

**Review by hubertkozik — APPROVED** [review]
`highcharts.d.ts` is light now (if we compare it to ~23MB before) 🎉

**Review by KacperMadej — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
