### PR TITLE
bugfix/15005-groupAll-dataGroup-start

### LINKED ISSUE #15005: Highstock chart point get wrong dataGroup start index when dataGrouping's options groupAll is true
#### expected behavior
get correct point.dataGroup.start index no matter zoom range is used or not

#### Actual behaviour
get wrong point.dataGroup.start when zoom range is selected. 

this problem only happens when dataGrouping setting groupAll: true, if groupAll:false, both scenario get corrected index.

#### Live demo with steps to reproduce
https://jsfiddle.net/98t1v4cp/3/

#### Product version
lastest

#### Affected browser(s)
bug

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #15005, when `groupAll` was set to true, group start was badly calculated.

### CODE REVIEW

**Review by TorsteinHonsi — APPROVED** [review]
Thanks! Pending the other reviewers.

**Review by pawelfus — APPROVED** [review]
Nice catch!

**Review by raf18seb — APPROVED** [review]
Perfect, thanks 👍

**Review by pawellysy — APPROVED** [review]
Looks great!

**Comment by TorsteinHonsi** [comment]
Merged in master. Pending CI.

**Pull request merged**
