### PR TITLE
bugfix/13572-incorrect-path-rendering-for-area

### LINKED ISSUE #13572: Incorrect path rendering for area
#### Expected behaviour
The ability to correctly set the color of the line surrounding the area using the CSS options.

#### Actual behaviour
When we want to set the line color surrounding an area using the CSS:
`.highcharts-area { 
	stroke-width: 3;
	stroke: red;
}
`
There is no border on one edge because the path is not closed:
https://jsfiddle.net/BlackLabel/7d0fq2ah/

Possible workaround - improved core function responsible for rendering this path (adding 'Z'):
https://jsfiddle.net/BlackLabel/wnypd0gs/

#### Product version
Highcharts v8.1.0

### PR DESCRIPTION
**Pull request by madepiet**
Fixed #13572, area series fill was not closed, making it hard to add a stroke for the area itself.

### CODE REVIEW

**Comment by sebastianbochan** [comment]
Looks good 👍

**Review by sebastianbochan — APPROVED** [review]

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks!

Sideways animation is broken (when adding point with `shift`): https://jsfiddle.net/y6Lz03pa/

**Comment by sebastianbochan** [comment]
It looks like a problem with double `areaPath.push(['Z']);` 

Suggested fix:
https://jsfiddle.net/BlackLabel/e2p36k9u/

**Comment by madepiet** [comment]
The problem seems to be more complex as it works fine with this code, but you can see the jump on the left side. I wonder how this is supposed to work - smoothly moving from the left side?

In the code, I only push 'Z' once, but it also requires a change in the animation function. Because right now we move the whole hardcoded path which is not correct.

**Comment by TorsteinHonsi** [comment]
@sebastianbochan 

> Is it the desired effect?

No, as you can see with your fiddle, the series doesn't move at all. It is supposed to slide sideways to make room for the new point.

> In the code, I only push 'Z' once, but it also requires a change in the animation function. Because right now we move the whole hardcoded path which is not correct.

Off the top of my head, I think what happens in the animation is that it splits the area path in two and injects the new point in the middle. So you need to make sure the added length of the path segments (the `Z`) is accounted for.

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
