### PR TITLE
enhancement/11308-center-column-with-nulls

### PR DESCRIPTION
**Pull request by raf18seb**
Added new property `series.ignoreNulls` which centers the columns within a category when other series have a null value or missing points.

This PR is a continuation of https://github.com/highcharts/highcharts/pull/12460

### CODE REVIEW

**Comment by raf18seb** [comment]
@TorsteinHonsi all tests have finally passed, ready for review.

**Comment by TorsteinHonsi** [comment]
Thanks for the PR! This is now a quite massive addition to the code base, and many operations are similar to the existing stack logic. I created an alternative solution at https://github.com/highcharts/highcharts/pull/12846, so let's put this on hold until we have discussed that.

**Comment by TorsteinHonsi** [comment]
Continued in https://github.com/highcharts/highcharts/pull/12818

**Comment by TorsteinHonsi** [comment]
Continued in https://github.com/highcharts/highcharts/pull/12818

**Pull request closed without merging**
