### PR TITLE
Some Dashboards demo styling

### PR DESCRIPTION
**Pull request by TorsteinHonsi**
Some styling of dashboards and dash demos

* Rounded corners for the components in accordance with the design sketch
* Left and right padding for the component title to match chart and grid components
* Non-default titles for some of the components to make it a tad more lifelike
* Dark mode demo with tri-state switch
* More consistent colors in dark mode. Text colors, impolementation for grid component (using the `.highcharts-light` and `.highcharts-dark` nomenclature.
* Use common variable names. When merged with v11, we get the same naming for neutral and highlight colors. After that we should consider a separate file for the color variables.

### CODE REVIEW

**Review by pawelfus — COMMENTED** [review]
Just a dummy comment, to get notification when ready

**Review by pawelfus — APPROVED** [review]
Thanks!

**Comment by TorsteinHonsi** [comment]
Pending review from @sebastianbochan .

**Review by sebastianbochan — APPROVED** [review]
Looks good for me 👍 

Sorry for delay.

**Pull request merged**
