### PR TITLE
NPM

### PR DESCRIPTION
**Pull request by bre1470**
The suggested solution to the NPM name conflict is to take our GitHub packages under the `@highcharts` namespace.

To-Do:
- [x] Merge `npm-hotfix` branches with new package name into master for
  - `highcharts-utils` https://github.com/highcharts/highcharts-utils/pull/48
  - `highcharts-documentation-generators` https://github.com/highcharts/highcharts-documentation-generators/pull/62
- [x] Change github dependencies accordingly to master branch or release tag.

### CODE REVIEW

**Comment by bre1470** [comment]
Unsolved issues:
- The visual comparison fails, because the master is not fixed yet.
- Safari has some connection issues with Browser Stack.
- Safari test reveals that test `Highcharts Point animation` fails.

**Comment by bre1470** [comment]
Thank you! What do you mean with "except utils"?

**Comment by bre1470** [comment]
Workaround for visual tests in utils by @pawelfus: In `highcharts-utils` repo find `functions.js` file, then increase `daysToTry` variable (e.g. 20+ days). Restart server.

**Comment by bre1470** [comment]
PR is ready for final tests. On my installation linting, testing and building (scripts, jsdoc, definitions) works.

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
