### PR TITLE
[3D] Fix perspective of Axis labels

### PR DESCRIPTION
**Pull request by paulo-raca**
Highcharts goes to great effort to position Axis labels in a way that looks good -- Proper spacing, no overlaps, etc. And they do look great!

Unless you use 3-D, that is.

In 3D, the label positions always stay bellow their ticks, but the text stays flat despite the perspective projetion, creating overlaps and mayhem.

This patch adds 2 options to 3-D chart axis:
 - `labels.skew3d` and `title.skew3d`: Enables skewing the text to follow the perspective. By itself, it fixes the overlaps.
    
 - `labels.position3d` and `title.position3d`: Modifies the position of axis labels/titles according to the chart orientation. It can be:
    - `'offset'`: Maintain a fixed horizontal/vertical distance from the tick marks, despite the chart orientation.
      This is the backwards-compatible behavior, and causes skewing of X and Z axes.
    - `'chart'`: Preserve 3D position relative to the chart.
      This looks nice, but hard to read if the text isn't forward-facing.
    - `'flap'`: Rotated text along the axis to compensate for the chart orientation.
      This tries to maintain text as legible as possible on all orientations.
    - `'ortho'`: Rotated text along the axis direction so that the labels are orthogonal to the axis.
      This is very similar to `'flap'`, but prevents skewing the labels (X and Y scaling are still present).

### Demo

http://jsfiddle.net/mruko5m2/

### Perspective
SVG doesn't really support perspective projection, which means "label skewing" won't make the label's text shrink with the distance.

Despite that limitation, skewing is calculated around each label's anchor point, which yields very convincing results.

### CODE REVIEW

**Comment by pawelfus** [comment]
Thank you! Let's wait for @TorsteinHonsi with merge.

**Comment by TorsteinHonsi** [comment]
Thanks for the PR! Great looking as always.

I'm a bit in doubt of the naming. Shouldn't the options be put on the actual axis options instead? So rather than `options3d.axisLabelSkew` it should be `xAxis.labels.skew`, and rather than `options3d.xzAxisLabelOrientation` it should be `xAxis.labels.orientation` and `zAxis.labels.orientation`? It seems more appropriate to me. Except I noticed that also the axis _title_ is affected, so maybe we need to put the option directly on the axis root.  @pawelfus What do you think?

**Comment by pawelfus** [comment]
You are right, these options should be under x/y/zAxis. I am not sure which solution would be better: each option on a separate level (`xAxis.title.skew` and `xAxis.labels.skew`) or options together (`xAxis.skewSomething?`). Personally I would choose the first one: it will get user an option to decide if he/she wants to apply options for all labels and will be more in Highcharts-style.

**Comment by paulo-raca** [comment]
Thanks for looking at it, guys.

To be honest, I'm not a fan of setting the same option 6 times (Every axis, label and title), but that's fine with me. I'll update this PR soon

**Comment by paulo-raca** [comment]
Ok, I've placed the options under each axis' labels and title.

I also made some cleanups and renames, and the documentation was updated.

Please take a look and let me know what you think

**Comment by paulo-raca** [comment]
FYI, my demo sometimes triggers a Chrome bug :disappointed:.
It is being tracked at https://bugs.chromium.org/p/chromium/issues/detail?id=753254

**Comment by paulo-raca** [comment]
Turns out that the chrome bug has already been fixed on latest, so I'm removing the workaround hack from the PR.

**Comment by paulo-raca** [comment]
Hello, guys.
Have you had the time to take a look at this? Thanks

**Comment by TorsteinHonsi** [comment]
Thanks Paolo, once again solid work!

**Comment by paulo-raca** [comment]
Thank you.

I'm sorry I forgot about the linter...

**Comment by TorsteinHonsi** [comment]
No worries! In the future, you can check your code running `gulp lint`.

**Pull request merged**
