### PR TITLE
bugfix/20191-beforeunload-export

### LINKED ISSUE #20191: beforeunload is triggered on download a chart
Hi,
I have a chart with download button and a form on the same page. The trigger of beforeunload on download is causing unnecessary prompts for leaving the page 

#### Expected behaviour
beforeunload event should not be triggered by exporting a chart

#### Actual behaviour
beforeunload event is triggered by exporting a chart

#### Live demo with steps to reproduce
https://jsfiddle.net/o0cx86qL/6/

#### Product version
Highcharts 11.2.0

#### Affected browser(s)
Chrome

### PR DESCRIPTION
**Pull request by goransle**
Fixed #20191, exporting a chart using the export module caused `beforeunload` event to fire. 

The export function now uses `fetch` internally. As a result, the `exporting.formAttributes` option has been deprecated. `exporting.fetchOptions` has been introduced  to allow customisation of the `fetch` call.

### Upgrade note
The `exporting.formAttributes` option can for some purposes be replaced with `exporting.fetchOptions`. See [the fetch article on MDN](https://developer.mozilla.org/en-US/docs/Web/API/fetch) for more information about possible options.

Requires https://github.com/highcharts/highcharts-utils/pull/80 for testing

~~Sidenote: should we consider marking https://api.highcharts.com/highcharts/exporting.formAttributes as deprecated?~~

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206030888370566

### CODE REVIEW

**Review by bre1470 — APPROVED** [review]
No `beforeunload` with the issue example. Nice! 👍

**Review by KacperMadej — COMMENTED** [review]
Shouldn't tests be in test files and not in a sample used in docs? From the perspective of someone trying only to check out the sample code with the usage explained in the docs the demo is polluted with irrelevant code.

**Comment by goransle** [comment]
> Shouldn't tests be in test files and not in a sample used in docs? From the perspective of someone trying only to check out the sample code with the usage explained in the docs the demo is polluted with irrelevant code.

Good point. I added it to this sample as it already had a `requiresManualTesting` flag, but did not check if it was used in the documentation.

**Review by TorsteinHonsi — COMMENTED** [review]
The `fetch` API has been supported in evergreen browsers since 2017, which means we can throw out the old form submit feature and replace it with fetch. 

IE11 implementations can use a polyfill.

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
