### PR TITLE
Axis: added option title.reserveSpace: true.

### PR DESCRIPTION
**Pull request by larsac07**
This enables users to avoid having the title take up space.

### CODE REVIEW

**Comment by oysteinmoseng** [comment]
Looks like a good idea. Maybe add a unit test/demo or something? Also, is this going in the public API?

**Comment by larsac07** [comment]
Was thinking public API. Since `*Axis.labels.reserveSpace` is already there, it shouldn't be very confusing. Should I add the `// docs`-flag?

**Comment by oysteinmoseng** [comment]
Unless @TorsteinHonsi has innvendinger I'd suggest you just add the docs to the API (w/next flag) + a small usage demo

**Comment by TorsteinHonsi** [comment]
Thanks Lars. I've added the `// docs` flag and did a minor optimization.

**Pull request merged**
