### PR TITLE
dash/dg-standalone-demo

### PR DESCRIPTION
**Pull request by karolkolodziej**
Added two standalone DataGrid demos.

### CODE REVIEW

**Review by stitot — COMMENTED** [review]
Nice, both of them, but perhaps add demo description that speaks of performance/virtualization and grouping of headers?

**Review by sebastianbochan — APPROVED** [review]

**Review by stitot — APPROVED** [review]

**Review by ddragula — CHANGES_REQUESTED** [review]
1. Can you enable cell editing in one of the demos?
2. Since we don't have too long text with brokeable lines, it would be worth turning on `rendering.rows.strictHeights` to `true` to increase performance even more.
3. It would be good to have one of the demos custom-styled to show the possibilities in this aspect. (And also collect pain points needed for the CSS upgrade before release)

**Comment by stitot** [comment]
> 1. Can you enable cell editing in one of the demos?

In the spirit of smaller, more focused and less complex demos I would suggest a separate demo for cell editing. This demo should also showcase relevant events (less point in cell editing demo if we do not show how they can save the edited value). Could come in v3.1

> 3. It would be good to have one of the demos custom-style...

Same point as above. Separate demo for this. Could also come in v3.1, to avoid scope creep at this stage.

**Review by ddragula — APPROVED** [review]
Ok, so let's leave these 2 for v3.1 then. :)

**Pull request merged**
