### PR TITLE
Tools: Added step comparing master with PR

### PR DESCRIPTION
**Pull request by activist**
.. using the visual tests comparisons.

The github part was implemented using vanilla requests, but I just realized that we do use octokit in other tasks (I'll never get used to finding libraries with @ prefix in package.json :sweat_smile: ). I can change it if you think it would be better or if we later would experience any issues with the current implementation.

### CODE REVIEW

**Comment by activist** [comment]
--list

**Comment by activist** [comment]
-n

**Comment by activist** [comment]
-n

**Comment by activist** [comment]
--delete

**Comment by activist** [comment]
Test

**Comment by activist** [comment]
<details>
            <summary> # Visual test results - diffs found. Click to review.</summary>
                | Test name | Pixels diff |
                | --- | --- |
                | `stock/xaxis/crosshairs-xy` | 579,| `stock/xaxis/datetimelabelformats` | 579,| `stock/xaxis/events-setextremes` | 579,| `stock/xaxis/gridlinecolor` | 580,| `stock/xaxis/gridlinedashstyle` | 475,| `stock/xaxis/id` | 579,| `stock/xaxis/labels-enabled` | 579,| `stock/xaxis/labels-formatter` | 579,| `stock/yaxis/styled-resizer` | 983 |
            </details>

**Comment by activist** [comment]
test

**Comment by activist** [comment]
# Visual test results - diffs found
| Test name | Pixels diff |
| --- | --- |
| `stock/xaxis/crosshairs-xy` | 579 |
| `stock/xaxis/datetimelabelformats` | 579 |
| `stock/xaxis/events-setextremes` | 579 |
| `stock/xaxis/gridlinecolor` | 580 |
| `stock/xaxis/gridlinedashstyle` | 475 |
| `stock/xaxis/id` | 579 |
| `stock/xaxis/labels-enabled` | 579 |
| `stock/xaxis/labels-formatter` | 579 |
| `stock/yaxis/styled-resizer` | 983 |

**Comment by activist** [comment]
# Visual test results - diffs found
| Test name | Pixels diff |
| --- | --- |
| `stock/xaxis/crosshairs-xy` | 579 |
| `stock/xaxis/datetimelabelformats` | 579 |
| `stock/xaxis/events-setextremes` | 579 |
| `stock/xaxis/gridlinecolor` | 580 |
| `stock/xaxis/gridlinedashstyle` | 475 |
| `stock/xaxis/id` | 579 |
| `stock/xaxis/labels-enabled` | 579 |
| `stock/xaxis/labels-formatter` | 579 |
| `stock/yaxis/styled-resizer` | 983 |

**Comment by activist** [comment]
# Visual test results - diffs found
| Test name | Pixels diff |
| --- | --- |
| `stock/xaxis/crosshairs-xy` | 579 |
| `stock/xaxis/datetimelabelformats` | 579 |
| `stock/xaxis/events-setextremes` | 579 |
| `stock/xaxis/gridlinecolor` | 580 |
| `stock/xaxis/gridlinedashstyle` | 475 |
| `stock/xaxis/id` | 579 |
| `stock/xaxis/labels-enabled` | 579 |
| `stock/xaxis/labels-formatter` | 579 |
| `stock/yaxis/styled-resizer` | 983 |

**Comment by activist** [comment]
## Visual test results - diffs found
| Test name | Pixels diff |
| --- | --- |
| `stock/xaxis/crosshairs-xy` | 579 |
| `stock/xaxis/datetimelabelformats` | 579 |
| `stock/xaxis/events-setextremes` | 579 |
| `stock/xaxis/gridlinecolor` | 580 |
| `stock/xaxis/gridlinedashstyle` | 475 |
| `stock/xaxis/id` | 579 |
| `stock/xaxis/labels-enabled` | 579 |
| `stock/xaxis/labels-formatter` | 579 |
| `stock/yaxis/styled-resizer` | 983 |

**Comment by activist** [comment]
## Visual test results - diffs found
| Test name | Pixels diff |
| --- | --- |
| `stock/xaxis/crosshairs-xy` | 579 |
| `stock/xaxis/datetimelabelformats` | 579 |
| `stock/xaxis/events-setextremes` | 579 |
| `stock/xaxis/gridlinecolor` | 580 |
| `stock/xaxis/gridlinedashstyle` | 475 |
| `stock/xaxis/id` | 579 |
| `stock/xaxis/labels-enabled` | 579 |
| `stock/xaxis/labels-formatter` | 579 |
| `stock/yaxis/styled-resizer` | 983 |

**Comment by TorsteinHonsi** [comment]
Thanks!

> I can change it if you think it would be better or if we later would experience any issues with the current implementation.

It's no big deal, let's just keep it in mind if we encounter problems.

**Pull request merged**
