### PR TITLE
bugfix/17738-array-based-gantt-points

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed, #17738, gantt series did not support array-based points

I am a bit unsure on how much we should do with this, and if we should support additional properties. 

Right now, without keys defined, basic array-points support `x` and `x2` only.

I know that in normal HC, for a basic line-series, a an array-point is 2 values, either `[name, y]` or `[x, y]`

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207852224732173

### CODE REVIEW

**Review by hubertkozik — APPROVED** [review]
Looks correct even in this mixed data case: https://jsfiddle.net/BlackLabel/vLk05sgr/

**Review by TorsteinHonsi — COMMENTED** [review]
Thanks!

While this approach is working, I am wondering if this is the best way to do it. In general, all data options handling is usually done in the `Series` class, where the data options are parsed and data pushed into parallel arrays.

So far so good, see the `console.log`: https://jsfiddle.net/highcharts/7e4w1bhz/

It seems to me that the TreeGridAxis should use `xData` and `x2Data` instead of looking directly at `s.options.data`. Then the TreeGridAxis wouldn't have to deal with array vs object config, nor the `key` option, because all that is handled by the Series.

**Comment by MarkusBarstad** [comment]
> Thanks!
> 
> While this approach is working, I am wondering if this is the best way to do it. In general, all data options handling is usually done in the `Series` class, where the data options are parsed and data pushed into parallel arrays.
> 
> So far so good, see the `console.log`: https://jsfiddle.net/highcharts/7e4w1bhz/
> 
> It seems to me that the TreeGridAxis should use `xData` and `x2Data` instead of looking directly at `s.options.data`. Then the TreeGridAxis wouldn't have to deal with array vs object config, nor the `key` option, because all that is handled by the Series.

@TorsteinHonsi I could be wrong but after messing a bit with the code, this could require a big-ish rewrite:

- The generation of the `treeGrid` object is responsible for [setting y-values](https://github.com/highcharts/highcharts/blob/7180a490cc94d7bcb96ba6288f4ee3bf4f23397a/ts/Core/Axis/TreeGrid/TreeGridAxis.ts#L337) on all `series.options.data` belonging to the axis. Later they are passed to `series.setData`

- To set these `y`-values, it needs to know which series a point belongs to (as can be seen in the same line as `data.y` is being set).

- The functions generating `treeGrid` expects every point to be an `object` so a potential rewrite will need some new typing as well.

Any ideas on how we should proceed? 🤔

**Comment by TorsteinHonsi** [comment]
I had to think twice on this, literally, because we need a solution that works both with the current master and the upcoming DataTable refactor. So I think we should stick with the current approach, at least for now. 

However, I think we can simplify it. In the current proposal, there is inline code that deals with the point options being arrays or objects, and whether `keys` are defined. It should be possible to avoid this by first running `Point.optionsToObject` on all the options. It deals with arrays and keys and returns an object, so we should be able to keep the remaining logic as it was before this PR. Maybe even simplify it because there is some logic looking for `keys`.

**Comment by TorsteinHonsi** [comment]
@MarkusBarstad Sorry for the late reply. I have no good ideas on how do deal with that. I think we should conclude that your [first approach](https://github.com/highcharts/highcharts/pull/21610#pullrequestreview-2218696767) was the best one, and move on 👍

**Comment by MarkusBarstad** [comment]
> I think we should conclude that your [first approach](https://github.com/highcharts/highcharts/pull/21610#pullrequestreview-2218696767) was the best one, and move on 👍

Alright, @TorsteinHonsi 

That should be where we are at on last commit + a merge from master (and a minor fix which was necessary after the merge).

No failing unit-tests or demos. (the failing visual comparison is the "Chart async chart test should load within 100 attempts (10 seconds)." which has been failing on many PRs lately)

**Review by TorsteinHonsi — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
