### PR TITLE
bugfix/19872-panning-axis-min-max

### LINKED ISSUE #19872: Panning does not respect axis min/max values
#### Expected behaviour
After zooming into a chart with specified `yAxis.min` and `yAxis.max` values, the user should freely pan the chart with respecting min/max values.

#### Actual behaviour
After zooming into a chart with specified `yAxis.min` and `yAxis.max` values, panning does not respect min/max values.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/vjhzw71a/
1) Zoom into the bottom part of the points.
2) Click the shift key and pan in y direction -> yAxis.min and yAxis.max are not respected.

#### Product version
Highcharts v11.1.0

### LINKED ISSUE #20070: Panning does not respect minPadding and maxPadding
#### Expected behaviour
Panning should respect minPadding and maxPadding when set.

#### Actual behaviour
When panning and minPadding or maxPadding are set, panning range is limited to dataMin and dataMax and not allowing to pan further.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/u396h8ad/

1. Zoom in
2. Try to pan beyond dataMin and dataMax

#### Product version
Highcharts v11.2.0

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by jakubjanuchta**
Fixed #19872, added threshold, min, max, minPadding and maxPadding support for panning.
Fixed #20070

### CODE REVIEW

**Comment by TorsteinHonsi** [comment]
Thanks!

This change came out pretty extensive... I was imagining we could respect the `min` and `max` options with something like this:

```ts
                            panningState.startMin = Math.min(
                                pick(series.options.threshold, Infinity),
                                dataExtremes.dataMin,
                                panningState.startMin
                            );
                            panningState.startMax = Math.max(
                                pick(series.options.threshold, -Infinity),
                                dataExtremes.dataMax,
                                panningState.startMax
                            );
```

Changed to:

```ts
                            panningState.startMin = Math.min(
                                pick(axis.options.min, series.options.threshold, Infinity),
                                dataExtremes.dataMin,
                                panningState.startMin
                            );
                            panningState.startMax = Math.max(
                                pick(axis.options.max, series.options.threshold, -Infinity),
                                dataExtremes.dataMax,
                                panningState.startMax
                            );
```

Is all the other code about min and max padding?

**Comment by jakubjanuchta** [comment]
> Thanks!
> 
> This change came out pretty extensive... I was imagining we could respect the `min` and `max` options with something like this:
> 
> ```ts
>                             panningState.startMin = Math.min(
>                                 pick(series.options.threshold, Infinity),
>                                 dataExtremes.dataMin,
>                                 panningState.startMin
>                             );
>                             panningState.startMax = Math.max(
>                                 pick(series.options.threshold, -Infinity),
>                                 dataExtremes.dataMax,
>                                 panningState.startMax
>                             );
> ```
> 
> Changed to:
> 
> ```ts
>                             panningState.startMin = Math.min(
>                                 pick(axis.options.min, series.options.threshold, Infinity),
>                                 dataExtremes.dataMin,
>                                 panningState.startMin
>                             );
>                             panningState.startMax = Math.max(
>                                 pick(axis.options.max, series.options.threshold, -Infinity),
>                                 dataExtremes.dataMax,
>                                 panningState.startMax
>                             );
> ```
> 
> Is all the other code about min and max padding?

Yes, the logic regarding `min` and `max` is quite simple, all the other code is responsible for respecting `min/maxPadding` and I thought it was going to be a good solution to squeeze both of those in one PR as it is pretty similar logic.

**Comment by TorsteinHonsi** [comment]
Putting this on hold until https://github.com/highcharts/highcharts/pull/20077 is finished

**Comment by TorsteinHonsi** [comment]
The two issues got fixed by the Chart.transform refactor.

**Pull request closed without merging**
