### PR TITLE
Feature/9378 vertical scrollable plotarea

### LINKED ISSUE #9378: Gantt Scrollable
Is it really not possible to define a scrollable yAxis with a fixed height for gantt rows?

I can set the height of the chart, but it makes everything in the gantt chart really small, imagine having 100 rows, it would become impossible to work with....

I can also set overflow:auto; on the container div but then the label will disappear, since the labels are inside the svg I cannot make them sticky using CSS. Is the most obvious thing for a gantt chart impossible to do in highcharts or am I missing something?

### LINKED ISSUE #10768: Vertical scroll: unable to scroll on touch device
#### Expected behaviour
Default 2 finger scroll to scroll the chart and a 1 finger scroll to scroll the web site.

#### Actual behaviour
Only the arrow buttons on the ends of the scrollbar are working on a touch device.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/hsm957qg/3/show

Open on a mobile device and try to scroll page and the chart.

#### Affected devices
Tested on Android 7.0 and iPad

about scrollbar fyi: @pawelfus

### PR DESCRIPTION
**Pull request by TorsteinHonsi**
Added new feature, vertically scrollable plot area. This adds native scrolling features vertically, and is enabled using the `chart.scrollablePlotArea.minHeight` setting.

Closes #9378, closes #10768.

### CODE REVIEW

**Comment by Izothep** [comment]
I am not sure if this is the right place to mention this problem, but it looks that scrollable plotarea works differently on Highstock and Highcharts when chart is inverted. 

Highstock (correct):
https://jsfiddle.net/izothep/r365magx/3/

Highcharts: (incorrect):
https://jsfiddle.net/izothep/r365magx/4/

An image showing the issue:
Screenshot 2019-05-23 at 10 55 43

**Comment by TorsteinHonsi** [comment]
Fix coming up... Thanks!

**Comment by AntonyJos** [comment]
@TorsteinHonsi 

Sorry for barging into this conversation..

I am interested in this feature..

Is this made available for **stockChart**?

As per the documentation, i could only see it for **@product   highcharts gantt**

I am trying to do something like Scroll-able Plot Area across Y-Axis in a stock-chart (wherein multiple Y Axis exist which are not opposite to each other) , as can be seen in fiddle below:

[https://jsfiddle.net/ynfbcxzo/](url)

As per my understanding i have added the following

`    scrollablePlotArea: {
      minHeight: 200,
      scrollPositionY: 0
    }
`
Still does not seem to  make a difference...

Detailed discussion on the same could be found in the below thread:

[https://www.highcharts.com/forum/viewtopic.php?f=12&t=42023](url)

Kindly let me know if i missed out something.

**Comment by AntonyJos** [comment]
Any update on this?

**Comment by TorsteinHonsi** [comment]
It works if you set a smaller height for the chart, forcing scrollbars: https://jsfiddle.net/highcharts/1n36hxr8/. It doesn't seem to handle panes very well though.

**Comment by AntonyJos** [comment]
@TorsteinHonsi,

**Thanks** for your time..

And **Congrats** on successful up-gradation of HighChart version to 7.1.2

I Have observed that the scrollablePlotArea works fine with a single Y Axis.

But for the latest fiddle shared, i see that if highcharts-plot-background is given it gets clipped in middle... i believe it to be the poor handling of the panes.

I have posted this suggestion on uservoice

[](https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/37821970-vertical-scrollableplotarea-for-highstock-across-y)

Hope you got what i am trying to achieve..

Kindly see to this if found to be valuable.

**Comment by AntonyJos** [comment]
https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/37821970-vertical-scrollableplotarea-for-highstock-across-y

**Comment by TorsteinHonsi** [comment]
Thanks for pointing out, I didn't notice that. New issue at https://github.com/highcharts/highcharts/issues/10952.

**Comment by risingrun** [comment]
Hi there, My Expert Friends. 

I am suing HighStock Demo for woocommerce website. I am want to track product selling data in HighStock Chart. for Example it will be like this  https://stockx.com/nike-sb-blazer-low-black-white

is it possible by HighStock chart to show the product selling amount in graph? 
Regards
Untitled

**Comment by pawelfus** [comment]
Hi @risingrun 

The chart you posted is created in Highstock, so I think yes, it's possible :) If you have any questions or problems, please contact our support: https://www.highcharts.com/blog/support/ - you posted your question on our bug tracker.

**Pull request merged**
