### PR TITLE
21061 description of sort modifier missing

### PR DESCRIPTION
**Pull request by jomar-honsi**
Description added and link to [broken sample](https://github.com/highcharts/highcharts/issues/21373#issue-2366461707) removed.

### CODE REVIEW

**Review by stitot — APPROVED** [review]
I appreciate the focus on language and typos!

**Review by karolkolodziej — APPROVED** [review]
The docs are fine but I would leave the demo and fix it as soon as possible.

**Review by vazonik — CHANGES_REQUESTED** [review]
I think more information on `orderInColumn` would be useful, and preferably a link to its page in the API docs. As of now, it is still quite unclear what this option exactly does.

**Comment by jomar-honsi** [comment]
> I think more information on `orderInColumn` would be useful, and preferably a link to its page in the API docs. As of now, it is still quite unclear what this option exactly does.

The API docs for DataModifiers are not visible on the public web (separate ticket?), so for now I'll just copy the text from the TS function header.

**Comment by karolkolodziej** [comment]
@jomar-honsi check the `tools/gulptasks/dashboards/api-docs.json` file. 
There, you can add missing files to properly generate the API with `npm run dapi`

**Review by vazonik — APPROVED** [review]
Thanks!

**Review by sebastianbochan — APPROVED** [review]

**Pull request merged**
