### PR TITLE
feature/10766-tooltip-classname

### PR DESCRIPTION
**Pull request by pawelfus**
Added `tooltip.className` option for additional custom CSS class.

### CODE REVIEW

**Comment by TorsteinHonsi** [comment]
@pawelfus Looks like the CI failure is legitimate...

**Comment by pawelfus** [comment]
You're right. Interesting fact - it fails also in Chrome (browser) but somehow pre-commit tests have passed..

**Comment by pawelfus** [comment]
It looks files were not automatically built in pre-commit. It seems that running locally `npx gulp scripts-ts` does not build distribution files (highcharts.js etc), separate `npx gulp` is necessary. This is my previous log from pre-commit:

```shell
git commit -am "Fixed #10766, added \`tooltip.className\`."
husky > pre-commit (node v10.8.0)
 ✔ Running tasks for *.js
[12:38:27] Using gulpfile ~/projects/projects/highcharts/gulpfile.js
[12:38:27] Starting 'lint-ts'...
[12:38:27] Linting [ **/*.ts ]...
[12:38:42] Command finished: cd ts && npx eslint **/*.ts
[12:38:42] Finished linting
[12:38:42] Finished 'lint-ts' after 15 s
[12:38:43] Using gulpfile ~/projects/projects/highcharts/gulpfile.js
[12:38:43] Starting 'scripts'...
[12:38:44] ✓ Source code has not been modified since the last successful run.
[12:38:44] Hint: Run the `scripts-watch` task to watch the js directory.
[12:38:44] Finished 'scripts' after 801 ms
[12:38:45] Using gulpfile ~/projects/projects/highcharts/gulpfile.js
[12:38:45] Starting 'test'...
[12:38:45] Starting 'scripts'...
[12:38:46] ✓ Source code has not been modified since the last successful run.
[12:38:46] Hint: Run the `scripts-watch` task to watch the js directory.
[12:38:46] Finished 'scripts' after 785 ms
[12:38:46] Starting 'test'...
[12:38:48] Run `gulp test --help` for available options
07 06 2019 12:39:02.991:INFO [karma-server]: Karma v4.1.0 server started at http://0.0.0.0:9876/
07 06 2019 12:39:02.992:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
07 06 2019 12:39:02.999:INFO [launcher]: Starting browser ChromeHeadless
07 06 2019 12:39:03.713:INFO [HeadlessChrome 74.0.3729 (Mac OS X 10.13.6)]: Connected on socket AE7JvKl88AOA0z8yAAAA with id 45398139
HeadlessChrome 74.0.3729 (Mac OS X 10.13.6): Executed 212 of 1201 SUCCESS (0 secs / 30.778 secs)


HeadlessChrome 74.0.3729 (Mac OS X 10.13.6): Executed 412 of 1201 (skipped 1) SUCCESS (0 secs / 1 min 3.684 secs)

HeadlessChrome 74.0.3729 (Mac OS X 10.13.6): Executed 1187 of 1201 (skipped 14) SUCCESS (2 mins 25.533 secs / 2 mins 25.035 secs)
TOTAL: 1187 SUCCESS
[12:41:32] Finished 'test' after 2.77 min
[12:41:32] Finished 'test' after 2.78 min
husky > commit-msg (node v10.8.0)
Commit message is OK, proceeding.
[feature/10766-tooltip-classname 86ba92b66] Fixed #10766, added `tooltip.className`.
 4 files changed, 26 insertions(+), 6 deletions(-)
```

**Comment by pawelfus** [comment]
Failed again? Wow, that suppose to be just a 5min fix, that alergy is killing me.

**Comment by pawelfus** [comment]
Ok, this time it seems it's not my fault:

```
Error: 403 Forbidden (Rate Limit Exceeded)
```

**Pull request merged**
