### PR TITLE
bugfix/external-data-in-tests

### LINKED ISSUE #20537: Karma failed fetch for usdeur.json and aapl-ohlcv.json
1. The sample fetch reports a failure for the karma tests in here:
https://github.com/highcharts/highcharts/blob/9577bec847d1fca5982d401e1ec84a91f5bcf74c/samples/unit-tests/series/datagrouping/demo.js#L3-L5

However, the data is globally available through the `usdeur` global variable loaded defined in [samples/data/usdeur.js](https://github.com/highcharts/highcharts/blob/master/samples/data/usdeur.js) and loaded by `karma-files.json` in here: https://github.com/highcharts/highcharts/blob/9577bec847d1fca5982d401e1ec84a91f5bcf74c/test/karma-files.json#L90

Maybe the [fetch rejection](https://github.com/highcharts/highcharts/blob/9577bec847d1fca5982d401e1ec84a91f5bcf74c/test/karma-setup.js#L188-L212) could be improved with an attempt to search for a relevant global variable?

2. A similar fail (`Exception has occurred: Sample error, URL "https://cdn.jsdelivr.net/gh/highcharts/highcharts@2c6e89641888ae94c988649d96552c06c4e47351/samples/data/aapl-ohlcv.json" missing in JSONSources (trying to fetch)`)  is reported for `\samples\unit-tests\rangeselector\buttons-datagrouping\demo.js` but it seems that the relevant data set is not loaded for the karma tests.

### PR DESCRIPTION
**Pull request by bm64**
Fixed #20537, tests were using external data resources.

### CODE REVIEW

**Comment by bm64** [comment]
@TorsteinHonsi the requested changes to `resolveJSON` are ready. When it comes to data grouping tests - it seems  they have been broken for a while now, precisely since this change https://github.com/highcharts/highcharts/commit/1d170b554f9a1e58e10fc19323e34c677cb05490, and the plan was to resolve the external resources issue with this PR, create a ticket for the skipped data grouping tests, and tackle them as a separate issue, unless you think we should do differently

**Comment by pawelfus** [comment]
Added Hubert to review the test changes

**Review by hubertkozik — APPROVED** [review]
Changes to the map test are applied with my help. This test aims to check calculated, recommended map projection for Map Chart without `hc-recommended-mapview` static property (directly in map topoJSON). In headless mode it is mapped to `json-sources` topoJSON where that property is not set and that's why test worked in headless mode :)

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Review by DJTechnoo — APPROVED** [review]

**Review by pawellysy — APPROVED** [review]
LGTM

**Review by kamil-musialowski — APPROVED** [review]

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
I get 3 failing tests when I run `npm test` now...

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
It all passes now. But I still don't get why we need to `skip` those tests. The tests are there for a reason, and by skipping it we lose the protection against regressions. Can we fix the actual problem instead of skipping? Like for the map test, it could be to (temporarily?) delete the recommended mapview? All these tests pass in the master if I run the tests offline - what changed?

**Comment by pawelfus** [comment]
@TorsteinHonsi do the tests pass on your master branch? I can't speak for the maps test, but DG is broken anyway when I open it in utils:
- http://utils.highcharts.local/samples/#test/unit-tests/series/datagrouping
- http://utils.highcharts.local/samples/#test/unit-tests/maps/projection

Those tests silently fail in Karma, for example:

```
npx gulp test --tests unit-tests/series/datagrouping
```

Does not run at all:
```
[11:35:00] Run `gulp test --help` for available options
(node:6836) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
12 03 2024 11:35:01.624:INFO [framework:karma-sharding]: sharding specs across 6 browsers
12 03 2024 11:35:48.574:INFO [karma-server]: Writing browser console to file: /Users/pawelfus/Projects/highcharts/test/console.log
12 03 2024 11:35:48.577:WARN [filelist]: Pattern "/Users/pawelfus/Projects/highcharts/vendor/topojson-client.min.js" does not match any file.
12 03 2024 11:35:48.577:WARN [filelist]: Pattern "/Users/pawelfus/Projects/highcharts/vendor/rgbcolor.js" does not match any file.
12 03 2024 11:35:49.038:INFO [karma-server]: Karma v6.4.2 server started at http://localhost:9876/
12 03 2024 11:35:49.039:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
12 03 2024 11:35:49.051:INFO [launcher]: Starting browser ChromeHeadless
12 03 2024 11:35:50.174:INFO [Chrome Headless 122.0.6261.112 (Mac OS 10.15.7)]: Connected on socket oXaEyWqDvn1XlkKUAAAB with id 47597504
Chrome Headless 122.0.6261.112 (Mac OS 10.15.7): Executed 0 of 0 SUCCESS (0.007 secs / 0 secs)
TOTAL: 0 SUCCESS
```

I think skipping is fine, since we skip 1 out of 108 tests in `maps`, and 6 out of 56 tests in `DG`. The remainder of them are fine. To be on the same page: at this moment tests are skipped, meaning 0/56 is being run in DG and 6/108 in maps.

Tested with commands:
```
npx gulp test --tests unit-tests/series/datagrouping
npx gulp test --tests unit-tests/maps/projection
```

**Comment by TorsteinHonsi** [comment]
### Data grouping tests
Okay, I understand that this hasn't been running for a while, probably since [we added the async IIFE](https://github.com/highcharts/highcharts/commit/754b0cb454f354b5fc833ba677036eb7ec90147f). That probably means the the test that we now skipped, has been broken in the meantime, right? Which again means that we should find out why, because we may have introduced regressions that are not yet discovered.

### Map projection test
I re-enabled it and deleted `hc-recommended-projection` like Hubert explained. Which revealed a test leak that I fixed.

### Other
I removed the remaining local file replications in `json-sources.js` as per my [comment last week](https://github.com/highcharts/highcharts/pull/20803#pullrequestreview-1927535027).

**Comment by TorsteinHonsi** [comment]
Now awaiting tests. Especially the visual tests may be broken with the changes in `json-sources.js`.

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
