### PR TITLE
Explain how to load as ECMAScript module from CDN

### PR DESCRIPTION
**Pull request by dandv**
See #7186

### CODE REVIEW

**Comment by TorsteinHonsi** [comment]
Thanks, looks good to me. What do you think @jon-a-nygaard ?

Also, we should make the demo our own so we don't depend on jsFiddle accounts that we don't manage.

**Comment by dandv** [comment]
> Also, we should make the demo our own so we don't depend on jsFiddle accounts that we don't manage.

Good point. Feel free to change my PR.

Also a Dynamic import example would be great because it's the most interesting use of ES module imports.

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard Awaiting your review.

**Comment by TorsteinHonsi** [comment]
@jon-a-nygaard Doesn't really fit in anywhere - I suppose putting it under `highcharts/chart/....` is least counterintuitive. But it doesn't matter much as long as it is there.

**Comment by dandv** [comment]
The URL that ended up in the [ES CDN loading example](https://github.com/highcharts/highcharts#load-highcharts-from-the-cdn-as-ecmascript-modules) doesn't work:

    https://code.highcharts.com/es-modules/masters/highcharts.js

Is this intentional, so the dev would select the appropriate version, or should a working URL be used in the `import` statement?

**Comment by TorsteinHonsi** [comment]
Sorry about that, it was not intentional.

**Pull request merged**
