### PR TITLE
Bugfix/20922 skipped dg tests

### PR DESCRIPTION
**Pull request by pawellysy**
Restored and fixed skipped `DataGrouping` tests.

### CODE REVIEW

**Review by kamil-musialowski — APPROVED** [review]
Nice 👌

**Review by pawelfus — APPROVED** [review]

**Review by DJTechnoo — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Review by bm64 — APPROVED** [review]
LGTM 👍

**Review by pawelfus — APPROVED** [review]
Now it looks perfect, thanks!

Ready to merge @TorsteinHonsi

**Pull request merged**
