### PR TITLE
dash/simplified-climate-demo

### PR DESCRIPTION
**Pull request by sebastianbochan**
- [x] - remove custom handles from the navigator
- [x] - optimize KPI options
- [x] - remove light/dark mode toggle
- [x] - leave 4 KPI
- [x] - remove click from the KPI
- [x] - 3 series on the chart
- [x] - leave only 6 markers on the map
- [x] - a11y

### CODE REVIEW

**Review by Vazonik — APPROVED** [review]
LGTM

**Review by oysteinmoseng — APPROVED** [review]
Very nice! I was going to suggest to keep the original so we could still test against it and use it for the 97% goal, but actually this one is still quite complex, so it should be enough as is, and we can still keep trying to simplify it.

**Comment by sebastianbochan** [comment]
@oysteinmoseng 
The "full" demo is also available, but in the other directory. 

https://github.com/highcharts/highcharts/pull/19933

**Review by marvin19 — CHANGES_REQUESTED** [review]
@sebastianbochan See Slack for comments

**Review by marvin19 — APPROVED** [review]

**Pull request merged**
