### PR TITLE
bugfix/9988-stocktools-popup-scroll

### PR DESCRIPTION
**Pull request by sebastianbochan**

### CODE REVIEW

**Comment by sebastianbochan** [comment]
Alternatively we can enable scrollbar on the whole popup by CSS:

```
.highcharts-popup {
  overflow-x: hidden;
  overflow-y: scroll;
}
```

Is it better solution?

**Comment by TorsteinHonsi** [comment]
Yes if that gives the desired result it would be better.

**Comment by TorsteinHonsi** [comment]
What's the status here @sebastianbochan ?

**Comment by sebastianbochan** [comment]
Will do commit today.

**Pull request merged**
