### PR TITLE
Docs: Made Point.graphic(s) properties public.

### LINKED ISSUE #15769: graphic type not defined?
#### Expected behaviour
No typescript error when accessing `Point.graphic`

```js
plotOptions: {
      point: {
        events: {
          mouseOver: function (this: Highcharts.Point) {
            this.graphic.attr({  // <------- error here
              fill: this.y < 0 ? "red" : "blue"
            });
          }
        }
      }
    }
```

#### Actual behaviour
Typescript error.
image

#### Live demo with steps to reproduce
https://codesandbox.io/s/focused-pond-9l84x?file=/src/Chart.tsx

#### Product version
9.1.0
React-official .3.0.0

### PR DESCRIPTION
**Pull request by bre1470**
Fixed #15769

### CODE REVIEW

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Comment by ramon-villain** [comment]
@bre1470 do you have an ETA for when this will be released? I checked `10.3.1` and the type is still not there. 
Thanks in advance

**Comment by bre1470** [comment]
Hello @ramon-villain!
Thank you for the question. The changes seem to not work and need a follow-up fix.

**Comment by bre1470** [comment]
As the fix is now part of the main branch, it will be solved with the next release this year.

**Pull request merged**
