### PR TITLE
bugfix/21429-multiple-solidgauge-rounded-off-center

### LINKED ISSUE #21429: Multiple KPI Gauge loses shape when values approach maxima
### Description

The multiple KPI gauge loses its shape when one or more values approach at least 98% of the maximum value per band.

#### Expected behaviour

It is expected that when the value of a multiple KPI band is at or above the maximum configured value, that it creates a uniform full gauge as in the image.

Screenshot from 2024-07-01 09-14-06

#### Actual behaviour

What actually happens is that the graph will lose its shape when the values get close to and become bigger than the maximum configured value per band.

Screenshot from 2024-07-01 09-22-32

##### Live demos

In this minimal fiddle below, which follows the official instructions on how to create a multiple KPI chart, you can see a very slight descrepency in the distances between the bands of the multiple KPI.
https://jsfiddle.net/bc9d0rm7/

In this slightly more involved example which provides a button to toggle the issue occurring in the Highcharts-React-Official wrapper, the issue is shown slightly more clearly when you click the button to increase the values close to their maxima.
https://stackblitz.com/edit/vitejs-vite-c6xser?file=src%2FGraph.tsx

##### Steps to reproduce

1. Create multiple KPI chart from the instructions here: https://www.highcharts.com/demo/highcharts/gauge-multiple-kpi
2. Set a series `y` value equal to or greater than 98% of the configured y-axis maximum.

#### Product version
highcharts: 11.4.0
highcharts-react-official: 3.2.1

#### Affected browser(s)

Firefox and Chrome at least.

### PR DESCRIPTION
**Pull request by hubertkozik**
Fixed #21429, the rounded solid gauge series was misaligned when close to 100%.

---
It seems to me, that division by radius to calculate proximity should not be used when border-radius is applied.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207713445159926

### CODE REVIEW

**Comment by hubertkozik** [comment]
There are 98 visual differences, but for me, it looks correct, it's just a few pixels for rounded arcs. TBD is it ok during the review?

**Review by bre1470 — APPROVED** [review]
Looks good! 👍

**Review by MarkusBarstad — APPROVED** [review]
LGTM!

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks! 

I agree that the diffs are acceptable, but I think it's something we should check first. The whole proximity concepts should only apply to full circles, as explained in the comment. Therefore it shouldn't apply at all to the majority of the cases in the diffs, which are regular pie slices with less than full circle sectors. 

So I think on line 65, the the end should only be corrected for proximity if `fullCircle` is true, otherwise not.

We may still get diffs in the pie slices though, because the proximity was subtracted in the previous version. But I think if we do this, it will be more correct for the future. 

Can you test that?

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
