### PR TITLE
docs/15085-stock-images

### LINKED ISSUE #15085: Docs [Stock]: Replace old images with new ones
List of URL's with images to be added/updated:

- https://www.highcharts.com/docs/stock/understanding-highcharts-stock (use this: https://www.highcharts.com/demo/stock/stock-tools-gui + add StockTools GUI arrow)
- Add an image of StockTools (like in the URL above) at the beginning of the article: https://www.highcharts.com/docs/stock/stock-tools
- https://www.highcharts.com/docs/stock/candlestick-chart
- Add an image of the DataGrouping in action: https://www.highcharts.com/docs/stock/data-grouping
- https://www.highcharts.com/docs/stock/flag-series
- https://www.highcharts.com/docs/stock/navigator
- https://www.highcharts.com/docs/stock/ohlc-chart
- https://www.highcharts.com/docs/stock/range-selector

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed #15085, replaced old stock images.

### CODE REVIEW

**Review by pawelfus — CHANGES_REQUESTED** [review]
In `understanding_highstock.png` please annotate Stock Tools too

**Review by raf18seb — APPROVED** [review]
Nice, I like that almost all the images have the same width and height.

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by pawellysy — APPROVED** [review]
Looks good!

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
