### PR TITLE
bugfix/21684-tooltip-outside-not-getting-themes

### LINKED ISSUE #21684: `tooltip.outside = true` does not respect the chart theme
#### Expected behaviour
If we have a chart in a dark theme, with a `highcharts-dark` class attached and we have a tooltip, we would expect this tooltip to also be in dark theme by default (with the `highcharts-dark`) class - which is currently not the case if `tooltip.outside` is set to true.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/tngq2cf3/
1. Turn on light mode on your laptop (by default `prefers-color-scheme` seems to be used).
2. Hover over a point and see the tooltip

Screenshot 2024-08-20 at 10 59 25

#### Product version
Highcharts 11.4.7

#### Affected browser(s)
All?

### PR DESCRIPTION
**Pull request by MarkusBarstad**
Fixed #21684, tooltip with `outside` did not receive css themes assigned to `container`.

WARNING: 
In the unit test for this it was necessary to give a class to 'container'/'renderTo'. 

I did this by accessing the div via `document.getElementById`. 

Not sure if this is a test-friendly thing to do. Are there better ways?

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208100489805551

### CODE REVIEW

**Review by KacperMadej — APPROVED** [review]

**Review by KacperMadej — APPROVED** [review]

**Comment by TorsteinHonsi** [comment]
Sorry I didn't catch this earlier, but I think we shouldn't simply apply the `renderTo`'s class name to the tooltip container. We can't control over what it brings with it, and it is likely that the container itself has style attached that isn't intended for Highcharts:
* https://jsfiddle.net/highcharts/25rmk1t4/
* https://jsfiddle.net/highcharts/25rmk1t4/1

I'm not quite sure what we should do about it. The tooltip container is added to the body itself, so any CSS class would have to be applied to the body to take effect, or alternatively be passed as the `tooltip.className` option: https://jsfiddle.net/highcharts/mjkztwgh/

We could experiment with appending the container directly to `chart.renderTo` or `chart.container` though. If so, the position would have to be offset by `chartPosition`, and we would likely run into problems with the [overflow setting](https://github.com/highcharts/highcharts/blob/1982b6a71d443990630e69f278f91a6bd36fa81c/ts/Core/Chart/Chart.ts#L1581-L1591).

Alternatively, we would need to improve the docs.

**Comment by MarkusBarstad** [comment]
@TorsteinHonsi , 
At first when I set `renderTo` as parent, tests complained about x/y position and overflowing of the viewport, but now I simply tried it once more to document the failing tests, and they all pass 🤔 

So last commit could possibly a bit dodgy but everything looks ok so far: https://jsfiddle.net/mkb93/bLwt2xce/33/

Note, I have not tried this with many options yet

**Review by TorsteinHonsi — COMMENTED** [review]
That's a pleasant surprise! Apparently a `position: absolute` element doesn't get clipped when by the parent's `overflow:hidden`: https://jsfiddle.net/highcharts/6v5pjcer/

There's one thing I don't understand though. How come the position of the tooltip is still correct? I would expect that we had to rewrite the positioning now that we append it to the `renderTo` instead of the body... But it does look correct even when we offset the container: https://jsfiddle.net/highcharts/c6fjLyqt/ . Can you just double check the positioning logic itself?

**Comment by MarkusBarstad** [comment]
@TorsteinHonsi Will do!

I have arrived at an hypothesis of why the position remains the same, regardless of where tooltip's container resides in the DOM.

### An `"outside"` Tooltip's container:
1. #### Is not used for calculations in `Tooltip.getPosition` and `Tooltip.updatePosition`.
    -   Instead those functions use: 
          - The relevant point,
          - Chart's position, returned by `Pointer.getChartPosition`
    -   `Pointer.getChartPosition` returns a charts position within `renderTo`
          - So tooltip gets same offsets as the chart (like the margins in your fiddle)
3. #### Has `position: absolute`.
    - Any sibling(s), like `Chart.container`, does not impact its position. 
4. #### Gets `left` / `top` values from its label: 
    - `xSetter`/`ySetter` functions are wrapped
    - They also set `Tooltip.container's` `left` / `top` to their new `x` / `y` values.

Thus we see that they render the same, regardless of the parent.

**Comment by TorsteinHonsi** [comment]
Okay, thanks for checking! No 2 means we can break it by setting `position: relative` to the `renderTo`: https://jsfiddle.net/highcharts/c6fjLyqt/1/

I _think_ that means that we should append the tooltip to `chart.container` instead of `chart.renderTo`, because `container` always has `position: relative`, which makes the positioning predictable. But also means the position is no longer relative to `Pointer.getChartPosition`.

**Comment by MarkusBarstad** [comment]
@TorsteinHonsi 

I had some challenges making positioning work when putting the tooltip's container. Inside of the chart container. Scrolling and `split` where some of the scenarios which did not play well with this.

A simpler solution to the users issue could be to append any Highcharts-specific CSS-classes supplied, to the tooltip's container as well using regex:
https://jsfiddle.net/mkb93/3j2Lzo4v/17/

Demo of the regex used: https://jsfiddle.net/mkb93/uvtzL1aq/6/

**Comment by TorsteinHonsi** [comment]
Hmm. This would solve the exact scenario in the main issue (`.highcharts-xxx` on the container), but won't solve other scenarios with class names further up the hierarchy or in other patterns.

> I had some challenges making positioning work when putting the tooltip's container inside of the chart container. Scrolling and split where some of the scenarios which did not play well with this.

I think the relevant code is in `Tooltip.getPosition`: 

https://github.com/highcharts/highcharts/blob/6fbdd206f9839e4baca9ba1895198590cadc5870/ts/Core/Tooltip.ts#L633-L651

When `outside`, the position is corrected for `chartPosition`. Did you try to change that part?

**Comment by MarkusBarstad** [comment]
> When `outside`, the position is corrected for `chartPosition`. Did you try to change that part?

I don't think so, thanks for the tip! @TorsteinHonsi

**Comment by MarkusBarstad** [comment]
@TorsteinHonsi 
Alright so making up for chart position worked!

Everything seems ok now, but some things to note: 

1. The tooltip-container is in chart-container _except_ when scrolling. 
    - Then it becomes a child of the scrolling wrapper container.
    - Previously tooltip-container did not scroll, so this plays easily with existing logic

2. A [change to an existing unit-test ](https://github.com/highcharts/highcharts/blob/ff4fb0b594bcd8b987a76a3e03b84aed109fe058/samples/unit-tests/tooltip/split/demo.js#L302)(unsure about this 🤔)
    - In headless, `getBoundingClientRect` reports too big of a `right` value for `series.tt.element`.
    - In the browser the tooltip does *not* spill over, even given the same dimensions as the headless test. 
    - Therefore I changed a `strictEqual` to a `close` for that single case.

**Comment by TorsteinHonsi** [comment]
Thanks! Maybe I'm missing something, but it seems like two problems persist. See https://jsfiddle.net/highcharts/51xsehz2/ . 
1. The tooltip position is off
2. For the rightmost point, the tooltip is clipped to the container. Which is a bit surprising because we discovered that it [shouldn't happen](https://github.com/highcharts/highcharts/pull/21695#pullrequestreview-2292935894)?

**Comment by MarkusBarstad** [comment]
> 1. The tooltip position is off
> 2. For the rightmost point, the tooltip is clipped to the container.
@TorsteinHonsi True! I should have checked my commit better, fixing one thing broke another 😬

**Regarding the clipped** `tooltip`:
We wish to move `tooltip.container` into `chart.container`. But `chart.container` usually/(always?) has `overflow: hidden;` 

How we should solve this? 🤔
- Only apply `overflow: hidden` when not `tooltip.outside`?
- Additional wrapper, wide as viewport for `chart` & `tooltip`?
- Alter `chart.container` and use `overflow: hidden` only on elements which need it?

**Regarding positioning bugs**:
Seems resolved as far as I can tell (but could be tests I have not thought of):
- margins: https://jsfiddle.net/mkb93/zwbgfn6a/
- scrolling: https://jsfiddle.net/mkb93/qwmbzug9/
- floated container: https://jsfiddle.net/mkb93/sLwadbe4/

**Comment by TorsteinHonsi** [comment]
> We wish to move tooltip.container into chart.container. But chart.container usually (or always?) has `overflow: hidden`;

Altering the overflow setting of the container is dangerous. But why did this work in an earlier stage of your PR? You did append the tooltip in the container, and it wasn't clipped. See https://github.com/highcharts/highcharts/pull/21695#pullrequestreview-2292935894.

**Comment by MarkusBarstad** [comment]
> But why did this work in an earlier stage of your PR? You did append the tooltip in the container, and it wasn't clipped.

@TorsteinHonsi 
The `tooltip.container` was appended to `chart.renderTo`, not `chart.container` back then: https://github.com/highcharts/highcharts/pull/21695/commits/3e62dce5ea6928a1b20fc8829d9ec397cbebb3b7

Not sure if it is a viable option but if we don't set `position` on `chart.container` it will render the tooltip unclipped: https://jsfiddle.net/mkb93/jpu3tksh/

This breaks scrolling (on this branch) but should not be too hard to fix.

**Comment by TorsteinHonsi** [comment]
> The tooltip.container was appended to `chart.renderTo`, not `chart.container` back then.

Ok, I see. I expect us to run into problem with responsive designs if we remove the `position: relative` on the container. Which means we're back to trying with adding the tooltip to the `renderTo` directly? In that case we need logic for positioning that can handle static, absolute or relative position on any parent element :/ . The position of the tooltip would be relative to the first parent with either relative or absolute position, right? This is getting complicated. And if the user sets `position: relative` on the `renderTo`, we're back to clipped tooltips. I'm tempted to going back to the limited solution of just copying over `highcharts-*` classes...

**Comment by MarkusBarstad** [comment]
> > The tooltip.container was appended to `chart.renderTo`, not `chart.container` back then.
> 
> Ok, I see. I expect us to run into problem with responsive designs if we remove the `position: relative` on the container. Which means we're back to trying with adding the tooltip to the `renderTo` directly? In that case we need logic for positioning that can handle static, absolute or relative position on any parent element :/ . The position of the tooltip would be relative to the first parent with either relative or absolute position, right? This is getting complicated. And if the user sets `position: relative` on the `renderTo`, we're back to clipped tooltips. I'm tempted to going back to the limited solution of just copying over `highcharts-*` classes...

Yes, @TorsteinHonsi , it indeed sounds tough and constly to accomodate all usecases here! 😬

I have reverted the branch to the regex fix, maybe the DOCs should mention this behavior? 🤔

**Comment by TorsteinHonsi** [comment]
Yes, I think it should be mentioned under `tooltip.outside`.

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
