### PR TITLE
CI: Workflow for milestone assignment

### PR DESCRIPTION
**Pull request by bre1470**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207714989513433

### CODE REVIEW

**Comment by bre1470** [comment]
The one thing I do not like about the action is that it runs with `node12`. So maybe we should refactor it to a script another day.

**Comment by goransle** [comment]
> The one thing I do not like about the action is that it runs with `node12`. So maybe we should refactor it to a script another day.

I think it potentially could be done with the github CLI, which should be preinstalled in the gh action image. From the CLI help text: 

```sh
gh pr edit 23 --milestone "Version 1"
```

**Comment by bre1470** [comment]
The GraphQL API for `gh` CLI needs `'read:org'` to work. Waiting for permission...

**Review by sebastianbochan — APPROVED** [review]

**Comment by bre1470** [comment]
It is extremely difficult to assign permission, so we have to find something else.

**Pull request closed without merging**
