### PR TITLE
docs/data-table-namespace

### PR DESCRIPTION
**Pull request by karolkolodziej**
Improved DataTable documentation.

### CODE REVIEW

**Review by stitot — COMMENTED** [review]
Thanks. Looking at "3. Manually" in the same article: we should include namespace there as well.

**Review by sebastianbochan — CHANGES_REQUESTED** [review]
I'm confused because in some tests we use `new DataTable` imported from DataGrid, so I suggest unifying it as well.
The same problem appears in the `strava demo`.

**Comment by karolkolodziej** [comment]
DataTable is added to the Dashboards and the DataGrid bundle and sometimes we only have demos/tests with DataGrid that is why we import it from here.
I've clarified it in the docs.

**Comment by sebastianbochan** [comment]
I agree that clarified version should be enough.

**Review by stitot — APPROVED** [review]

**Pull request merged**
