### PR TITLE
enhancement/shadows-inside-series

### PR DESCRIPTION
**Pull request by wchmiel**
Added shadows inside series.

### CODE REVIEW

**Comment by TorsteinHonsi** [comment]
What does this PR do? Is it an answer to an issue? Or is it a new option? Where can we see the effect, should it have a visual sample?

**Comment by TorsteinHonsi** [comment]
Demo: http://jsfiddle.net/highcharts/zsy5ojnq/

Personally I'm not sure this feature is worth the bloat... Maybe it's better off as a plugin.

**Comment by wchmiel** [comment]
Oh sorry, I forgot to add an additional comment.

It was a ticket that I've made on support. The client was asking how to add shadows inside a bar series something like CSS box-shadow inset. I thought it will be a good idea to add this feature. Of course, I can make it work better and add a visual sample, etc. but first I wanted you to see it and decide if it makes any sense for you. A plugin can be a good idea.

**Comment by TorsteinHonsi** [comment]
Thanks! Yes I think we go for a plugin in this case, as it is not a commonly requested feature.

**Pull request closed without merging**
