### PR TITLE
Tools: More workflows

### PR DESCRIPTION
**Pull request by bre1470**
- [x] Added two new workflows to save time
- [x] [Add secrets for browserstack environment](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment) (name: `browserstack`)
- [x] [Hardening permissions](https://github.com/highcharts/highcharts/pull/17754)
- [x] Fixed browser-specific workflows

### CODE REVIEW

**Comment by TorsteinHonsi** [comment]
Is it ready to merge, or should I wait for the final checkbox in the to do list?

**Comment by bre1470** [comment]
Please wait. We need the environment variables first, in case the workflows gets triggered. You can merge the PR about workflow permissions in the meantime.

**Comment by TorsteinHonsi** [comment]
_Note to self_: Awaiting further directions.

**Review by cvasseng — APPROVED** [review]
This looks good as far as I can tell. 

I've checked the Karma setup as well to make sure the correct stuff is set in the `browserstack` env on GH also, and it looks ok. :)

**Comment by bre1470** [comment]
Thank you! 😄

**Comment by cvasseng** [comment]
@TorsteinHonsi I think this one is ready.

**Pull request merged**
