### PR TITLE
Docs: Improved API to support URL history.

### PR DESCRIPTION
**Pull request by bre1470**
This only works online and locally with something like `python3 -m http.server -b 127.0.0.1` because of iframe CORS.

How to test on MacOS:
- `npx gulp dashboards/api-docs`
- `python3 -m http.server -b 127.0.0.1`
- `open http://127.0.0.1:8000/build/api/dashboards/index.html`

### CODE REVIEW

**Review by karolkolodziej — APPROVED** [review]
Perhaps it's worth mentioning the Python server somewhere in the `CONTRIBUTING.md` file?

**Comment by bre1470** [comment]
It is not like it is breaking, when opened via `file://`. Just the outer frame hash history gets not updated because of cross-origin restrictions.

**Review by pawelfus — COMMENTED** [review]
Thanks!

Can we store the hash too? For example:

- visit page: http://127.0.0.1:8000/build/api/dashboards/index.html#interfaces/Extensions_DashboardPlugins_HighchartsComponent.HighchartsComponent.Options
- click `cell` option
- result: url is missing `#cell`

**Review by pawelfus — APPROVED** [review]
Thanks!

**Pull request merged**
