### PR TITLE
Add support for composer

### PR DESCRIPTION
**Pull request by alloylab**
Also need to setup account on https://packagist.org/

### CODE REVIEW

**Comment by oysteinmoseng** [comment]
Thank you for the PR! We'll review it as soon as possible.

**Comment by pavarnos** [comment]
yes please! any progress with this?

**Comment by TorsteinHonsi** [comment]
Sorry for not following up. This is the working repo for Highcharts, and we don't publish the release build here. Our official channel for npm, bower etc is https://github.com/highcharts/highcharts-dist, so that is where composer should look too.

**Comment by pavarnos** [comment]
thanks. realised this about half an hour ago. For those who follow: a solution is 
```
composer require fxp/composer-asset-plugin
composer require bower-asset/highcharts
```
which loads the highcharts-dist repo as a composer compatible package. The files are installed in vendor/bower-asset/highcharts

**Pull request closed without merging**
