### PR TITLE
bugfix/12566-data-module-null-points

### LINKED ISSUE #12556: Inverted not working on live chart
#### Expected behaviour
The Y axis is supposed to invert with the X axis on the option inverted: false/true

#### Actual behaviour
Doesnt work with live charts

#### Live demo with steps to reproduce
https://jsfiddle.net/ascnhf12/10/
put the inverted option to true and false.

#### Product version
Highcharts,  Latest version

#### Affected browser(s)
Firefox, Chrome

### LINKED ISSUE #12566: Data module parses absent points to undefined instead of null.
#### Expected behaviour
I expect to get `null` point when I provide data in a table without a corresponding `<td></td>` tag.

#### Actual behaviour
I get `undefined` point.

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/nbjurf5y

#### Product version
Highcharts 7.2.1

### PR DESCRIPTION
**Pull request by mateuszkornecki**
Fixed #12566, now, in data module, empty points are beeing parsed to null instead of undefined.

### CODE REVIEW

**Comment by mateuszkornecki** [comment]
Because of a new code editor, I had some errors with indentations and needed to change them to spaces. Now I can see that it didn't work well. Should I fix it and commit again?

**Comment by TorsteinHonsi** [comment]
Also, it seems like the issue reference is wrong... This PR doesn't really relate to #12556, does it?

**Comment by mateuszkornecki** [comment]
> Also, it seems like the issue reference is wrong... This PR doesn't really relate to #12556, does it?

Yes, you are right. The correct ticket number should be #12566. Should I create a new branch and push everything again or can I just make another commit with the correct ticket number (it is wrong just in the commit name)?

**Comment by TorsteinHonsi** [comment]
It is sufficient to change it in the PR description.

**Comment by mateuszkornecki** [comment]
All changes have been completed.

**Comment by mateuszkornecki** [comment]
Because of the problem with CircleCI tests and differences with the actual master, created new pull request here: https://github.com/highcharts/highcharts/pull/12865

**Pull request closed without merging**
