### PR TITLE
bugfix/2667-area-series-legend-symbol

### LINKED ISSUE #2667: Area legend should display area transparency
The Area legend displays the series color and transparency. But the user will recognize the area by the area color/transparency, not by the line color. We even use area charts where the series only differ in transparency,where the current legend is of no use at all.

See http://jsfiddle.net/kNLL4/2/

Possible overlap with issue 1982

### PR DESCRIPTION
**Pull request by pawellysy**
Fixed #2667, legend item of area series didn't apply the opacity property.

### CODE REVIEW

**Review by KacperMadej — APPROVED** [review]
👍

**Comment by TorsteinHonsi** [comment]
I'm not 100% sure this is a good idea. Area charts are sometimes used with a very transparent fill. Like [in this case](https://jsfiddle.net/highcharts/udwxp1ya/), where it would better to use the color of the graphs and markers, not the fill.

It could be that we should make the legend symbol an option. Currently we have two methods in LegendSymbol; `drawRectangle` (which is by default a circle because of the `legend.symbolRadius` setting). What we could do is to refactor this so that we have a series-level `drawLegendSymbol` function that calls either of these functions based on a `series.legendSymbol` option. If so, we need to rename the functions to something more generic, like `lineMarker` and `simple`. 

```ts
public drawLegendSymbol(): void {
    LegendSymbol[this.options.legendSymbol].call(this);
}
```

@KacperMadej , @pawellysy , @pawelfus what do you think?

**Comment by pawelfus** [comment]
> what do you think?

+1 
It will not only keep the old charts without changes but also give better flexibility to the designers. Unless we want this for all series (e.g. column or pie?), I would start with these types:
- area
- areaspline
- arearange
- areasplinerange
- streamgraph
- polygon

**Comment by KacperMadej** [comment]
+1

and https://github.com/highcharts/highcharts/issues/15159 was planned as a separate issue but in case of considering refactor it should be included in the discussion IMHO

**Comment by TorsteinHonsi** [comment]
Ok @pawellysy then we pivot this PR into a small refactor, introducing the new `legendSymbol` option like described above. 

> and #15159 was planned as a separate issue but in case of considering refactor it should be included in the discussion IMHO

I think we should leave that out of this PR. The suggested refactoring in this case is more like moving code around, so it would be easier to keep track of changes if we keep the scope down.

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Ok @pawellysy then we pivot this PR into a small refactor, introducing the new `legendSymbol` option like described above. 

> and #15159 was planned as a separate issue but in case of considering refactor it should be included in the discussion IMHO

I think we should leave that out of this PR. The suggested refactoring in this case is more like moving code around, so it would be easier to keep track of changes if we keep the scope down.

**Pull request closed without merging**
