### PR TITLE
bugfix/20482-crosshair-cut-off

### LINKED ISSUE #20482: highchart stock chart yAxis crosshair label is not fully displayed in mobile terminal
#### Expected behaviour

It is desirable to provide a property that sets the offset of the reticle

For example
```js
 yAxis: {
        opposite: false,
        crosshair: {
          label: {
            enabled: true,
            style: {
              fontSize: "0.55467rem"
            }
          },
         offset:10
        },
}
```

#### Actual behaviour

Do not know what method can be used to set its offset conveniently and quickly, so as to solve the problem of being covered

#### Product version
11.3.0

#### Example figure
image

### PR DESCRIPTION
**Pull request by pawellysy**
Fixed #20482,  crosshair's label was cut off in certain label config.

### CODE REVIEW

**Review by kamil-musialowski — APPROVED** [review]
Nice!

**Review by DJTechnoo — APPROVED** [review]
LGTM!

**Review by bm64 — APPROVED** [review]

**Review by pawelfus — APPROVED** [review]
Nice catch! Thanks

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
