### PR TITLE
dash/dg2-keyboard-navigation

### PR DESCRIPTION
**Pull request by ddragula**
Implemented keyboard navigation between cells.

---
TODO:
- [x] Add custom keyboard navigation between cells.
- [x] Add sorting & editing using the keyboard.
- [x] Add navigation to cells using tab when outside the DataGrid scope.
- [x] Check if all doclets are written correctly.
- [x] Add tests.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208383027272114

### CODE REVIEW

**Review by karolkolodziej — CHANGES_REQUESTED** [review]
A few things I see, I'm not sure if this can be solved in this PR but:
1. When VoiceOver enable I'm not able to edit cells
2. When we reach the end of the row, shouldn't it go to the first element of the next row?
3. Should we add any events on focus/editing? They are with the mouse but I don't see them when navigating with the keyboard.

**Comment by ddragula** [comment]
Thanks for the review, @karolkolodziej.

> 1. When VoiceOver enable I'm not able to edit cells

Are you sure you tested it on the demo with editable cells enabled? Everything works for me with voice-over on too

> 2. When we reach the end of the row, shouldn't it go to the first element of the next row?

I followed [this](https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/data-grids/) and the navigation in Google Sheets and nothing like that happens there. I don't know if that wouldn't cause more confusion, but I'd wait for @marvin19's opinion.

> 3. Should we add any events on focus/editing? They are with the mouse but I don't see them when navigating with the keyboard.

We have events on `afterEdit` and `afterSorting` which are also called by keyboard navigation. I think adding callback options for each event listener is pointless and will mess up the API. Users can hook into methods that handle events.

**Review by stitot — COMMENTED** [review]
Great work! Just two things I notice, and perhaps not relevant.

When table is in iframe (e.g. http://localhost:3030/samples/#view/data-grid/basic/cell-events) it is not 100% focused, in that left/right arrow navigates the samples menu, not the table. Up/down works fine. Could also be an issue with the sampleviewer itself? Anyways, perhaps something to keep in mind when it comes to https://www.highcharts.com/demo/.

Observe scroll behavior when using arrows to navigate down/up in iframe vs non-iframe (http://192.168.10.78:3030/samples/#view/data-grid/basic/scroll-to-row vs http://192.168.10.78:3030/samples/view?path=data-grid/basic/scroll-to-row)

When not in iframe tbody is centered when you reach the end of the viewport, while in iframe it is not (last visible row stays at the bottom when using down arrow).

Both are fine from my perspective, but the difference in behaviour could perhaps, maybe, potentially be a symptom of some underlying weakness in logic? Don't know, and probably not something we should spend too much time on, unless you see some issues I don't.

**Comment by ddragula** [comment]
> Same problem as @karolkolodziej , I'm not able to do edit cells by using only VO-keys (control + option + arrow left/right and control + option + space bar to select), but if I use the tab key too I am able to edit the cells (which we do not want to). So it is not working as expected.

I did some research and still couldn’t find a clear answer on what I should do. The issue is that the VO-interaction triggers a `click` event, not a `dblclick` or `enter keydown`. Unfortunately, the browser doesn’t offer a way to differentiate whether the `click` was triggered by the user with a mouse click or by VoiceOver. Therefore, I can think of two alternative solutions:

1. Trigger cell editing on a single click instead of a double click, but this carries the risk of accidental edits and combining focus and editing in one action.
2. Keep editing on double click and Enter, while VO-interaction will only set the focus on the cell, and the user would still need to press Enter to edit it.

Any suggestions? @stitot @marvin19 @karolkolodziej

**Comment by stitot** [comment]
> Any suggestions? @stitot @marvin19 @karolkolodziej

I'm no a11y guru, but from a strictly technical perspective, and possibly not a  solution to anything:

Does it help to "mimic" a `dblclick` by using two `click` events with a timeout on the first?

**Comment by ddragula** [comment]
>Does it help to "mimic" a dblclick by using two click events with a timeout on the first?

Unfortunately, no, "mimicking" a double-click using two consecutive click events with a timeout doesn’t work here. The issue is that the VoiceOver interaction (`Control + Option + Space`) triggers a `click` event, but **doesn’t** simulate a `dblclick`. Ideally, a single click triggered by VoiceOver would enable editing, while a mouse-triggered click would only activate editing with a double-click.

The challenge is that the `click` event object doesn't distinguish between a click triggered by the mouse or by VoiceOver; all event parameters look the same. Additionally, VoiceOver also triggers `mousedown` and `mouseup` events, so even using flags to simulate the distinction doesn’t work. This leaves us with the two non-ideal solutions I mentioned before.

**Comment by stitot** [comment]
Hm, I see. Then I suggest to implement solution #2 now, before the test, and see how it goes. Unless @marvin19 thinks otherwise.

**Comment by karolkolodziej** [comment]
Taking everything into consideration, approach nr 2 sounds fine!

**Comment by ddragula** [comment]
I need approvals to make @sebastianbochan able to merge this. We'll do the rest of the accessibility in separate PRs. Thanks!

**Review by stitot — APPROVED** [review]

**Review by sebastianbochan — APPROVED** [review]

**Comment by sebastianbochan** [comment]
Looks good to me!

**Review by marvin19 — APPROVED** [review]

**Review by karolkolodziej — APPROVED** [review]

**Pull request merged**
