### PR TITLE
enhancement/5526-pie-zero-data-refactored

### PR DESCRIPTION
**Pull request by kamilkulig**
Added empty pie graphic: if total sum of all visible points is 0 then the chart is represented as an empty circle (#5526).

### CODE REVIEW

**Comment by TorsteinHonsi** [comment]
Looking good now!

After a quick discussion, we decided to simplify the API a bit. We can get rid of the `emptySeries` options structure be using existing `color` and `fillColor` properties for the circle. So the remaining work is:

* Apply the `color`, simply use `series.color` from the instance. This would be a good default and respond to theming. Usually it will be the same color as the first slice.
* Apply the `fillColor` option. This is currently available in area series, now it gets a new meaning in empty pie charts. It should be `undefined` by default in pies.
* Add doclets for both, explaining when they apply.

**Comment by TorsteinHonsi** [comment]
@kamilkulig Can you make the final changes?

**Comment by bre1470** [comment]
@kamilkulig This should get updated and merged asap, because I start now migrating series to TypeScript.

**Comment by bre1470** [comment]
@TorsteinHonsi Please review changes of handling series options `colors`, `color`, and new `fillColor`.

**Comment by bre1470** [comment]
@TorsteinHonsi `series.supportingColor` is also something new, but seems to be an internal option only.

**Pull request merged**
