### PR TITLE
Tools: Removed discontinued dtslint.

### PR DESCRIPTION
**Pull request by bre1470**

### CODE REVIEW

**Review by goransle — COMMENTED** [review]
Are both `lint-dts` and `jsdoc-namespace` supposed to fail now? Or

<details>

<summary> Output </summary>

```sh
➜  highcharts git:(tools/lint-dts) npx gulp lint-dts
[09:00:59] Using gulpfile ~/hs/highcharts/gulpfile.js
[09:00:59] Starting 'lint-dts'...
[09:00:59] Linting TypeScript declarations (.d.ts) for highcharts ...
test/typescript-dts/classes/Axis.ts(1,29): error TS7016: Could not find a declaration file for module 'highcharts'. '/Users/goranslettemark/hs/highcharts/code/hig
hcharts.js' implicitly has an 'any' type.
test/typescript-dts/classes/Chart.ts(1,29): error TS7016: Could not find a declaration file for module 'highcharts'. '/Users/goranslettemark/hs/highcharts/code/hi
ghcharts.js' implicitly has an 'any' type.
test/typescript-dts/classes/Chart.ts(14,19): error TS7006: Parameter 'chart' implicitly has an 'any' type.
test/typescript-dts/classes/Chart.ts(21,19): error TS7006: Parameter 'chart' implicitly has an 'any' type.
test/typescript-dts/classes/Series.ts(1,29): error TS7016: Could not find a declaration file for module 'highcharts'. '/Users/goranslettemark/hs/highcharts/code/h
ighcharts.js' implicitly has an 'any' type.
test/typescript-dts/classes/SVGRenderer.ts(1,29): error TS7016: Could not find a declaration file for module 'highcharts'. '/Users/goranslettemark/hs/highcharts/c
ode/highcharts.js' implicitly has an 'any' type.
test/typescript-dts/classes/Tick.ts(1,29): error TS7016: Could not find a declaration file for module 'highcharts'. '/Users/goranslettemark/hs/highcharts/code/hig
hcharts.js' implicitly has an 'any' type.
test/typescript-dts/classes/Utilities.ts(1,29): error TS7016: Could not find a declaration file for module 'highcharts'. '/Users/goranslettemark/hs/highcharts/cod
e/highcharts.js' implicitly has an 'any' type.
[09:00:59] Error: Command failed: npx tsc -p test/typescript-dts/classes

[09:00:59] 'lint-dts' errored after 660 ms
[09:00:59] Error: Command failed: npx tsc -p test/typescript-dts/classes

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:518:28)
    at ChildProcess.emit (node:domain:551:15)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)
```

```sh
➜  highcharts git:(tools/lint-dts) npx gulp jsdoc-namespace
[09:01:49] Using gulpfile ~/hs/highcharts/gulpfile.js
[09:01:49] Starting 'jsdoc-namespace'...
[09:01:49] Generating tree-namespace.json...
[09:01:50] ERROR: The @todo tag requires a value. File: dashboards.src.js, line: 3948

[09:01:50] ERROR: The @todo tag requires a value. File: dashboards.src.js, line: 3954

[09:02:05] JSDoc returned with error code: 1
[09:02:05] 'jsdoc-namespace' errored after 17 s
[09:02:05] Error: JSDoc closed with error code: 1
    at ChildProcess.<anonymous> (/Users/goranslettemark/hs/highcharts/node_modules/gulp-jsdoc3/dist/gulp-jsdoc.js:144:20)
    at ChildProcess.emit (node:events:518:28)
    at ChildProcess.emit (node:domain:551:15)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)
```

</details>

**Comment by bre1470** [comment]
Did you run `npx gulp scripts && npx gulp jsdoc-dts` before testing?

**Review by MarkusBarstad — APPROVED** [review]
Looks good!

I just want to see if I have gotten this correctly;

1. define ignored filepaths
2. grab all filepaths from code/ and subdirs
3. filter away any ignored
4. if "highcharts.src.js" is in the array, put it first
5. make options for gulp(the filepath array, tell gulp to not read files)
6. make options for jsdoc3(filepath to the plugin "highcharts.namespace")
7. throw error if no filepaths in our array
8. run and wait for scripts in "scripts/"
9. generate docs
10. then make tree-file for each of the product dirs

**Comment by bre1470** [comment]
> I just want to see if I have gotten this correctly;
> 
> 1. define ignored filepaths
> ...
> 10. then make tree-file for each of the product dirs

Yes, that is the plan in `jsdoc-namespace`.
It creates `tree-namespace.json` as called/consumed by `jsdoc-dts` and the result can be tested with `lint-dts`.

**Review by goransle — APPROVED** [review]
Works well when I built the declarations first 😬 👍

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
