### PR TITLE
bugfix/empty-area-svg-error

### PR DESCRIPTION
**Pull request by khlieng**
Fixed a regression, area series with empty data caused SVG error.

### CODE REVIEW

**Review by TorsteinHonsi — COMMENTED** [review]
How did this issue manifest? In this case it looks okay: https://jsfiddle.net/highcharts/qhact8ou/

Also, we have a generic test for all series types and no data/empty data. Maybe we should adapt that to catch this case? 

https://github.com/highcharts/highcharts/blob/908d8c4f7a25fe34f203a1bff2584fb2a7aad34a/samples/unit-tests/series/seriestypes/demo.js#L1-L43

**Comment by khlieng** [comment]
Its a unreleased regression caused by #14900, since its not a regular thrown error that can be caught that test didnt catch it.

**Comment by TorsteinHonsi** [comment]
How does it look then? What happens?

**Comment by khlieng** [comment]
Looks fine, just a console error: https://jsfiddle.net/grvfqnce/

**Comment by TorsteinHonsi** [comment]
Do you know where the regression comes from? Have you bisected? What changed? Why is this an issue now when it wasn't earlier?

Trying to understand why we need to add a check...

**Comment by khlieng** [comment]
The issue comes from the PR I linked above, which closes the path to make strokes look nicer, this PR prevents pushing the `Z` if the path is empty since setting `d` to just `Z` logs an error.

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
