### PR TITLE
bugfix/standalone-nav-remove-map

### PR DESCRIPTION
**Pull request by bm64**
Replaced map in standalone nav with es5 friendly code.

### CODE REVIEW

**Review by kamil-musialowski — APPROVED** [review]
LGTM (agree with Pawel's suggestion about `arr.length = 0`)

**Review by pawelfus — APPROVED** [review]
Very nice!

**Review by pawellysy — COMMENTED** [review]
| arr.length = 0 >  arr = []

I've heard somewhere, that it might've changed in newer JS and browser versions. Probably we could investigate further :)

**Review by pawellysy — APPROVED** [review]
LGTM

**Pull request merged**
