### PR TITLE
bugfix/21136-pointer-events-outside-of-plotarea

### LINKED ISSUE #21136: Click and hover events pass through x-axis
#### Expected behaviour

I have a scollable bar chart and there are items hiding under the x-axis. When I hover over the x-axis or click on the x-axis, the click should be ignored because the bars in that area are not visible.

#### Actual behaviour

Clicks trigger selections of rows (not shown in the demo). Hover events still trigger popups in the x-axis (shown in demo). Right-clicking in the spot shows the bar in the SVG as the topmost element.

image

#### Live demo with steps to reproduce

https://jsfiddle.net/jo3vm6s1/

This does not implement selection of items, but does show how the cursor events are triggering things for bars that are not visible.

#### Product version

* Highcharts JS v11.4.1 (2024-04-04)

#### Affected browser(s)

Chrome.

### PR DESCRIPTION
**Pull request by jedrzejruta**
Fixed #21136, pointer events were called on points outside of plot area with `scrollablePlotArea` enabled.

### CODE REVIEW

**Comment by jedrzejruta** [comment]
@TorsteinHonsi I'll dig around in upcoming week to find why it captures mouse events.

**Comment by jedrzejruta** [comment]
@TorsteinHonsi  After digging around a bit, it seems that the not visible part of the column isn't necessarily outside of the clip area after all. The `onMouseOver` event is added to the whole series group, and the scrollablePlotArea mask doesn't actually "cover" the mouse events. In my opinion, we can either go with the proposed solution or dive deeper into why the clip-path area allows mouse events.

**Review by TorsteinHonsi — APPROVED** [review]
Okay, thanks for checking it out! Let's just go with what we have then 👍

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
But now we have a conflict :(

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
