### PR TITLE
ts/packedbubble-series

### PR DESCRIPTION
**Pull request by bre1470**
Migrated packedbubble series to class pattern.

### CODE REVIEW

**Comment by bre1470** [comment]
@Izothep @sebastianbochan Can you confirm, that the diffs of the bubble series (packed bubble halo) are wrong? For me the candidate after migration looks more correct than the reference.

**Comment by bre1470** [comment]
Just to clarify: The reason that it differs is that now the packedbubble point inherits from the bubble point. With the old factory function it would inherit from the linepoint instead. Nevertheless I believe the new outcome in the visuals is correct.

**Comment by pawelfus** [comment]
I agree, the candidate's halo looks much better 👍

**Comment by Izothep** [comment]
I agree, the candidate is much better!

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
