### PR TITLE
hc71/gulp-tasks

### PR DESCRIPTION
**Pull request by bre1470**
- Contains several master merges
- Branch changes are limited to:
  - gulpfile.js & gulpfile.old.js
  - js/modules/networkgraph
  - test/typescript
  - tools/gulptasks

### CODE REVIEW

**Comment by bre1470** [comment]
@TorsteinHonsi Note: You have to merge this branch before merging the additional PR fix for timeline by @Denyllon

**Comment by TorsteinHonsi** [comment]
> Note: You have to merge this branch before merging the additional PR fix for timeline by @Denyllon

Woops. Seems like both you, I and Denyllon fixed the same issue... I'll be careful.

**Comment by Denyllon** [comment]
But all of us resolved the conflict in other way. Currently the tests are not passing and the `alignConnector` function is removed from Point class prototype, so I'll push my fix which resolves all the issues as fast as I can.

**Comment by TorsteinHonsi** [comment]
I removed the `alignConnector` function, didn't find it necessary and combined it with `drawConnector` to follow our usual pattern. All tests pass for me on `hc71/master`.

**Pull request merged**
