### PR TITLE
feature/navigator-handles-radius

### PR DESCRIPTION
**Pull request by pawellysy**
Added new option, [navigator.handles.borderRadius](https://api.highcharts.com/highstock/navigator.handles.borderRadius).

~~Added a new option: `borderRadius` for navigator handles. [See live here](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/navigator/handles/).~~

### CODE REVIEW

**Review by kamil-musialowski — APPROVED** [review]
Nice 🥳

**Review by DJTechnoo — APPROVED** [review]
Looking fresh!

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
Thanks, looks good! 

For the description (for the changelog) can you provide a link to the new feature? Also make sure to comply to changelog rules. No `camelCaseCode` without backticks (except links of course).

Edit: Also I'm wondering, instead of creating a single-purpose new demo, if we should just brush up the existing http://localhost:3030/samples/#view/stock/navigator/handles demo.

**Comment by pawellysy** [comment]
> Edit: Also I'm wondering, instead of creating a single-purpose new demo, if we should just brush up the existing http://localhost:3030/samples/#view/stock/navigator/handles demo.

I think that it is a good thing to have a single-purpose demo showing a specific feature, but in this case, we might as well incorporate it into the one you suggested. WDYT @pawelfus?

**Review by pawelfus — CHANGES_REQUESTED** [review]
Something is off:

Zrzut ekranu 2024-04-23 o 15 46 17
Zrzut ekranu 2024-04-23 o 15 46 13
 The vertical lines are blurry - old ones were good

**Comment by TorsteinHonsi** [comment]
I made another commit to avoid the large number of diffs, and to reduce the height of the rifles to a fixed number.

Let's wait for the visual diffs. Expected now is a 1px change at the top left of the handles in some cases. This is correct - the old stroke was buggy because the path was not correctly closed.

**Comment by pawelfus** [comment]
In general, I prefer a demo per option, but here we have a styling case. Similarly, we don't create demos for fontSize and fontColor, just merge them. However here, we already have two demos: 
- http://localhost:3030/samples/#view/stock/navigator/styled-handles (called "Styled handles")
- http://localhost:3030/samples/#view/stock/navigator/handles (called "Colored handles")

And none of them fits great. Let's keep separate samples, so we don't accidentally remove this option somewhere one the future.

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
