### PR TITLE
bugfix/21740-minorgridlines-break

### LINKED ISSUE #21749: Highcharts/Highstocks minor grid lines disappeared if there is a break
#### Expected behaviour
The minor grid lines should be displayed across the whole graph.

#### Actual behaviour
The minor grid lines disappeared when scrolling to the section with a break and reappear when there is no break.

#### Live demo with steps to reproduce

https://jsfiddle.net/BlackLabel/egL48m3u/

#### Product version

Latest?

#### Affected browser(s)
IE and Chrome

### PR DESCRIPTION
**Pull request by marvin19**
Fixed #21749, gridlines disappeared when axis had breaks.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208188452611537

### CODE REVIEW

**Review by hubertkozik — COMMENTED** [review]
Can I ask for the demo purpose? Should be mentioned somewhere in the docs or maybe it should be a manual test?

Also, did you consider unit test for this case? I think we can check if the `gridLine` is set correctly on ticks.

**Comment by marvin19** [comment]
> Can I ask for the demo purpose? Should be mentioned somewhere in the docs or maybe it should be a manual test?
> 
> Also, did you consider unit test for this case? I think we can check if the `gridLine` is set correctly on ticks.

@hubertkozik Made a sample for visual tests, but after some thinking I figured out a way to to the unit test after all! Can remove the demo if it is unecessary, and I also brought it with me into the unit-test.

**Review by Xillez — APPROVED** [review]
LGTM 👍

**Review by bre1470 — APPROVED** [review]
Works for me! 👍

**Review by TorsteinHonsi — CHANGES_REQUESTED** [review]
> Can remove the demo if it is unecessary, and I also brought it with me into the unit-test.

I think it would be better to remove it, since we already have the coverage, and we don't link to the demo from anywhere.

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
