### PR TITLE
Website/small demos

### PR DESCRIPTION
**Pull request by nasin**
Hi, I created small demos to take the place of the static "popular demos" section (under the hero.)

I set it up so that each product type has 4 demos that use a single demo.html file. The URL parameter "charts" tells demo.html which chart to load.

Here's a page that shows all the charts in action:
[https://www.goodwiththat.com/ag/demos/](https://www.goodwiththat.com/ag/demos/)

### CODE REVIEW

**Comment by nasin** [comment]
Hi, I fixed the demo.html file issues (sorry about the CSS...I was troubleshooting and forgot to remove it.)

I also changed the getJSON methods to fetch.

**Comment by nasin** [comment]
Hi, I also removed all of the different theme configurations and added references to the one JS theme file we've already published.

**Comment by TorsteinHonsi** [comment]
Awesome, thanks!

**Review by TorsteinHonsi — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
