### PR TITLE
bugfix/15799-rangeselector-offsetMin-selected

### LINKED ISSUE #15799: Range selector's button's offset not respected with pre-selected buttons
#### Expected behaviour
Button offsets should be respected with `rangeSelector.selected`

#### Actual behaviour
Only on clicking the button again, the offset is respected. 

#### Live demo with steps to reproduce
https://jsfiddle.net/8unLwe69/ - Try clicking the button 1 month after load

#### Product version
Highstock v9.1.0

#### Affected browser(s)
Chrome

### PR DESCRIPTION
**Pull request by khlieng**
Fixed #15799, `offsetMin` did not get applied by pre-selected range selector buttons.

### CODE REVIEW

**Review by pawelfus — CHANGES_REQUESTED** [review]
Doesn't work with other preselected ranges than year/month, for example: https://jsfiddle.net/BlackLabel/rwdz7a9s/

**Comment by TorsteinHonsi** [comment]
Pending Pawel's change request.

**Comment by TorsteinHonsi** [comment]
@pawelfus Can you follow up this? The original developer has been assigned to another project, so it would be great if your team can take over this one.

**Review by pawelfus — APPROVED** [review]
Thanks!

Pending @TorsteinHonsi review

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
