### PR TITLE
docs/morningstar-docs-structure

### PR DESCRIPTION
**Pull request by kamil-musialowski**
Initial structure for Morningstar docs.

### CODE REVIEW

**Comment by kamil-musialowski** [comment]
Internal test:

image

**Review by pawelfus — CHANGES_REQUESTED** [review]
Thanks for the preview!

Could we get rid of ".... Connector" in the menu list? If it's necessary to update docs in connector repo, it is fine.
387676649-ad1ce60e-61d7-4516-a99b-8171f64f3dc9

**Review by pawelfus — APPROVED** [review]
Thanks!

The merge with master branch can wait for v12 release first.

**Review by pawellysy — APPROVED** [review]

**Review by bm64 — APPROVED** [review]

**Review by DJTechnoo — APPROVED** [review]
Fantastic!

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
