### PR TITLE
bugfix/20359-scrollbar-same-extremes

### LINKED ISSUE #20359: scrollbar not working when xAxis.ceiling is 0
#### Expected behaviour
When scrollbar is enabled, and xAxis ceiling is 0, chart should show 1 category at a time, and allow scrolling.

#### Actual behaviour
When scrollbar is enabled, and xAxis ceiling is 0, and scrollbar.showFull is false, chart shows only 1 category, scroll bar is not visible, and there is no way to see the other categories. If showFull is true, scrollbar appears but does not work.

#### Live demo with steps to reproduce
https://jsfiddle.net/marklofdahl/zq27w4cp

#### Product version
Highstock 11

#### Affected browser(s)
All

### PR DESCRIPTION
**Pull request by K009**
Fixed #20359, scrollbar was not working when x-axis extremes were the same.

### CODE REVIEW

**Review by pawelfus — CHANGES_REQUESTED** [review]
Looks promising, but it seems the calculations are a bit off: https://jsfiddle.net/BlackLabel/ockqrjvz/1/ - start dragging, sometimes the chart jumps back and forth. I guess caused by a wrong extremes (range is below 1 unit):
Zrzut ekranu 2024-05-28 o 12 12 37

**Comment by pawelfus** [comment]
Yes, it looks good, however the width sometimes is incorrect (thus wrong extremes, or the other way around): https://jsfiddle.net/BlackLabel/ockqrjvz/2/ (see console).

My bet for the culprit goes for incorrect from/to, for example: https://jsfiddle.net/BlackLabel/ockqrjvz/6/ - gives zero visible points, because we zoom in between them. Increase the extremes' range, and we get the "correct" zoom (with visible points): https://jsfiddle.net/BlackLabel/ockqrjvz/7/

**Comment by pawelfus** [comment]
The problem with vanishing columns is related to cropping the data. While disabling it (`cropThreshold = 0`) - it works fine, demo: https://jsfiddle.net/BlackLabel/ockqrjvz/12/

**Review by pawelfus — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
