### PR TITLE
Limited impact of styled ColorAxis to fill color.

### PR DESCRIPTION
**Pull request by bre1470**
Also restored undocumented change in marker animation.

### CODE REVIEW

**Comment by TorsteinHonsi** [comment]
Thanks! Can you explain some more what this PR does?

> Limited impact of styled ColorAxis to fill color

What other impacts were there?

> Also restored undocumented change in marker animation.

How did that materialize?

**Comment by TorsteinHonsi** [comment]
Note that we now have this duplicate code, which I think was what the other PR tried to address by deleting the first one.

https://github.com/highcharts/highcharts/blob/288cd5fae85a87145d99ad07458c27626f77d0a9/ts/Core/Series/Series.ts#L2698-L2701

https://github.com/highcharts/highcharts/blob/288cd5fae85a87145d99ad07458c27626f77d0a9/ts/Core/Series/Series.ts#L2751-L2754

**Comment by bre1470** [comment]
- It was taking all styling attributes of the point, not just fill color.
- Also options of marker states where winning over CSS because of point styling attributes.

> Note that we now have this duplicate code, which I think was what the other PR tried to address by deleting the first one.
I did not notice this and will undo mine. I did not saw any relation to the fix and animations in the climate map have some flaws.

**Comment by bre1470** [comment]
> > Also restored undocumented change in marker animation.

> How did that materialize?

I did not test it, but I was speculating that it might have been related to random reposition animations when labels change.

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
