### PR TITLE
Added demo-config to samples folder

### PR DESCRIPTION
**Pull request by goransle**
Moved this config file from the highcharts-demo-manager repo. Related to #15370.

### CODE REVIEW

**Comment by karolkolodziej** [comment]
In the future, we might want to change the `name` in the demo details from `Highstock` to `Highcharts Stock` like [here](https://github.com/highcharts/highcharts/blob/12540607569b99467d91c447e23eb1d3b869e16d/samples/stock/indicators/ema/demo.details).
Will it make any difference for the demo builder?
FYI: @pawelfus

**Comment by goransle** [comment]
@karolkolodziej  `name` is used mainly for the page title, so that would not break anything. The demos which appear on [https://highcharts.com/demo](highcharts.com/demo), are selected by `tags` ([example .details file](https://github.com/highcharts/highcharts/blob/497b60df028d6a123d753bcb0140b3a1b28a517b/samples/stock/demo/arearange/demo.details)). I already changed these to `Highcharts Stock demo`, so they should be OK :)

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Comment by TorsteinHonsi** [comment]
@goransle Are the [samples/{product}/demo/index.htm](https://github.com/highcharts/highcharts/blob/feature/mapgeometry/samples/highcharts/demo/index.htm) files now redundant? In that case, they should be deleted.

**Comment by goransle** [comment]
@TorsteinHonsi  Yes, they should be redundant now. I will check and see.

**Pull request merged**
