### PR TITLE
v0.0.2 Release

### PR DESCRIPTION
**Pull request by pawelfus**

### CODE REVIEW

**Comment by bre1470** [comment]
It is hard to see the dashboard changes with all the master changes in-between.

**Comment by pawellysy** [comment]
@pawelfus maybe merge master before you merge dashboards/main?

**Comment by pawelfus** [comment]
> @pawelfus maybe merge master before you merge dashboards/main?

I don't think so.. That would mean we have something like this on `github.highcharts.com/dashboards/mvp` (remember: this is something clients use):
- v0.0.1 + HCv10 -> v0.0.1 + pre-HCv11 -> v0.0.2 + pre-HCv11

And that means:
- I would need to test both `v0.0.1 + pre-HCv11` and `v0.0.2 + pre-HCv11`
- In the future, if clients download in-between versions, that may cause confusion, unexpected bugs 

Note: This is merge current `main` into `mvp`. That means all commits/PR's were already reviewd by you (the team) :) That PR exists only because of agreed on branch-protection (no accident commits, at least one approve).

**Review by karolkolodziej — APPROVED** [review]

**Review by pawellysy — APPROVED** [review]
LGTM!

**Pull request merged**
