### PR TITLE
bugfix/DataConverter-type

### PR DESCRIPTION
**Pull request by karolkolodziej**
Fixed, added missing `DataConverter` type in `DataConnector`.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207744726847053

### CODE REVIEW

**Review by bre1470 — CHANGES_REQUESTED** [review]
I need access to the base class code itself, not an instance type / property. I have to fulfil all of the DataConnector API when implementing a new connector with converter.

So I need the DataConverter class attached to the Dashboards / DataGrid namespaces in masters.

**Comment by karolkolodziej** [comment]
Sorry, I didn't get the assignment. Do we need the same for `DataEvents`?

**Comment by bre1470** [comment]
Sorry, no problem. My previous comment was not meant to sound rude. I probably need DataEvents in the declarations, but it seems to be only types, so nothing for masters to add.

**Review by bre1470 — APPROVED** [review]
Awesome! This works now. 👍

**Review by sebastianbochan — APPROVED** [review]

**Pull request merged**
