### PR TITLE
bugfix/21884-measure-annotation-border

### LINKED ISSUE #21884: Measure Annotation:  Issue with rendering the border on stocktools
#### Expected behaviour
1. Border/Stroke should render for all sides.
2. Left, right, top and bottom of the stroke width should be consistent
Screenshot 2024-09-20 163317

#### Actual behaviour
1. Border/Stroke is not rendering for left side. Check the attached screenshot
2. Inconsistent stroke width for horizontal and vertical sides
Screenshot 2024-09-20 163850

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/0p4zuy82/

#### Product version
Highstock JS v11.4.8 (2024-08-29)

#### Affected browser(s)
All Browers chrome, edge etc.

### PR DESCRIPTION
**Pull request by pawellysy**
Fixed #21884, rendering issues with the borders of the Measure annotation.

Measure annotation's border was missing on 1 side, and the size of measure's rectangle didn't take into account the border, and also the border's dimension wasn't included in size calculation.

### CODE REVIEW

**Review by pawelfus — CHANGES_REQUESTED** [review]
~~Approving only because there's refactor (path -> rect). This solution breaks the animation of the shape, when the border exists.~~

Requesting a test, so the future refactor will be safe.

**Review by bm64 — APPROVED** [review]

**Review by kamil-musialowski — APPROVED** [review]
lgtm!

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by DJTechnoo — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
