### PR TITLE
docs: fill up the missing jsdoc for classes and series types

### PR DESCRIPTION
**Pull request by e-cloud**
add these docs is to generate `highcharts.d.ts` at the next step. 

Seperating the changes into two PR is good for reviewing.

partly fix https://github.com/highcharts/highcharts/issues/4876

@TorsteinHonsi could you have a review over this.

> Note: all of changes only involve comment improvement.

### CODE REVIEW

**Comment by e-cloud** [comment]
@TorsteinHonsi could you have a look? or close it. Leaving it hanging is a waste of time.

**Comment by scott-ho** [comment]
@oysteinmoseng could you have a review? It seems good.

**Comment by TorsteinHonsi** [comment]
Thanks for the PR!

Our main purpose of the JSDoc doclets is to generate our [class reference](https://api.highcharts.com/class-reference/Highcharts) and options reference. The existing doclets that show up in the class reference are carefully revised to be informative to our users. Unfortunately, the remaining code is not revised. So exposing those doclets results in some inconsistencies and errors in the generated documentation, plus there are internal functions that we don't want to document because they may change in the future etc.

skjermbilde 2018-05-15 kl 14 24 42

**Comment by e-cloud** [comment]
@TorsteinHonsi you are right. Then I make a plugin to filter out those accidentally exposed docs.

**Comment by e-cloud** [comment]
@TorsteinHonsi you are right. Then I make a plugin to filter out those accidentally exposed docs.

could you have a review again? The extra docs must be filtered out now.

**Comment by oysteinmoseng** [comment]
Torstein is on vacation at the moment, but let's have a look.

@cvasseng Is this something we can pull in?

**Comment by TorsteinHonsi** [comment]
Thanks again for your contribution @e-cloud !

We are now continuing the work on our own TypeScript support, and will take this PR into account.

**Comment by e-cloud** [comment]
sounds good. @TorsteinHonsi  did you have a look over the **ref** branch? a `highcharts.d.td` is auto generated. Although it is not perfect yet. But we can continue to improve jsdoc or improve the types directly.

BTW, could you reveal the plan of `our own typescript support`

**Comment by sophiebremer** [comment]
@e-cloud
First of all I like to thank you for the work, you have done here. We are still reviewing your massive changes and will probably integrate part of it into Highcharts. Unfortunately there are still some unresolved issues, so for now everything is in-between. We will integrate the pull request at the end of this.

We are working internally since last year on the problem (with lower priority until recently). The goal beside declarations is to synchronize the online documentation and the declarations for TypeScript. Thanks to your contribution we might speed this up and hopefully have working declarations in the near future. We then will integrate it in our node package and also provide it to the definitelyTyped project to replace the current declarations there.

**Comment by e-cloud** [comment]
@sophiebremer Could you point out the unresolved issues to see if I could solve them?

**Comment by sophiebremer** [comment]
@e-cloud No, I am sorry. These issues are about synchronization.

**Comment by e-cloud** [comment]
@sophiebremer what do you mean by synchronization? If you mean branch synchronization, I've rebase the branch to latest master two days ago.

**Pull request closed without merging**
