### PR TITLE
add travis.yml

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@TorsteinHonsi I can't work out how to get the tests running.

Is there some documentation on how to run them? It seems JQuery isn't in the repo...

**Comment by TorsteinHonsi** [comment]
See https://github.com/highcharts/highcharts/tree/master/utils

**Comment by graingert** [comment]
@TorsteinHonsi as in I can't work out how to get ANT to run them.

**Comment by TorsteinHonsi** [comment]
You can't, we only run ant for packaging and deploying, and soon we'll abandon it for that as well. However, you can run `gulp test` which runs the test suite through PhantomJS.

**Comment by graingert** [comment]
Ah cool I'll configure Travis for that. Are you up for Travis support?

**Comment by graingert** [comment]
@TorsteinHonsi it's mysteriously broken, is there any documentation for how to run the automated tests?

**Comment by graingert** [comment]
If not, can you take over this PR?

**Comment by graingert** [comment]
@TorsteinHonsi why did you close this?

**Pull request closed without merging**
