### PR TITLE
bugfix/15902-legend-proxy-series-update

### LINKED ISSUE #15902: A11Y Proxy Container doesn't update when chart data updates
#### Expected behaviour

When the series of a chart changes, the hidden A11Y buttons/elements should update as well.

#### Actual behaviour
The A11Y buttons still displays the original series.

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/kz5yneb6/

Open the console, click the button and notice that the original series is still listed

#### Product version
Highcharts 9.1.1 with Accessibility Module

#### Affected browser(s)
Chrome

Note: I originally reported this in [highcharts-react](https://github.com/highcharts/highcharts-react/issues/303) and Paweł sent me here.

### PR DESCRIPTION
**Pull request by khlieng**
Fixed #15902, legend proxy buttons did not update when updating series.

- [x] Fix `addSeries` too?

### CODE REVIEW

**Comment by TorsteinHonsi** [comment]
> Fix addSeries too?

It should reflect all CRUD operations, right @oysteinmoseng ?

**Comment by oysteinmoseng** [comment]
Yes, this is just an HTML overlay for the legend, so needs to update whenever the legend moves somewhere (`chart.update`) or has changed content. Also note `series.addPoint` if we have points in the legend (e.g. in pies).

Without testing, it looks like the current solution would be good if we also recreate the proxies if the list of proxies doesn't match the series/points.

Honestly we could probably get away with always just recreating them on every render as well, since there aren't usually that many legend items..

**Comment by khlieng** [comment]
Should probably just try to find some way to check if the legend has been dirty.

**Comment by oysteinmoseng** [comment]
Yes, perhaps instead of doing this on `chart.render` it would be better to attach an event (use the EventProvider) to whenever the legend has re-rendered

**Comment by TorsteinHonsi** [comment]
If it is hooked up to `Legend.renderItem` or `Legend.layoutItem` it should automagically handle whatever is thrown at it. Or use the Legend `afterRender` event, which can access `Legend.allItems`.

**Review by TorsteinHonsi — APPROVED** [review]
Looks good to me 👍 . Pending approval by @oysteinmoseng .

**Review by oysteinmoseng — APPROVED** [review]
Nice work!

**Pull request merged**
