### PR TITLE
bugfix/15727-annotation-popup-input-selection

### LINKED ISSUE #15727: Stock Tools: Selecting input in popup and firing event mouseup outside the popup hides it
#### Expected behaviour
Text in the input should be highlighted and editable. The popup should not hide

#### Actual behaviour
Popup disappears

#### Live demo with steps to reproduce
[Demo](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/demo/stock-tools-gui)

drag popup

#### Product
Highcharts Stock

### PR DESCRIPTION
**Pull request by khlieng**
Fixed #15727, annotation popup was hidden when dragging from input to outside popup.

This PR needs #15748.

### CODE REVIEW

**Comment by khlieng** [comment]
But we still want to be able to close the popup by clicking outside it right? I think we could just add my event handler to the popup itself instead.

**Comment by pawelfus** [comment]
> But we still want to be able to close the popup by clicking outside it right?

Of course, we still want this

**Comment by pawelfus** [comment]
It doesn't seem to be fixed: https://jsfiddle.net/BlackLabel/30Lpdz2r/

**Comment by pawelfus** [comment]
Ah, right, my bad, sorry!

**Comment by khlieng** [comment]
@TorsteinHonsi this one should be ready now.

**Review by TorsteinHonsi — APPROVED** [review]
Thanks! Pending final approval from @pawelfus

**Review by pawelfus — CHANGES_REQUESTED** [review]
Thanks, looks good! Just missing a Cypress test

**Comment by TorsteinHonsi** [comment]
@khlieng Pending Pawel's request

**Review by pawelfus — APPROVED** [review]
Thanks!

**Review by TorsteinHonsi — APPROVED** [review]

**Pull request merged**
