### PR TITLE
Migration of StockTools

### PR DESCRIPTION
**Pull request by bre1470**
Based & pending on PR https://github.com/highcharts/highcharts/pull/17505

- Added StockTools compositions
- Splitted classes / helpers
- Improved typing
- Removed internal namespace

### CODE REVIEW

**Comment by bre1470** [comment]
Review of Stock Tools only: https://github.com/highcharts/highcharts/compare/ts/annotations-types...ts/stocktools

**Comment by sebastianbochan** [comment]
I have only the problem with TS
- a lot of castings to "any"
- `StockToolsGuiDefinitionsButtonOptions` and `StockToolsGuiDefinitionsButtonsOptions` are really similar in names (so its confusing a bit). I'm also thinking about rearranging types and using something like `Array<StockToolsGuiDefinitionsButtonOptions>` or considering a generic type. However its only a kind of a thing for consideration.

**Comment by bre1470** [comment]
Thanks for the review! I agree with your comment points. StockTools needs more type improvements.

Focus of this PR though is getting it ESM-compatible. Maybe you can take over after merge.

**Review by sebastianbochan — APPROVED** [review]

**Review by TorsteinHonsi — APPROVED** [review]
Thanks!

**Pull request merged**
