### PR TITLE
db/climate-demo-datagrid

### PR DESCRIPTION
**Pull request by sebastianbochan**
- [x] - disable the edit option in the Datagrid
- [x] - sync with chart
- [x] - bug in es-modules
- [x] - problem with sync

### CODE REVIEW

**Review by goransle — APPROVED** [review]
Looks good!

**Review by karolkolodziej — CHANGES_REQUESTED** [review]
Good idea with the whole `rowXIndex` concept ;) 

Could you please only see why the last few rows are not visible in the `dataGrid`? Perhaps add some CSS styles here :)

**Comment by sebastianbochan** [comment]
The issue is caused by the commit: https://github.com/highcharts/highcharts/commit/79e10afad9614bd59052c3c2793c96c17b7dd6fa

**Comment by bre1470** [comment]
I think the commit just triggers the issue. The datagrid is larger than the component space, because of the headline, therefor rows are hidden.

**Comment by sebastianbochan** [comment]
Problem with overflow has been fixed.

@bre1470 @karolkolodziej

**Review by karolkolodziej — APPROVED** [review]

**Review by bre1470 — APPROVED** [review]
Behind the scenes there are still rows rendered outside the visible area. These need to eventually be removed or otherwise the last ones are never visible.

Screenshot 2023-01-19 at 12 20 03

**Comment by sebastianbochan** [comment]
I think that its a completely different issue and it is a problem with datagrid inside. 

There is a few issues f.e elements positioned absolutely etc. So I think that we should refactor datagrid in the future.

**Pull request merged**
